### **Read Files in Pandas**
Pandas provides functions to read data from files and write data to files. This is one of the most important skills in data analysis.

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Format</th>
<th>Read</th>
<th>Write</th>
</tr>
<tr>
<td>CSV</td>
<td>read_csv()</td>
<td>to_csv()</td>
</tr>
<tr>
<td>Excel</td>
<td>read_excel()</td>
<td>to_excel()</td>
</tr>
<tr>
<td>JSON</td>
<td>read_json()</td>
<td>to_json()</td>
</tr>
<tr>
<td>SQL</td>
<td>read_sql()</td>
<td>to_sql()</td>
</tr>
</table>



#### **Problem with Windows paths**

**Suppose you write:**
```python
path = 'C:\newfolder\test.csv'
print(path)
```

**Python sees:**

- \n → New line
- \t → Tab

**Output:**
```
C:
ewfolder    est.csv
```
So the path becomes corrupted.

**Solution: Use raw string (r)**
```python
path = r'C:\newfolder\test.csv'
```

Now Python treats every backslash literally.
This is the most common method.

#### 1. **CSV**

##### **Read CSV**

In [1]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Employees.csv')
df

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]

##### **Important Arguments**
<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Argument</th>
<th>Purpose</th>
</tr>
<tr>
<td><i>sep</i></td>
<td>Delimiter</td>
</tr>
<tr>
<td><i>header</i></td>
<td>Header row number</td>
</tr>
<tr>
<td><i>names</i></td>
<td>Custom column names</td>
</tr>
<tr>
<td><i>usecols</i></td>
<td>Read selected columns</td>
</tr>
<tr>
<td><i>index_col</i></td>
<td>Set index column</td>
</tr>
<tr>
<td><i>skiprows</i></td>
<td>Skip rows</td>
</tr>
<tr>
<td><i>nrows</i></td>
<td>Read limited rows</td>
</tr>
<tr>
<td><i>na_values</i></td>
<td>Treat values as NaN</td>
</tr>
<tr>
<td><i>encoding</i></td>
<td>File encoding</td>
</tr>
</table>

In [2]:
df = pd.read_csv(
    r'sample_datasets\Employees.csv',
    header=0,
    names=['emp_id', 'emp_name', 'emp_age', 'emp_dep', 'emp_sal', 'emp_exp'],
    usecols=['emp_id','emp_name', 'emp_sal'],
    index_col='emp_id',
    nrows=10,
    skiprows=1,
    na_values=['Karan Nair'])
df

            emp_name  emp_sal
emp_id
1002     Sneha Kumar    28124
1003     Neha Sharma    40488
1004    Arjun Sharma    42973
1005             NaN    35200
1006     Divya Verma    33247
1007    Sanjay Kumar    73268
1008     Rahul Patel    40369
1009     Sneha Menon    55491
1010     Divya Mehta    47330
1011      Neha Gupta    64790

#### 2. **Excel**

##### **Read Excel**

Install Excel support:
```bash
pip install openpyxl
```

In [3]:
df = pd.read_excel(r'sample_datasets\Employees.xlsx')
df

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]

##### **Important Arguments**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Argument</th>
<th>Purpose</th>
</tr>
<tr>
<td><i>sheet_name</i></td>
<td>Sheet to read</td>
</tr>
<tr>
<td><i>usecols</i></td>
<td>Read selected columns</td>
</tr>
<tr>
<td><i>index_col</i></td>
<td>Set index column</td>
</tr>
<tr>
<td><i>skiprows</i></td>
<td>Skip rows</td>
</tr>
<tr>
<td><i>nrows</i></td>
<td>Read limited rows</td>
</tr>
</table>

In [4]:
df = pd.read_excel(
    r'sample_datasets\Employees.xlsx',
    sheet_name=['IT Department'],
    usecols='A:E',
    names=['emp_id', 'emp_name', 'emp_age', 'emp_dep', 'emp_sal'],
    index_col=0,
    nrows=5)
df

{'IT Department':                emp_name  emp_age emp_dep  emp_sal
 emp_id
 1002        Sneha Kumar       49      IT    28124
 1016    Vikram Malhotra       27      IT    28834
 1022         Aarav Nair       53      IT    60402
 1032         Meera Bose       51      IT    95814
 1040         Priya Nair       25      IT    41292}

#### 3. **JSON**
##### **Read JSON**

In [5]:
df = pd.read_json(r'sample_datasets\Employees.json')
df

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]

#### 4. **Text File**
##### **Read Txt File**

In [6]:
df = pd.read_csv(r'sample_datasets\Employees.txt', sep='\t')
df

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]