### **Data Exploration**

Data exploration means understanding your dataset before analyzing or processing it. It helps you answer questions like:

- How many rows and columns are there?
- What are the column names?
- What are the data types?
- Are there missing values?
- What are the basic statistics?

In [1]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Employees.csv')

#### 1. **head()**

Displays the first 5 rows by default.

In [2]:
df.head()

   EmpID          Name  Age   Department  Salary  Experience
0   1001  Sneha Sharma   39        Sales   45401           7
1   1002   Sneha Kumar   49           IT   28124           0
2   1003   Neha Sharma   34  Engineering   40488           3
3   1004  Arjun Sharma   32  Engineering   42973           5
4   1005    Karan Nair   28           HR   35200           3

In [3]:
df.head(3) # Displays first 3 rows

   EmpID          Name  Age   Department  Salary  Experience
0   1001  Sneha Sharma   39        Sales   45401           7
1   1002   Sneha Kumar   49           IT   28124           0
2   1003   Neha Sharma   34  Engineering   40488           3

#### 2. **tail()**

Displays the last 5 rows.

In [4]:
df.tail()

    EmpID          Name  Age Department  Salary  Experience
95   1096  Aditya Verma   45    Finance   88574          19
96   1097   Sneha Gupta   41         HR   68270          18
97   1098   Pooja Menon   47      Sales   39789           2
98   1099    Neha Reddy   41         HR   90979          18
99   1100    Divya Bose   45         HR   81131          16

In [5]:
df.tail(3) # Displays the last 3 rows

    EmpID         Name  Age Department  Salary  Experience
97   1098  Pooja Menon   47      Sales   39789           2
98   1099   Neha Reddy   41         HR   90979          18
99   1100   Divya Bose   45         HR   81131          16

#### 3. **shape**

Returns the number of rows and columns.

In [6]:
df.shape

(100, 6)

Meaning:
- 100 rows
- 6 columns

#### 4. **columns**

Shows all column names.

In [7]:
df.columns

Index(['EmpID', 'Name', 'Age', 'Department', 'Salary', 'Experience'], dtype='str')

Convert to a list:

In [8]:
list(df.columns)

['EmpID', 'Name', 'Age', 'Department', 'Salary', 'Experience']

#### 5. **index**

Shows row labels.

In [9]:
df.index

RangeIndex(start=0, stop=100, step=1)

#### 6. **dtypes**

Shows the data type of each column.

Common data types:

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Type</th>
<th>Meaning</th>
</tr>
<tr>
<td><i>int64</i></td>
<td>Integer</td>
</tr>
<tr>
<td><i>float64</i></td>
<td>Decimal number</td>
</tr>
<tr>
<td><i>object</i></td>
<td>String/Text</td>
</tr>
<tr>
<td><i>bool</i></td>
<td>True/False</td>
</tr>
<tr>
<td><i>datetime64</i></td>
<td>Date &amp; Time</td>
</tr>
</table>

In [10]:
df.dtypes

EmpID         int64
Name            str
Age           int64
Department      str
Salary        int64
Experience    int64
dtype: object

#### 7. **info()**

Provides a summary of the DataFrame.

It shows:

- Number of rows
- Number of columns
- Non-null values
- Data types
- Memory usage

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmpID       100 non-null    int64
 1   Name        100 non-null    str
 2   Age         100 non-null    int64
 3   Department  100 non-null    str
 4   Salary      100 non-null    int64
 5   Experience  100 non-null    int64
dtypes: int64(4), str(2)
memory usage: 6.5 KB

#### 8. **describe()**

Shows statistical summary for numeric columns.

In [12]:
df.describe()

             EmpID         Age         Salary  Experience
count   100.000000  100.000000     100.000000  100.000000
mean   1050.500000   38.740000   59746.430000    9.070000
std      29.011492    9.450156   24934.292013    8.029309
min    1001.000000   22.000000   28027.000000    0.000000
25%    1025.750000   32.000000   40120.500000    2.000000
50%    1050.500000   38.000000   53300.000000    7.000000
75%    1075.250000   47.000000   76978.250000   14.000000
max    1100.000000   55.000000  119960.000000   30.000000

Meaning:

- *count* → Number of values
- *mean* → Average
- *std* → Standard deviation
- *min* → Smallest value
- *25%, 50%, 75%* → Quartiles
- *max* → Largest value

#### 9. **isnull() or isna()**

Checks for missing values.

Returns: *True/False*

In [13]:
df.isnull()

    EmpID   Name    Age  Department  Salary  Experience
0   False  False  False       False   False       False
1   False  False  False       False   False       False
2   False  False  False       False   False       False
3   False  False  False       False   False       False
4   False  False  False       False   False       False
..    ...    ...    ...         ...     ...         ...
95  False  False  False       False   False       False
96  False  False  False       False   False       False
97  False  False  False       False   False       False
98  False  False  False       False   False       False
99  False  False  False       False   False       False

[100 rows x 6 columns]

Count missing values:

In [14]:
df.isnull().sum()

EmpID         0
Name          0
Age           0
Department    0
Salary        0
Experience    0
dtype: int64

#### 10. **nunique()**

Counts unique values.

In [15]:
df.nunique()

EmpID         100
Name           86
Age            33
Department      8
Salary        100
Experience     26
dtype: int64

#### 11. **value_counts()**

Counts occurrences of unique values.

In [16]:
df['Department'].value_counts()

Department
HR             21
Engineering    20
Sales          14
Marketing      12
Support        11
Finance         9
IT              7
Operations      6
Name: count, dtype: int64

In [17]:
df['Name'].value_counts()

Name
Sneha Kumar     2
Aditya Verma    2
Rohan Reddy     2
Karan Singh     2
Pooja Rao       2
               ..
Neha Singh      1
Sneha Gupta     1
Pooja Menon     1
Neha Reddy      1
Divya Bose      1
Name: count, Length: 86, dtype: int64

#### 12. **sample()**

Returns random rows.

In [18]:
df.sample(4)

    EmpID          Name  Age Department  Salary  Experience
53   1054   Divya Singh   49    Finance   33257           1
39   1040    Priya Nair   25         IT   41292           3
84   1085   Aarav Menon   52         IT  109273          30
12   1013  Sanjay Verma   26      Sales   50021           4

In [19]:
df.sample(3)

    EmpID         Name  Age   Department  Salary  Experience
11   1012    Neha Nair   25        Sales   36660           0
43   1044    Rohan Rao   38  Engineering   46747           4
7    1008  Rahul Patel   36    Marketing   40369           1

**Most Important Data Exploration Methods**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Method</th>
<th>Purpose</th>
</tr>
<tr>
<td><i>head()</i></td>
<td>First rows</td>
</tr>
<tr>
<td><i>tail()</i></td>
<td>Last rows</td>
</tr>
<tr>
<td><i>shape</i></td>
<td>Rows and columns</td>
</tr>
<tr>
<td><i>columns</i></td>
<td>Column names</td>
</tr>
<tr>
<td><i>index</i></td>
<td>Row labels</td>
</tr>
<tr>
<td><i>dtypes</i></td>
<td>Data types</td>
</tr>
<tr>
<td><i>info()</i></td>
<td>Complete summary</td>
</tr>
<tr>
<td><i>describe()</i></td>
<td>Statistics</td>
</tr>
<tr>
<td><i>isnull().sum()</i></td>
<td>Missing values</td>
</tr>
<tr>
<td><i>nunique()</i></td>
<td>Unique count</td>
</tr>
<tr>
<td><i>value_counts()</i></td>
<td>Frequency count</td>
</tr>
<tr>
<td><i>sample()</i></td>
<td>Random row</td>
</tr>
</table>