### **Column Selection in Pandas**

Column selection means choosing one or more columns from a DataFrame.

In [1]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Employees.csv')
df

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]

#### 1. **Select a Single Column**

**Method 1:** Bracket Notation (Recommended)

In [2]:
df['Name']

0     Sneha Sharma
1      Sneha Kumar
2      Neha Sharma
3     Arjun Sharma
4       Karan Nair
          ...
95    Aditya Verma
96     Sneha Gupta
97     Pooja Menon
98      Neha Reddy
99      Divya Bose
Name: Name, Length: 100, dtype: str

**Method 2:** Dot Notation

In [3]:
df.Name

0     Sneha Sharma
1      Sneha Kumar
2      Neha Sharma
3     Arjun Sharma
4       Karan Nair
          ...
95    Aditya Verma
96     Sneha Gupta
97     Pooja Menon
98      Neha Reddy
99      Divya Bose
Name: Name, Length: 100, dtype: str

⚠️ Use only when:

- Column name has no spaces
- Column name is a valid Python identifier

Example:

```python
df.Employee Name    # Error
```

#### 2. **Select Multiple Columns**

In [4]:
df[['Name', 'Salary']]

            Name  Salary
0   Sneha Sharma   45401
1    Sneha Kumar   28124
2    Neha Sharma   40488
3   Arjun Sharma   42973
4     Karan Nair   35200
..           ...     ...
95  Aditya Verma   88574
96   Sneha Gupta   68270
97   Pooja Menon   39789
98    Neha Reddy   90979
99    Divya Bose   81131

[100 rows x 2 columns]

##### **Remember**

- Single Brackets [] → Returns a Series

- Double Brackets [[]] → Returns a DataFrame

In [5]:
result1 = df['Name']
result2 = df[['Name', 'Salary']]
print(type(result1))
print(type(result2))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

#### 3. **Select All Columns**

In [6]:
df

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]

In [7]:
df.columns

Index(['EmpID', 'Name', 'Age', 'Department', 'Salary', 'Experience'], dtype='str')


#####  ***loc* and *iloc* in Pandas**

*loc* and *iloc* are the two main indexing methods in Pandas. They are used to select rows, columns, or both.

*************************************************************************************************************
1. ***iloc* (Integer Position-Based Indexing)**

*iloc* selects data using integer positions.

**Syntax:**

```python
df.iloc[row_position, column_position]
```
*************************************************************************************************************
2. ***loc* (Label-Based Indexing)**

*loc* selects data using row labels (index names) and column labels (column names).

**Syntax:**
```python
df.loc[row_label, column_label]
```
*************************************************************************************************************

#### 4. **Select Columns by Position**

- Using *iloc*

**Syntax:**
```python
df.iloc[rows, columns]
```

- : = all rows
- 0:2 = columns 0 and 1


1. **Select a Single Column Using *iloc***

In [8]:
df.iloc[:,0]

0     1001
1     1002
2     1003
3     1004
4     1005
      ...
95    1096
96    1097
97    1098
98    1099
99    1100
Name: EmpID, Length: 100, dtype: int64

2. **Select Multiple Columns Using *iloc***

In [9]:
df.iloc[:, [1,3,5]]

            Name   Department  Experience
0   Sneha Sharma        Sales           7
1    Sneha Kumar           IT           0
2    Neha Sharma  Engineering           3
3   Arjun Sharma  Engineering           5
4     Karan Nair           HR           3
..           ...          ...         ...
95  Aditya Verma      Finance          19
96   Sneha Gupta           HR          18
97   Pooja Menon        Sales           2
98    Neha Reddy           HR          18
99    Divya Bose           HR          16

[100 rows x 3 columns]

3. **Select a Range of Columns Using *iloc***

In [10]:
df.iloc[:, 1:4]

            Name  Age   Department
0   Sneha Sharma   39        Sales
1    Sneha Kumar   49           IT
2    Neha Sharma   34  Engineering
3   Arjun Sharma   32  Engineering
4     Karan Nair   28           HR
..           ...  ...          ...
95  Aditya Verma   45      Finance
96   Sneha Gupta   41           HR
97   Pooja Menon   47        Sales
98    Neha Reddy   41           HR
99    Divya Bose   45           HR

[100 rows x 3 columns]


#### 5. **Select Columns by Label**

- Using *loc*

**Syntax:**

```python
df.loc[rows, columns]
```

1. **Select Columns using *loc***

In [11]:
df.loc[:, ['Name', 'Department']]

            Name   Department
0   Sneha Sharma        Sales
1    Sneha Kumar           IT
2    Neha Sharma  Engineering
3   Arjun Sharma  Engineering
4     Karan Nair           HR
..           ...          ...
95  Aditya Verma      Finance
96   Sneha Gupta           HR
97   Pooja Menon        Sales
98    Neha Reddy           HR
99    Divya Bose           HR

[100 rows x 2 columns]

2. **Select a Range of Columns Using *loc***

*loc* includes both start and end labels.

In [12]:
df.loc[:, 'Name':'Salary']

            Name  Age   Department  Salary
0   Sneha Sharma   39        Sales   45401
1    Sneha Kumar   49           IT   28124
2    Neha Sharma   34  Engineering   40488
3   Arjun Sharma   32  Engineering   42973
4     Karan Nair   28           HR   35200
..           ...  ...          ...     ...
95  Aditya Verma   45      Finance   88574
96   Sneha Gupta   41           HR   68270
97   Pooja Menon   47        Sales   39789
98    Neha Reddy   41           HR   90979
99    Divya Bose   45           HR   81131

[100 rows x 4 columns]

#### 6. **Select Columns Using a List Variable**

In [13]:
columns = ['Name', 'Experience', 'Salary']
df[columns]

            Name  Experience  Salary
0   Sneha Sharma           7   45401
1    Sneha Kumar           0   28124
2    Neha Sharma           3   40488
3   Arjun Sharma           5   42973
4     Karan Nair           3   35200
..           ...         ...     ...
95  Aditya Verma          19   88574
96   Sneha Gupta          18   68270
97   Pooja Menon           2   39789
98    Neha Reddy          18   90979
99    Divya Bose          16   81131

[100 rows x 3 columns]

#### 7. **Select Columns Based on Data Type**

**Numeric Columns**

In [14]:
df.select_dtypes(include='number')

    EmpID  Age  Salary  Experience
0    1001   39   45401           7
1    1002   49   28124           0
2    1003   34   40488           3
3    1004   32   42973           5
4    1005   28   35200           3
..    ...  ...     ...         ...
95   1096   45   88574          19
96   1097   41   68270          18
97   1098   47   39789           2
98   1099   41   90979          18
99   1100   45   81131          16

[100 rows x 4 columns]

**String Columns**

In [15]:
df.select_dtypes(include='object')

C:\Users\shaik\AppData\Local\Temp\ipykernel_6200\676392701.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object')

            Name   Department
0   Sneha Sharma        Sales
1    Sneha Kumar           IT
2    Neha Sharma  Engineering
3   Arjun Sharma  Engineering
4     Karan Nair           HR
..           ...          ...
95  Aditya Verma      Finance
96   Sneha Gupta           HR
97   Pooja Menon        Sales
98    Neha Reddy           HR
99    Divya Bose           HR

[100 rows x 2 columns]

In [16]:
df.select_dtypes(include='string')

            Name   Department
0   Sneha Sharma        Sales
1    Sneha Kumar           IT
2    Neha Sharma  Engineering
3   Arjun Sharma  Engineering
4     Karan Nair           HR
..           ...          ...
95  Aditya Verma      Finance
96   Sneha Gupta           HR
97   Pooja Menon        Sales
98    Neha Reddy           HR
99    Divya Bose           HR

[100 rows x 2 columns]

**Most Important Methods for Data Analysis**
```python
df["column"]                  # Single column
df[["col1", "col2"]]          # Multiple columns
df.loc[:, ["col1", "col2"]]   # By labels
df.iloc[:, [0, 2]]            # By positions
df.select_dtypes()            # By data type
df.columns                    # View column names
```
These are the column selection methods you'll use most often in pandas data analysis.