### **Row Selection in Pandas**

Row selection means choosing specific rows from a DataFrame.

#####  ***loc* and *iloc* in Pandas**

*loc* and *iloc* are the two main indexing methods in Pandas. They are used to select rows, columns, or both.

*************************************************************************************************************
1. ***iloc* (Integer Position-Based Indexing)**

*iloc* selects data using integer positions.

**Syntax:**

```python
df.iloc[row_position, column_position]
```
*************************************************************************************************************
2. ***loc* (Label-Based Indexing)**

*loc* selects data using row labels (index names) and column labels (column names).

**Syntax:**

```python
df.loc[row_label, column_label]
```
*************************************************************************************************************

In [1]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Employees.csv', index_col='EmpID')
df

               Name  Age   Department  Salary  Experience
EmpID
1001   Sneha Sharma   39        Sales   45401           7
1002    Sneha Kumar   49           IT   28124           0
1003    Neha Sharma   34  Engineering   40488           3
1004   Arjun Sharma   32  Engineering   42973           5
1005     Karan Nair   28           HR   35200           3
...             ...  ...          ...     ...         ...
1096   Aditya Verma   45      Finance   88574          19
1097    Sneha Gupta   41           HR   68270          18
1098    Pooja Menon   47        Sales   39789           2
1099     Neha Reddy   41           HR   90979          18
1100     Divya Bose   45           HR   81131          16

[100 rows x 5 columns]

#### 1. **Select Rows by Position**

- Using *iloc*

1. **Select a Single Row using *iloc***

In [2]:
df.iloc[1]

Name          Sneha Kumar
Age                    49
Department             IT
Salary              28124
Experience              0
Name: 1002, dtype: object

2. **Select Multiple Rows using *iloc***

In [3]:
df.iloc[[0,2]]

               Name  Age   Department  Salary  Experience
EmpID
1001   Sneha Sharma   39        Sales   45401           7
1003    Neha Sharma   34  Engineering   40488           3

3. **Select a Range of Rows using iloc**

In [4]:
df.iloc[0:3]

               Name  Age   Department  Salary  Experience
EmpID
1001   Sneha Sharma   39        Sales   45401           7
1002    Sneha Kumar   49           IT   28124           0
1003    Neha Sharma   34  Engineering   40488           3

#### 2. **Select Rows by Label**
- Using *loc*

1. **Select a Single Row using *loc***

In [5]:
df.loc[1005]

Name          Karan Nair
Age                   28
Department            HR
Salary             35200
Experience             3
Name: 1005, dtype: object

2. **Select Multiple Rows using *loc***

In [6]:
df.loc[[1005,1010]]

              Name  Age Department  Salary  Experience
EmpID
1005    Karan Nair   28         HR   35200           3
1010   Divya Mehta   39         HR   47330           5

3. **Select a Range of Rows using *loc***

In [7]:
df.loc[1015:1020]

                  Name  Age   Department  Salary  Experience
EmpID
1015        Vikram Rao   38  Engineering   62687          12
1016   Vikram Malhotra   27           IT   28834           0
1017       Ananya Bose   26  Engineering   42688           3
1018      Aditya Verma   22           HR   36223           0
1019       Rohan Reddy   40  Engineering   45963           5
1020       Arjun Gupta   54           HR   95841          19

#### 3. **Select First and Last Row**

In [8]:
df.iloc[[0,-1]]

               Name  Age Department  Salary  Experience
EmpID
1001   Sneha Sharma   39      Sales   45401           7
1100     Divya Bose   45         HR   81131          16

#### 4. **Select Specific Rows and Columns**

In [9]:
df.iloc[5:10, 0:4]

               Name  Age  Department  Salary
EmpID
1006    Divya Verma   24     Support   33247
1007   Sanjay Kumar   40  Operations   73268
1008    Rahul Patel   36   Marketing   40369
1009    Sneha Menon   39     Support   55491
1010    Divya Mehta   39          HR   47330

In [10]:
df.iloc[[1,4],[1,4]]

       Age  Experience
EmpID
1002    49           0
1005    28           3

In [11]:
df.loc[[1001,1010], ['Department','Name','Experience']]

      Department          Name  Experience
EmpID
1001       Sales  Sneha Sharma           7
1010          HR   Divya Mehta           5

In [12]:
df.loc[1004:1010, 'Name':'Department']

               Name  Age   Department
EmpID
1004   Arjun Sharma   32  Engineering
1005     Karan Nair   28           HR
1006    Divya Verma   24      Support
1007   Sanjay Kumar   40   Operations
1008    Rahul Patel   36    Marketing
1009    Sneha Menon   39      Support
1010    Divya Mehta   39           HR