### **Filtering in Pandas**

Filtering is the process of selecting only the rows (or sometimes columns) from a DataFrame that satisfy one or more conditions.

In [1]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Employees.csv')

In [2]:
df.columns

Index(['EmpID', 'Name', 'Age', 'Department', 'Salary', 'Experience'], dtype='str')

#### 1. **Filter Rows by a Single Condition**

In [3]:
df[df['Department'] == 'IT']

    EmpID             Name  Age Department  Salary  Experience
1    1002      Sneha Kumar   49         IT   28124           0
15   1016  Vikram Malhotra   27         IT   28834           0
21   1022       Aarav Nair   53         IT   60402           7
31   1032       Meera Bose   51         IT   95814          21
39   1040       Priya Nair   25         IT   41292           3
68   1069     Ananya Desai   47         IT   53275           9
84   1085      Aarav Menon   52         IT  109273          30

#### 2. **Filter with Multiple Conditions**

Important Notes
- Use **&** instead of **and**.
- Use **|** instead of **or**.

##### **AND (&)**

Employees older than 28 and salary above 55000:

In [4]:
df[(df['Age'] > 28) & (df['Salary'] > 55000) ]

    EmpID            Name  Age   Department  Salary  Experience
6    1007    Sanjay Kumar   40   Operations   73268          18
8    1009     Sneha Menon   39      Support   55491          11
10   1011      Neha Gupta   51  Engineering   64790           8
13   1014     Rohan Mehta   53  Engineering   98107          29
14   1015      Vikram Rao   38  Engineering   62687          12
19   1020     Arjun Gupta   54           HR   95841          19
20   1021     Karan Singh   45      Finance   92901          17
21   1022      Aarav Nair   53           IT   60402           7
23   1024   Lakshmi Kumar   30      Finance   60740           7
24   1025    Ananya Verma   55  Engineering   79472          13
25   1026     Karan Desai   47   Operations   81889          14
29   1030     Karan Singh   52        Sales  100749          25
31   1032      Meera Bose   51           IT   95814          21
32   1033     Sneha Patel   47   Operations  115131          25
34   1035    Arjun Chopra   37           HR   79508          14
37   1038     Aarav Menon   38      Support   56133           9
41   1042       Rahul Rao   47           HR   74886          18
49   1050     Karan Verma   54      Support   88349          16
51   1052    Vikram Verma   32      Support   59113           8
56   1057     Aarav Gupta   43  Engineering  102764          21
57   1058      Neha Verma   32           HR   56199           6
60   1061     Rahul Verma   44  Engineering  106627          21
63   1064      Rohan Bose   54           HR  113382          24
65   1066      Karan Iyer   49           HR  104635          21
66   1067     Rohan Reddy   41    Marketing   64404          13
67   1068     Pooja Singh   34  Engineering   70188          10
69   1070      Meera Nair   51      Support   76066          14
71   1072     Rohan Kumar   37    Marketing   58074           7
73   1074    Rahul Chopra   48        Sales  100176          22
75   1076      Sneha Bose   36      Finance   76991          12
76   1077    Aditya Patel   37           HR   61966          14
77   1078     Aditya Nair   50  Engineering  119960          26
78   1079    Aditya Gupta   52      Support   60035           8
79   1080  Arjun Malhotra   37    Marketing   60514          14
80   1081       Pooja Rao   39   Operations   69146          10
82   1083     Karan Kumar   48  Engineering   61437          10
83   1084     Meera Patel   35  Engineering   56787           6
84   1085     Aarav Menon   52           IT  109273          30
86   1087  Lakshmi Sharma   46   Operations   96661          21
87   1088    Sanjay Gupta   51      Finance   86307          19
90   1091      Rohan Nair   46    Marketing  115243          24
92   1093      Priya Iyer   36           HR   76974          12
94   1095      Neha Singh   52           HR   95932          18
95   1096    Aditya Verma   45      Finance   88574          19
96   1097     Sneha Gupta   41           HR   68270          18
98   1099      Neha Reddy   41           HR   90979          18
99   1100      Divya Bose   45           HR   81131          16

##### **OR (|)**

Employees younger than 26 or salary above 65000:

In [5]:
df[(df['Age'] > 26) | (df['Salary'] > 65000)]

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[86 rows x 6 columns]

#### 3. **Filter Using *isin()***

In [6]:
dep = ['IT', 'Operations']
df[df['Department'].isin(dep)]

    EmpID             Name  Age  Department  Salary  Experience
1    1002      Sneha Kumar   49          IT   28124           0
6    1007     Sanjay Kumar   40  Operations   73268          18
15   1016  Vikram Malhotra   27          IT   28834           0
21   1022       Aarav Nair   53          IT   60402           7
25   1026      Karan Desai   47  Operations   81889          14
31   1032       Meera Bose   51          IT   95814          21
32   1033      Sneha Patel   47  Operations  115131          25
39   1040       Priya Nair   25          IT   41292           3
42   1043      Priya Kumar   48  Operations   49085           8
68   1069     Ananya Desai   47          IT   53275           9
80   1081        Pooja Rao   39  Operations   69146          10
84   1085      Aarav Menon   52          IT  109273          30
86   1087   Lakshmi Sharma   46  Operations   96661          21

#### 4. **Filter Missing Values**

In [7]:
print(df[df['Experience'].isna()]) # Missing Values
print()
df[df['Experience'].notna()]

Empty DataFrame
Columns: [EmpID, Name, Age, Department, Salary, Experience]
Index: []

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]

#### 5. **Filter with String Conditions**

Names starting with "A":

In [8]:
df[df['Name'].str.startswith('A')]

    EmpID            Name  Age   Department  Salary  Experience
3    1004    Arjun Sharma   32  Engineering   42973           5
16   1017     Ananya Bose   26  Engineering   42688           3
17   1018    Aditya Verma   22           HR   36223           0
19   1020     Arjun Gupta   54           HR   95841          19
21   1022      Aarav Nair   53           IT   60402           7
24   1025    Ananya Verma   55  Engineering   79472          13
26   1027    Aditya Reddy   37        Sales   36233           2
34   1035    Arjun Chopra   37           HR   79508          14
37   1038     Aarav Menon   38      Support   56133           9
40   1041    Ananya Patel   54           HR   53325          11
52   1053     Aarav Reddy   26      Finance   36576           4
56   1057     Aarav Gupta   43  Engineering  102764          21
62   1063     Arjun Patel   28  Engineering   41699           2
68   1069    Ananya Desai   47           IT   53275           9
76   1077    Aditya Patel   37           HR   61966          14
77   1078     Aditya Nair   50  Engineering  119960          26
78   1079    Aditya Gupta   52      Support   60035           8
79   1080  Arjun Malhotra   37    Marketing   60514          14
84   1085     Aarav Menon   52           IT  109273          30
89   1090    Ananya Patel   38  Engineering   54156          10
95   1096    Aditya Verma   45      Finance   88574          19

Names containing "a":

In [9]:
df[df['Name'].str.contains('t', case='False')]

    EmpID              Name  Age   Department  Salary  Experience
7    1008       Rahul Patel   36    Marketing   40369           1
9    1010       Divya Mehta   39           HR   47330           5
10   1011        Neha Gupta   51  Engineering   64790           8
13   1014       Rohan Mehta   53  Engineering   98107          29
15   1016   Vikram Malhotra   27           IT   28834           0
17   1018      Aditya Verma   22           HR   36223           0
19   1020       Arjun Gupta   54           HR   95841          19
26   1027      Aditya Reddy   37        Sales   36233           2
30   1031       Meera Mehta   28           HR   45577           5
32   1033       Sneha Patel   47   Operations  115131          25
33   1034        Neha Mehta   34      Support   37406           2
35   1036       Sneha Patel   22           HR   28995           0
36   1037  Lakshmi Malhotra   35  Engineering   28975           0
40   1041      Ananya Patel   54           HR   53325          11
56   1057       Aarav Gupta   43  Engineering  102764          21
62   1063       Arjun Patel   28  Engineering   41699           2
70   1071     Lakshmi Gupta   27    Marketing   46621           4
76   1077      Aditya Patel   37           HR   61966          14
77   1078       Aditya Nair   50  Engineering  119960          26
78   1079      Aditya Gupta   52      Support   60035           8
79   1080    Arjun Malhotra   37    Marketing   60514          14
83   1084       Meera Patel   35  Engineering   56787           6
87   1088      Sanjay Gupta   51      Finance   86307          19
89   1090      Ananya Patel   38  Engineering   54156          10
95   1096      Aditya Verma   45      Finance   88574          19
96   1097       Sneha Gupta   41           HR   68270          18

#### 6. **Using query()**

This is often cleaner for complex conditions.

In [10]:
df.query('Age > 30 and Department == "IT"')

    EmpID          Name  Age Department  Salary  Experience
1    1002   Sneha Kumar   49         IT   28124           0
21   1022    Aarav Nair   53         IT   60402           7
31   1032    Meera Bose   51         IT   95814          21
68   1069  Ananya Desai   47         IT   53275           9
84   1085   Aarav Menon   52         IT  109273          30

#### 7. **Filter Columns**

Select specific columns:

In [11]:
df[['Name', 'Salary']]

            Name  Salary
0   Sneha Sharma   45401
1    Sneha Kumar   28124
2    Neha Sharma   40488
3   Arjun Sharma   42973
4     Karan Nair   35200
..           ...     ...
95  Aditya Verma   88574
96   Sneha Gupta   68270
97   Pooja Menon   39789
98    Neha Reddy   90979
99    Divya Bose   81131

[100 rows x 2 columns]

#### 8. **Using loc[]**

loc[] filters rows and can also select columns at the same time.

In [12]:
df.loc[df['Age'] > 50, ['Name', 'Age', 'Salary']]

            Name  Age  Salary
10    Neha Gupta   51   64790
13   Rohan Mehta   53   98107
19   Arjun Gupta   54   95841
21    Aarav Nair   53   60402
24  Ananya Verma   55   79472
29   Karan Singh   52  100749
31    Meera Bose   51   95814
40  Ananya Patel   54   53325
49   Karan Verma   54   88349
63    Rohan Bose   54  113382
69    Meera Nair   51   76066
78  Aditya Gupta   52   60035
84   Aarav Menon   52  109273
87  Sanjay Gupta   51   86307
94    Neha Singh   52   95932

#### 9. **Between()**

In [13]:
df[df['Age'].between(25,30)]

    EmpID             Name  Age   Department  Salary  Experience
4    1005       Karan Nair   28           HR   35200           3
11   1012        Neha Nair   25        Sales   36660           0
12   1013     Sanjay Verma   26        Sales   50021           4
15   1016  Vikram Malhotra   27           IT   28834           0
16   1017      Ananya Bose   26  Engineering   42688           3
22   1023        Pooja Rao   25        Sales   28027           0
23   1024    Lakshmi Kumar   30      Finance   60740           7
28   1029       Priya Nair   26        Sales   40865           2
30   1031      Meera Mehta   28           HR   45577           5
39   1040       Priya Nair   25           IT   41292           3
52   1053      Aarav Reddy   26      Finance   36576           4
61   1062     Rohan Sharma   29    Marketing   39628           2
62   1063      Arjun Patel   28  Engineering   41699           2
70   1071    Lakshmi Gupta   27    Marketing   46621           4
88   1089    Sanjay Sharma   27  Engineering   40519           1
91   1092      Meera Verma   27      Support   35988           0

#### 10. **where()**

Keeps values where condition is True.

False values become NaN.

In [14]:
df.where(df['Department'] == 'HR')

     EmpID         Name   Age Department   Salary  Experience
0      NaN          NaN   NaN        NaN      NaN         NaN
1      NaN          NaN   NaN        NaN      NaN         NaN
2      NaN          NaN   NaN        NaN      NaN         NaN
3      NaN          NaN   NaN        NaN      NaN         NaN
4   1005.0   Karan Nair  28.0         HR  35200.0         3.0
..     ...          ...   ...        ...      ...         ...
95     NaN          NaN   NaN        NaN      NaN         NaN
96  1097.0  Sneha Gupta  41.0         HR  68270.0        18.0
97     NaN          NaN   NaN        NaN      NaN         NaN
98  1099.0   Neha Reddy  41.0         HR  90979.0        18.0
99  1100.0   Divya Bose  45.0         HR  81131.0        16.0

[100 rows x 6 columns]

**Replace False values**

In [15]:
df.where(df['Department'] == 'HR', 'N/A')

   EmpID         Name  Age Department Salary Experience
0    N/A          N/A  N/A        N/A    N/A        N/A
1    N/A          N/A  N/A        N/A    N/A        N/A
2    N/A          N/A  N/A        N/A    N/A        N/A
3    N/A          N/A  N/A        N/A    N/A        N/A
4   1005   Karan Nair   28         HR  35200          3
..   ...          ...  ...        ...    ...        ...
95   N/A          N/A  N/A        N/A    N/A        N/A
96  1097  Sneha Gupta   41         HR  68270         18
97   N/A          N/A  N/A        N/A    N/A        N/A
98  1099   Neha Reddy   41         HR  90979         18
99  1100   Divya Bose   45         HR  81131         16

[100 rows x 6 columns]

#### 11. **mask()**

Opposite of where().

Condition True → replaced.

Condition False → kept.

In [16]:
df.mask(df['Department'] == 'HR')

     EmpID          Name   Age   Department   Salary  Experience
0   1001.0  Sneha Sharma  39.0        Sales  45401.0         7.0
1   1002.0   Sneha Kumar  49.0           IT  28124.0         0.0
2   1003.0   Neha Sharma  34.0  Engineering  40488.0         3.0
3   1004.0  Arjun Sharma  32.0  Engineering  42973.0         5.0
4      NaN           NaN   NaN          NaN      NaN         NaN
..     ...           ...   ...          ...      ...         ...
95  1096.0  Aditya Verma  45.0      Finance  88574.0        19.0
96     NaN           NaN   NaN          NaN      NaN         NaN
97  1098.0   Pooja Menon  47.0        Sales  39789.0         2.0
98     NaN           NaN   NaN          NaN      NaN         NaN
99     NaN           NaN   NaN          NaN      NaN         NaN

[100 rows x 6 columns]

**Replace**

In [17]:
df.mask(df['Department'] == 'HR', 'N/A')

   EmpID          Name  Age   Department Salary Experience
0   1001  Sneha Sharma   39        Sales  45401          7
1   1002   Sneha Kumar   49           IT  28124          0
2   1003   Neha Sharma   34  Engineering  40488          3
3   1004  Arjun Sharma   32  Engineering  42973          5
4    N/A           N/A  N/A          N/A    N/A        N/A
..   ...           ...  ...          ...    ...        ...
95  1096  Aditya Verma   45      Finance  88574         19
96   N/A           N/A  N/A          N/A    N/A        N/A
97  1098   Pooja Menon   47        Sales  39789          2
98   N/A           N/A  N/A          N/A    N/A        N/A
99   N/A           N/A  N/A          N/A    N/A        N/A

[100 rows x 6 columns]