### **Sorting in Pandas**

Sorting means arranging data in a specific order.

There are two types of sorting:

1. **Sort Rows (sort_values())**
2. **Sort Index (sort_index())**

Let's learn them one by one.

In [9]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Employees.csv')

#### 1. **sort_values()**

Used to sort rows based on column values.

**Syntax:**

```python
df.sort_values(by="column_name")
```

##### **Sort by one column (Ascending)**

Ascending is the default.

In [10]:
df.sort_values(by='Age')

    EmpID          Name  Age   Department  Salary  Experience
27   1028      Neha Rao   22           HR   29747           0
17   1018  Aditya Verma   22           HR   36223           0
35   1036   Sneha Patel   22           HR   28995           0
59   1060      Neha Rao   23        Sales   33517           1
5    1006   Divya Verma   24      Support   33247           2
..    ...           ...  ...          ...     ...         ...
19   1020   Arjun Gupta   54           HR   95841          19
40   1041  Ananya Patel   54           HR   53325          11
63   1064    Rohan Bose   54           HR  113382          24
49   1050   Karan Verma   54      Support   88349          16
24   1025  Ananya Verma   55  Engineering   79472          13

[100 rows x 6 columns]

##### **Sort by (Descending)**

In [11]:
df.sort_values(by='Age', ascending=False)

    EmpID          Name  Age   Department  Salary  Experience
24   1025  Ananya Verma   55  Engineering   79472          13
19   1020   Arjun Gupta   54           HR   95841          19
49   1050   Karan Verma   54      Support   88349          16
40   1041  Ananya Patel   54           HR   53325          11
63   1064    Rohan Bose   54           HR  113382          24
..    ...           ...  ...          ...     ...         ...
5    1006   Divya Verma   24      Support   33247           2
59   1060      Neha Rao   23        Sales   33517           1
35   1036   Sneha Patel   22           HR   28995           0
17   1018  Aditya Verma   22           HR   36223           0
27   1028      Neha Rao   22           HR   29747           0

[100 rows x 6 columns]

##### **Sort by Multiple Columns**

Suppose two people have the same age.

Sort by Age first and then Salary.

Explanation

- First sort by Age.
- If Age is the same, sort by Salary.

In [12]:
df.sort_values(by=['Age', 'Salary'])

    EmpID          Name  Age   Department  Salary  Experience
35   1036   Sneha Patel   22           HR   28995           0
27   1028      Neha Rao   22           HR   29747           0
17   1018  Aditya Verma   22           HR   36223           0
59   1060      Neha Rao   23        Sales   33517           1
64   1065   Karan Verma   24  Engineering   33239           0
..    ...           ...  ...          ...     ...         ...
40   1041  Ananya Patel   54           HR   53325          11
49   1050   Karan Verma   54      Support   88349          16
19   1020   Arjun Gupta   54           HR   95841          19
63   1064    Rohan Bose   54           HR  113382          24
24   1025  Ananya Verma   55  Engineering   79472          13

[100 rows x 6 columns]

##### **Different Order for Different Columns**

Meaning

- Age → Ascending
- Salary → Descending

In [13]:
df.sort_values(by=['Age', 'Salary'], ascending=[True, False])

    EmpID           Name  Age   Department  Salary  Experience
17   1018   Aditya Verma   22           HR   36223           0
27   1028       Neha Rao   22           HR   29747           0
35   1036    Sneha Patel   22           HR   28995           0
59   1060       Neha Rao   23        Sales   33517           1
72   1073  Vikram Sharma   24        Sales   37196           1
..    ...            ...  ...          ...     ...         ...
63   1064     Rohan Bose   54           HR  113382          24
19   1020    Arjun Gupta   54           HR   95841          19
49   1050    Karan Verma   54      Support   88349          16
40   1041   Ananya Patel   54           HR   53325          11
24   1025   Ananya Verma   55  Engineering   79472          13

[100 rows x 6 columns]

In [14]:
df2 = pd.read_csv(r'sample_datasets\Employees.csv', na_values=['Engineering'])
df2

    EmpID          Name  Age Department  Salary  Experience
0    1001  Sneha Sharma   39      Sales   45401           7
1    1002   Sneha Kumar   49         IT   28124           0
2    1003   Neha Sharma   34        NaN   40488           3
3    1004  Arjun Sharma   32        NaN   42973           5
4    1005    Karan Nair   28         HR   35200           3
..    ...           ...  ...        ...     ...         ...
95   1096  Aditya Verma   45    Finance   88574          19
96   1097   Sneha Gupta   41         HR   68270          18
97   1098   Pooja Menon   47      Sales   39789           2
98   1099    Neha Reddy   41         HR   90979          18
99   1100    Divya Bose   45         HR   81131          16

[100 rows x 6 columns]

##### **Handling Missing Values**

By Default:
- Missing values appear at the end.

In [15]:
df2.sort_values(by='Department')

    EmpID           Name  Age Department  Salary  Experience
20   1021    Karan Singh   45    Finance   92901          17
23   1024  Lakshmi Kumar   30    Finance   60740           7
52   1053    Aarav Reddy   26    Finance   36576           4
53   1054    Divya Singh   49    Finance   33257           1
55   1056    Meera Singh   37    Finance   53234           5
..    ...            ...  ...        ...     ...         ...
77   1078    Aditya Nair   50        NaN  119960          26
82   1083    Karan Kumar   48        NaN   61437          10
83   1084    Meera Patel   35        NaN   56787           6
88   1089  Sanjay Sharma   27        NaN   40519           1
89   1090   Ananya Patel   38        NaN   54156          10

[100 rows x 6 columns]

Move missing values first

In [16]:
df2.sort_values(by='Department', na_position='first')

    EmpID          Name  Age Department  Salary  Experience
2    1003   Neha Sharma   34        NaN   40488           3
3    1004  Arjun Sharma   32        NaN   42973           5
10   1011    Neha Gupta   51        NaN   64790           8
13   1014   Rohan Mehta   53        NaN   98107          29
14   1015    Vikram Rao   38        NaN   62687          12
..    ...           ...  ...        ...     ...         ...
58   1059   Lakshmi Rao   34    Support   43438           5
69   1070    Meera Nair   51    Support   76066          14
78   1079  Aditya Gupta   52    Support   60035           8
85   1086   Sanjay Bose   36    Support   37844           3
91   1092   Meera Verma   27    Support   35988           0

[100 rows x 6 columns]

##### **Ignore Old Index**

It creates a new index (0, 1, 2, ...) after sorting.

**Without *ignore_index=True***

In [17]:
df.sort_values(by='Age').head()

    EmpID          Name  Age Department  Salary  Experience
27   1028      Neha Rao   22         HR   29747           0
17   1018  Aditya Verma   22         HR   36223           0
35   1036   Sneha Patel   22         HR   28995           0
59   1060      Neha Rao   23      Sales   33517           1
5    1006   Divya Verma   24    Support   33247           2

**With *ignore_index=True***

In [18]:
df.sort_values(by='Age', ignore_index=True).head()

   EmpID          Name  Age Department  Salary  Experience
0   1028      Neha Rao   22         HR   29747           0
1   1018  Aditya Verma   22         HR   36223           0
2   1036   Sneha Patel   22         HR   28995           0
3   1060      Neha Rao   23      Sales   33517           1
4   1006   Divya Verma   24    Support   33247           2

##### **In-place Sorting**

It changes the original DataFrame.

**Without *inplace=True***

- Shows the sorted result.
- df is NOT changed.

In [19]:
df.sort_values(by='Age') # # Original DataFrame remains unchanged.
df

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]

**With *inplace=True***
- Sorts the data.
- df is permanently changed.

In [20]:
df.sort_values(by='Age', inplace=False) # Now df is permanently sorted.
df

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]

##### **Case-sensitive Sorting**

Uppercase letters come before lowercase because sorting is based on Unicode values.

In [21]:
df3 = pd.DataFrame({
    "Name":["john","Alice","bob","David"]
})
df3.sort_values(by='Name')

    Name
1  Alice
3  David
2    bob
0   john

To sort without considering case:

In [22]:
df3.sort_values(by='Name', key=lambda col: col.str.lower())

    Name
1  Alice
2    bob
3  David
0   john

##### **Custom Sorting Using *key***

Example: Sort names by their length.

In [23]:
df.sort_values(by='Name', key=lambda col : col.str.len())

    EmpID              Name  Age   Department  Salary  Experience
27   1028          Neha Rao   22           HR   29747           0
59   1060          Neha Rao   23        Sales   33517           1
22   1023         Pooja Rao   25        Sales   28027           0
11   1012         Neha Nair   25        Sales   36660           0
46   1047         Rahul Rao   45    Marketing   45699           5
..    ...               ...  ...          ...     ...         ...
70   1071     Lakshmi Gupta   27    Marketing   46621           4
86   1087    Lakshmi Sharma   46   Operations   96661          21
79   1080    Arjun Malhotra   37    Marketing   60514          14
15   1016   Vikram Malhotra   27           IT   28834           0
36   1037  Lakshmi Malhotra   35  Engineering   28975           0

[100 rows x 6 columns]

#### 2. **sort_index()**

Sorts rows or columns by their index labels, not by the data.

##### **Sort Row Index**

In [24]:
df.sort_index(ascending=False)

    EmpID          Name  Age   Department  Salary  Experience
99   1100    Divya Bose   45           HR   81131          16
98   1099    Neha Reddy   41           HR   90979          18
97   1098   Pooja Menon   47        Sales   39789           2
96   1097   Sneha Gupta   41           HR   68270          18
95   1096  Aditya Verma   45      Finance   88574          19
..    ...           ...  ...          ...     ...         ...
4    1005    Karan Nair   28           HR   35200           3
3    1004  Arjun Sharma   32  Engineering   42973           5
2    1003   Neha Sharma   34  Engineering   40488           3
1    1002   Sneha Kumar   49           IT   28124           0
0    1001  Sneha Sharma   39        Sales   45401           7

[100 rows x 6 columns]

##### **Sort Column Names**

axis=1 means sort column labels.

In [25]:
df.sort_index(axis=1)

    Age   Department  EmpID  Experience          Name  Salary
0    39        Sales   1001           7  Sneha Sharma   45401
1    49           IT   1002           0   Sneha Kumar   28124
2    34  Engineering   1003           3   Neha Sharma   40488
3    32  Engineering   1004           5  Arjun Sharma   42973
4    28           HR   1005           3    Karan Nair   35200
..  ...          ...    ...         ...           ...     ...
95   45      Finance   1096          19  Aditya Verma   88574
96   41           HR   1097          18   Sneha Gupta   68270
97   47        Sales   1098           2   Pooja Menon   39789
98   41           HR   1099          18    Neha Reddy   90979
99   45           HR   1100          16    Divya Bose   81131

[100 rows x 6 columns]

#### **Important Parameters**

##### *sort_values()*

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
</tr>
<tr>
<td><i>by</i></td>
<td>Column(s) to sort by</td>
</tr>
<tr>
<td><i>ascending</i></td>
<td>True or False</td>
</tr>
<tr>
<td><i>ignore_index</i></td>
<td>Reset index after sorting</td>
</tr>
<tr>
<td><i>inplace</i></td>
<td>Modify original DataFrame</td>
</tr>
<tr>
<td><i>na_position</i></td>
<td>"first" or "last"</td>
</tr>
<tr>
<td><i>key</i></td>
<td>Apply a function before sorting</td>
</tr>
</table>

##### *sort_index()*

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
</tr>
<tr>
<td><i>axis</i></td>
<td>0 = rows, 1 = columns</td>
</tr>
<tr>
<td><i>ascending</i></td>
<td>Sort ascending/descending</td>
</tr>
<tr>
<td><i>ignore_index</i></td>
<td>Reset index</td>
</tr>
<tr>
<td><i>inplace</i></td>
<td>Modify original DataFrame</td>
</tr>
</table>