### **Add & Delete Columns in Pandas**

#### 1. **ADDING COLUMNS**

There are many ways to add columns.

In [1]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Employees.csv')

##### 1. **Add a Column with a Single Value**

Every row gets the same value.

In [2]:
df['Country'] = 'India'
df.head()

   EmpID          Name  Age   Department  Salary  Experience Country
0   1001  Sneha Sharma   39        Sales   45401           7   India
1   1002   Sneha Kumar   49           IT   28124           0   India
2   1003   Neha Sharma   34  Engineering   40488           3   India
3   1004  Arjun Sharma   32  Engineering   42973           5   India
4   1005    Karan Nair   28           HR   35200           3   India

##### 2. **Add a Column Using Another Column**

In [3]:
df['Bonus'] = df['Salary'] * 0.10
df.head()

   EmpID          Name  Age   Department  Salary  Experience Country   Bonus
0   1001  Sneha Sharma   39        Sales   45401           7   India  4540.1
1   1002   Sneha Kumar   49           IT   28124           0   India  2812.4
2   1003   Neha Sharma   34  Engineering   40488           3   India  4048.8
3   1004  Arjun Sharma   32  Engineering   42973           5   India  4297.3
4   1005    Karan Nair   28           HR   35200           3   India  3520.0

##### 3. **Add Multiple Columns**

In [4]:
df['Tax'] = df['Salary'] * 0.05
df['Net Salary'] = df['Salary'] - df['Tax']
df.head()

,EmpID,Name,Age,Department,Salary,Experience,Country,Bonus,Tax,Net Salary
0,1001,Sneha Sharma,39,Sales,45401,7,India,4540.1,2270.05,43130.95
1,1002,Sneha Kumar,49,IT,28124,0,India,2812.4,1406.20,26717.80
2,1003,Neha Sharma,34,Engineering,40488,3,India,4048.8,2024.40,38463.60
3,1004,Arjun Sharma,32,Engineering,42973,5,India,4297.3,2148.65,40824.35
4,1005,Karan Nair,28,HR,35200,3,India,3520.0,1760.00,33440.00

##### 4. **Add an Empty Column**

In [5]:
df['Email'] = None
df.head()

,EmpID,Name,Age,Department,Salary,Experience,Country,Bonus,Tax,Net Salary,Email
0,1001,Sneha Sharma,39,Sales,45401,7,India,4540.1,2270.05,43130.95,None
1,1002,Sneha Kumar,49,IT,28124,0,India,2812.4,1406.20,26717.80,None
2,1003,Neha Sharma,34,Engineering,40488,3,India,4048.8,2024.40,38463.60,None
3,1004,Arjun Sharma,32,Engineering,42973,5,India,4297.3,2148.65,40824.35,None
4,1005,Karan Nair,28,HR,35200,3,India,3520.0,1760.00,33440.00,None

##### 5. **Renaming a Column**

In [6]:
df.rename(columns={'Net Salary':'net_salary', 'Email':'email'}, inplace=True)
df.head()

,EmpID,Name,Age,Department,Salary,Experience,Country,Bonus,Tax,net_salary,email
0,1001,Sneha Sharma,39,Sales,45401,7,India,4540.1,2270.05,43130.95,None
1,1002,Sneha Kumar,49,IT,28124,0,India,2812.4,1406.20,26717.80,None
2,1003,Neha Sharma,34,Engineering,40488,3,India,4048.8,2024.40,38463.60,None
3,1004,Arjun Sharma,32,Engineering,42973,5,India,4297.3,2148.65,40824.35,None
4,1005,Karan Nair,28,HR,35200,3,India,3520.0,1760.00,33440.00,None

Renaming all columns:

In [7]:
df.columns = [
    'emp_id',
    'name',
    'age',
    'department',
    'salary',
    'experience',
    'country',
    'bonus',
    'tax',
    'net_salary',
    'email'
]
df.columns

Index(['emp_id', 'name', 'age', 'department', 'salary', 'experience',
       'country', 'bonus', 'tax', 'net_salary', 'email'],
      dtype='str')

Creating a sample dataframe for exploring more options:

In [8]:
emp = pd.DataFrame({
    "emp_id": [101, 102, 103, 104],
    "name": ["Rahul", "Anita", "John", "Priya"],
    "salary": [35000, 42000, 50000, 38000],
    "department": ["HR", "IT", "Finance", "IT"]
})
emp

   emp_id   name  salary department
0     101  Rahul   35000         HR
1     102  Anita   42000         IT
2     103   John   50000    Finance
3     104  Priya   38000         IT

##### 6. **Add a Column from a List**

The list length must equal the number of rows.

If lengths don't match:

**Output:**

*ValueError:Length of values does not match length of index*

In [9]:
emp["age"] = [25, 30, 28, 26]
emp

   emp_id   name  salary department  age
0     101  Rahul   35000         HR   25
1     102  Anita   42000         IT   30
2     103   John   50000    Finance   28
3     104  Priya   38000         IT   26

##### 7. **Insert a Column at a Specific Position**

Normally,

```python
emp["city"] = "Hyderabad"
```
adds the column at the end.


If you want a specific position, use insert().

**Syntax:**

```python
df.insert(position, column_name, values)
```

In [10]:
emp.insert(2, 'gender', ['M', 'F', 'M', 'F'])
emp

   emp_id   name gender  salary department  age
0     101  Rahul      M   35000         HR   25
1     102  Anita      F   42000         IT   30
2     103   John      M   50000    Finance   28
3     104  Priya      F   38000         IT   26

#### 2. **DELETING COLUMNS**

Several methods are available.

##### 1. ***drop()***

Most commonly used.

**Syntax:**

```python
df.drop(columns=["column_name"])
```

In [11]:
new_df = df.drop(columns=['email'])
print(new_df.head())
print(df.head())    # Original DataFrame remains unchanged.

   emp_id          name  age   department  salary  experience country   bonus  \
0    1001  Sneha Sharma   39        Sales   45401           7   India  4540.1
1    1002   Sneha Kumar   49           IT   28124           0   India  2812.4
2    1003   Neha Sharma   34  Engineering   40488           3   India  4048.8
3    1004  Arjun Sharma   32  Engineering   42973           5   India  4297.3
4    1005    Karan Nair   28           HR   35200           3   India  3520.0

       tax  net_salary
0  2270.05    43130.95
1  1406.20    26717.80
2  2024.40    38463.60
3  2148.65    40824.35
4  1760.00    33440.00
   emp_id          name  age   department  salary  experience country   bonus  \
0    1001  Sneha Sharma   39        Sales   45401           7   India  4540.1
1    1002   Sneha Kumar   49           IT   28124           0   India  2812.4
2    1003   Neha Sharma   34  Engineering   40488           3   India  4048.8
3    1004  Arjun Sharma   32  Engineering   42973           5   India  4297.3
4    1005    Karan Nair   28           HR   35200           3   India  3520.0

       tax  net_salary email
0  2270.05    43130.95  None
1  1406.20    26717.80  None
2  2024.40    38463.60  None
3  2148.65    40824.35  None
4  1760.00    33440.00  None

Using *inplace=True*

In [12]:
df.drop(columns=['email'], inplace=True)
df.head()   # Original DataFrame is modified.

,emp_id,name,age,department,salary,experience,country,bonus,tax,net_salary
0,1001,Sneha Sharma,39,Sales,45401,7,India,4540.1,2270.05,43130.95
1,1002,Sneha Kumar,49,IT,28124,0,India,2812.4,1406.20,26717.80
2,1003,Neha Sharma,34,Engineering,40488,3,India,4048.8,2024.40,38463.60
3,1004,Arjun Sharma,32,Engineering,42973,5,India,4297.3,2148.65,40824.35
4,1005,Karan Nair,28,HR,35200,3,India,3520.0,1760.00,33440.00

##### **Delete Multiple Columns**

In [13]:
df.drop(columns=['net_salary', 'tax'], inplace=True)
df.head()

   emp_id          name  age   department  salary  experience country   bonus
0    1001  Sneha Sharma   39        Sales   45401           7   India  4540.1
1    1002   Sneha Kumar   49           IT   28124           0   India  2812.4
2    1003   Neha Sharma   34  Engineering   40488           3   India  4048.8
3    1004  Arjun Sharma   32  Engineering   42973           5   India  4297.3
4    1005    Karan Nair   28           HR   35200           3   India  3520.0

##### 2. ***del***

Deletes the column permanently.(can only delete one column at a time)

In [14]:
del df['bonus']
df.head()

   emp_id          name  age   department  salary  experience country
0    1001  Sneha Sharma   39        Sales   45401           7   India
1    1002   Sneha Kumar   49           IT   28124           0   India
2    1003   Neha Sharma   34  Engineering   40488           3   India
3    1004  Arjun Sharma   32  Engineering   42973           5   India
4    1005    Karan Nair   28           HR   35200           3   India

##### 3. ***pop()***

Removes the column and returns it.

In [15]:
country = df.pop('country')
print(country.head()) # The country column is removed from df.
df.head()

0    India
1    India
2    India
3    India
4    India
Name: country, dtype: str

   emp_id          name  age   department  salary  experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3

#### **Difference Between *drop(), del,* and *pop()***

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Method</th>
<th>Original DataFrame Changed?</th>
<th>Returns Deleted Column?</th>
<th>Can Delete Multiple Columns?</th>
</tr>
<tr>
<td><i>drop()</i></td>
<td>No (unless inplace=True)</td>
<td>No</td>
<td>Yes</td>
</tr>
<tr>
<td><i>del</i></td>
<td>Yes</td>
<td>No</td>
<td>No</td>
</tr>
<tr>
<td><i>pop()</i></td>
<td>Yes</td>
<td>Yes</td>
<td>No</td>
</tr>
</table>

#### 3. **Checking Whether a Column Exists**

In [16]:
'name' in df.columns

True

In [17]:
'city' in df.columns

False

##### **Common Errors**

1. List length doesn't match rows

```python
emp["age"] = [25, 30]
```

❌ Error because there are 4 rows.

2. Dropping a non-existing column

```python
emp.drop(columns=["city"])
```

❌ Raises a KeyError.


To avoid the error:

```python
emp.drop(columns=["city"], errors="ignore")
```

#### 4. **Other Modifications**
##### 1. ***assign()***

*assign()* returns a new DataFrame with added or updated columns. It does not modify the original DataFrame unless you assign the result back.

**Syntax:**

```python
df.assign(column_name=value)
```

In [18]:
new_df = df.assign(
    bonus = 5000,
    new_salary = df['salary'] + 5000
)
new_df

,emp_id,name,age,department,salary,experience,bonus,new_salary
0,1001,Sneha Sharma,39,Sales,45401,7,5000,50401
1,1002,Sneha Kumar,49,IT,28124,0,5000,33124
2,1003,Neha Sharma,34,Engineering,40488,3,5000,45488
3,1004,Arjun Sharma,32,Engineering,42973,5,5000,47973
4,1005,Karan Nair,28,HR,35200,3,5000,40200
...,...,...,...,...,...,...,...,...
95,1096,Aditya Verma,45,Finance,88574,19,5000,93574
96,1097,Sneha Gupta,41,HR,68270,18,5000,73270
97,1098,Pooja Menon,47,Sales,39789,2,5000,44789
98,1099,Neha Reddy,41,HR,90979,18,5000,95979
99,1100,Divya Bose,45,HR,81131,16,5000,86131

##### 2. ***astype()***

*astype()* changes the data type of one or more columns.

In [19]:
df.dtypes

emp_id        int64
name            str
age           int64
department      str
salary        int64
experience    int64
dtype: object

**Convert integer to  string**

In [20]:
df['age'] = df['age'].astype(str)
df.dtypes

emp_id        int64
name            str
age             str
department      str
salary        int64
experience    int64
dtype: object

**Convert multiple columns**

In [21]:
df[['salary', 'experience', 'age']] = df[['salary', 'experience', 'age']].astype({
    'salary': 'float',
    'experience': 'float',
    'age': int
}
)

print(df.head())
df.dtypes

   emp_id          name  age   department   salary  experience
0    1001  Sneha Sharma   39        Sales  45401.0         7.0
1    1002   Sneha Kumar   49           IT  28124.0         0.0
2    1003   Neha Sharma   34  Engineering  40488.0         3.0
3    1004  Arjun Sharma   32  Engineering  42973.0         5.0
4    1005    Karan Nair   28           HR  35200.0         3.0

emp_id          int64
name              str
age             int64
department        str
salary        float64
experience    float64
dtype: object