### **Missing Values in Pandas**

Missing values are values that are not available or unknown in a dataset.

In Pandas, missing values are usually represented as:

- NaN (Not a Number) – for numeric data
- None – for object/string data (often treated as missing)
- pd.NA – the newer missing value marker used by Pandas

In [1]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Employees_with_Nan.csv')
df

    EmpID           Name   Age Department    Salary  Experience
0    1001   Aarav Sharma  22.0        NaN   35000.0         NaN
1    1002    Rohan Reddy  23.0         HR   36200.0         1.0
2    1003   Vikram Patel  24.0    Finance   37400.0         2.0
3    1004    Kiran Kumar  25.0      Sales   38600.0         3.0
4    1005    Rahul Verma  26.0  Marketing   39800.0         4.0
..    ...            ...   ...        ...       ...         ...
95   1096     Venu Gopal  37.0         IT  149000.0         5.0
96   1097   Ajay Krishna  38.0         HR  150200.0         6.0
97   1098   Pavan Kalyan  39.0    Finance  151400.0         7.0
98   1099  Karthik Reddy   NaN      Sales  152600.0         8.0
99   1100     Lokesh Rao  41.0  Marketing  153800.0         9.0

[100 rows x 6 columns]

#### 1. **Check for Missing Values**

***isna()*** or ***isnull()***

Returns *True* where a value is missing

In [2]:
#df.isna() 
df.isnull()

    EmpID   Name    Age  Department  Salary  Experience
0   False  False  False        True   False        True
1   False  False  False       False   False       False
2   False  False  False       False   False       False
3   False  False  False       False   False       False
4   False  False  False       False   False       False
..    ...    ...    ...         ...     ...         ...
95  False  False  False       False   False       False
96  False  False  False       False   False       False
97  False  False  False       False   False       False
98  False  False   True       False   False       False
99  False  False  False       False   False       False

[100 rows x 6 columns]

#### 2. **Check Non-Missing Values**

***notna()*** or ***notnull()***

In [3]:
df.notnull() # or df.notna()

    EmpID  Name    Age  Department  Salary  Experience
0    True  True   True       False    True       False
1    True  True   True        True    True        True
2    True  True   True        True    True        True
3    True  True   True        True    True        True
4    True  True   True        True    True        True
..    ...   ...    ...         ...     ...         ...
95   True  True   True        True    True        True
96   True  True   True        True    True        True
97   True  True   True        True    True        True
98   True  True  False        True    True        True
99   True  True   True        True    True        True

[100 rows x 6 columns]

#### 3. **Count Missing Values**

In [4]:
df.isnull().sum()

EmpID          0
Name           3
Age           11
Department     5
Salary         7
Experience    10
dtype: int64

Total missing values

In [5]:
df.isnull().sum().sum()

np.int64(36)

#### 4. **Check if Any Missing Values Exist**

In [6]:
df.isnull().any()

EmpID         False
Name           True
Age            True
Department     True
Salary         True
Experience     True
dtype: bool

#### 5. **Check if All Values Are Missing**

In [7]:
df.isnull().all()

EmpID         False
Name          False
Age           False
Department    False
Salary        False
Experience    False
dtype: bool

#### 6. **Retrieve Rows with Missing Data**

It returns all rows where at least one column contains a missing value.

In [8]:
df[
    (df['Name'].isnull()) | 
    (df['Age'].isnull()) | 
    (df['Department'].isnull()) | 
    (df['Salary'].isnull()) | 
    (df['Experience'].isnull())
    ] # It returns all rows where at least one column contains a missing value.

    EmpID           Name   Age Department    Salary  Experience
0    1001   Aarav Sharma  22.0        NaN   35000.0         NaN
5    1006   Suresh Naidu  27.0         IT       NaN         5.0
6    1007    Arjun Singh   NaN         HR   42200.0         6.0
7    1008            NaN  29.0    Finance   43400.0         7.0
8    1009  Prakash Yadav  30.0      Sales       NaN         8.0
10   1011   Deepak Joshi   NaN         IT   47000.0        10.0
12   1013     Anil Kumar  34.0    Finance   49400.0         NaN
28   1029  Prakash Yadav  30.0        NaN   68600.0        13.0
29   1030    Manoj Gupta   NaN  Marketing   69800.0        14.0
32   1033     Anil Kumar   NaN    Finance   73400.0         NaN
34   1035    Harish Babu  36.0  Marketing   75800.0         NaN
35   1036     Venu Gopal  37.0         IT   77000.0         NaN
37   1038   Pavan Kalyan  39.0    Finance       NaN         7.0
42   1043   Vikram Patel   NaN    Finance   85400.0        12.0
44   1045    Rahul Verma  26.0  Marketing       NaN        14.0
45   1046   Suresh Naidu  27.0        NaN   89000.0         0.0
47   1048     Naveen Rao  29.0    Finance   91400.0         NaN
56   1057            NaN  38.0         HR  102200.0         NaN
58   1059  Karthik Reddy   NaN      Sales  104600.0        13.0
68   1069  Prakash Yadav   NaN        NaN  116600.0         8.0
69   1070    Manoj Gupta  31.0  Marketing  117800.0         NaN
70   1071            NaN  32.0         IT  119000.0        10.0
71   1072       Sai Teja  33.0        NaN  120200.0         NaN
72   1073     Anil Kumar   NaN    Finance  121400.0        12.0
77   1078   Pavan Kalyan   NaN    Finance  127400.0         NaN
83   1084    Kiran Kumar   NaN      Sales  134600.0         8.0
85   1086   Suresh Naidu  27.0         IT       NaN        10.0
90   1091   Deepak Joshi  32.0         IT       NaN         0.0
91   1092       Sai Teja  33.0         HR       NaN         1.0
98   1099  Karthik Reddy   NaN      Sales  152600.0         8.0

#### **A much shorter and better way**

Instead of checking every column manually

```python
df[df.isna().any(axis=1)] 
#or
df[df.isnull().any(axis=1)]
```

In [9]:
df[df.isnull().any(axis=1)]

    EmpID           Name   Age Department    Salary  Experience
0    1001   Aarav Sharma  22.0        NaN   35000.0         NaN
5    1006   Suresh Naidu  27.0         IT       NaN         5.0
6    1007    Arjun Singh   NaN         HR   42200.0         6.0
7    1008            NaN  29.0    Finance   43400.0         7.0
8    1009  Prakash Yadav  30.0      Sales       NaN         8.0
10   1011   Deepak Joshi   NaN         IT   47000.0        10.0
12   1013     Anil Kumar  34.0    Finance   49400.0         NaN
28   1029  Prakash Yadav  30.0        NaN   68600.0        13.0
29   1030    Manoj Gupta   NaN  Marketing   69800.0        14.0
32   1033     Anil Kumar   NaN    Finance   73400.0         NaN
34   1035    Harish Babu  36.0  Marketing   75800.0         NaN
35   1036     Venu Gopal  37.0         IT   77000.0         NaN
37   1038   Pavan Kalyan  39.0    Finance       NaN         7.0
42   1043   Vikram Patel   NaN    Finance   85400.0        12.0
44   1045    Rahul Verma  26.0  Marketing       NaN        14.0
45   1046   Suresh Naidu  27.0        NaN   89000.0         0.0
47   1048     Naveen Rao  29.0    Finance   91400.0         NaN
56   1057            NaN  38.0         HR  102200.0         NaN
58   1059  Karthik Reddy   NaN      Sales  104600.0        13.0
68   1069  Prakash Yadav   NaN        NaN  116600.0         8.0
69   1070    Manoj Gupta  31.0  Marketing  117800.0         NaN
70   1071            NaN  32.0         IT  119000.0        10.0
71   1072       Sai Teja  33.0        NaN  120200.0         NaN
72   1073     Anil Kumar   NaN    Finance  121400.0        12.0
77   1078   Pavan Kalyan   NaN    Finance  127400.0         NaN
83   1084    Kiran Kumar   NaN      Sales  134600.0         8.0
85   1086   Suresh Naidu  27.0         IT       NaN        10.0
90   1091   Deepak Joshi  32.0         IT       NaN         0.0
91   1092       Sai Teja  33.0         HR       NaN         1.0
98   1099  Karthik Reddy   NaN      Sales  152600.0         8.0

#### 7. **Removing Missing Values *dropna()***

- Remove rows with missing values.

In [10]:
print(df.dropna())
df.dropna().isnull().sum()

    EmpID          Name   Age Department    Salary  Experience
1    1002   Rohan Reddy  23.0         HR   36200.0         1.0
2    1003  Vikram Patel  24.0    Finance   37400.0         2.0
3    1004   Kiran Kumar  25.0      Sales   38600.0         3.0
4    1005   Rahul Verma  26.0  Marketing   39800.0         4.0
9    1010   Manoj Gupta  31.0  Marketing   45800.0         9.0
..    ...           ...   ...        ...       ...         ...
94   1095   Harish Babu  36.0  Marketing  147800.0         4.0
95   1096    Venu Gopal  37.0         IT  149000.0         5.0
96   1097  Ajay Krishna  38.0         HR  150200.0         6.0
97   1098  Pavan Kalyan  39.0    Finance  151400.0         7.0
99   1100    Lokesh Rao  41.0  Marketing  153800.0         9.0

[70 rows x 6 columns]

EmpID         0
Name          0
Age           0
Department    0
Salary        0
Experience    0
dtype: int64

- Remove rows only if all values are missing

In [11]:
print(df.dropna(how='all'))
df.dropna(how='all').isnull().sum()

    EmpID           Name   Age Department    Salary  Experience
0    1001   Aarav Sharma  22.0        NaN   35000.0         NaN
1    1002    Rohan Reddy  23.0         HR   36200.0         1.0
2    1003   Vikram Patel  24.0    Finance   37400.0         2.0
3    1004    Kiran Kumar  25.0      Sales   38600.0         3.0
4    1005    Rahul Verma  26.0  Marketing   39800.0         4.0
..    ...            ...   ...        ...       ...         ...
95   1096     Venu Gopal  37.0         IT  149000.0         5.0
96   1097   Ajay Krishna  38.0         HR  150200.0         6.0
97   1098   Pavan Kalyan  39.0    Finance  151400.0         7.0
98   1099  Karthik Reddy   NaN      Sales  152600.0         8.0
99   1100     Lokesh Rao  41.0  Marketing  153800.0         9.0

[100 rows x 6 columns]

EmpID          0
Name           3
Age           11
Department     5
Salary         7
Experience    10
dtype: int64

- Remove rows if any value is missing

In [12]:
print(df.dropna(how='any'))
df.dropna(how='any').isnull().sum()

    EmpID          Name   Age Department    Salary  Experience
1    1002   Rohan Reddy  23.0         HR   36200.0         1.0
2    1003  Vikram Patel  24.0    Finance   37400.0         2.0
3    1004   Kiran Kumar  25.0      Sales   38600.0         3.0
4    1005   Rahul Verma  26.0  Marketing   39800.0         4.0
9    1010   Manoj Gupta  31.0  Marketing   45800.0         9.0
..    ...           ...   ...        ...       ...         ...
94   1095   Harish Babu  36.0  Marketing  147800.0         4.0
95   1096    Venu Gopal  37.0         IT  149000.0         5.0
96   1097  Ajay Krishna  38.0         HR  150200.0         6.0
97   1098  Pavan Kalyan  39.0    Finance  151400.0         7.0
99   1100    Lokesh Rao  41.0  Marketing  153800.0         9.0

[70 rows x 6 columns]

EmpID         0
Name          0
Age           0
Department    0
Salary        0
Experience    0
dtype: int64

- Keep rows with at least 5 non-missing values

In [13]:
print(df.dropna(thresh=5))
df.dropna(thresh=5).isnull().sum()

    EmpID           Name   Age Department    Salary  Experience
1    1002    Rohan Reddy  23.0         HR   36200.0         1.0
2    1003   Vikram Patel  24.0    Finance   37400.0         2.0
3    1004    Kiran Kumar  25.0      Sales   38600.0         3.0
4    1005    Rahul Verma  26.0  Marketing   39800.0         4.0
5    1006   Suresh Naidu  27.0         IT       NaN         5.0
..    ...            ...   ...        ...       ...         ...
95   1096     Venu Gopal  37.0         IT  149000.0         5.0
96   1097   Ajay Krishna  38.0         HR  150200.0         6.0
97   1098   Pavan Kalyan  39.0    Finance  151400.0         7.0
98   1099  Karthik Reddy   NaN      Sales  152600.0         8.0
99   1100     Lokesh Rao  41.0  Marketing  153800.0         9.0

[94 rows x 6 columns]

EmpID         0
Name          2
Age           8
Department    2
Salary        7
Experience    5
dtype: int64

#### 8. **Filling Missing Values**

- Fill with a constant

In [14]:
df.fillna(0)

    EmpID           Name   Age Department    Salary  Experience
0    1001   Aarav Sharma  22.0          0   35000.0         0.0
1    1002    Rohan Reddy  23.0         HR   36200.0         1.0
2    1003   Vikram Patel  24.0    Finance   37400.0         2.0
3    1004    Kiran Kumar  25.0      Sales   38600.0         3.0
4    1005    Rahul Verma  26.0  Marketing   39800.0         4.0
..    ...            ...   ...        ...       ...         ...
95   1096     Venu Gopal  37.0         IT  149000.0         5.0
96   1097   Ajay Krishna  38.0         HR  150200.0         6.0
97   1098   Pavan Kalyan  39.0    Finance  151400.0         7.0
98   1099  Karthik Reddy   0.0      Sales  152600.0         8.0
99   1100     Lokesh Rao  41.0  Marketing  153800.0         9.0

[100 rows x 6 columns]

- Fill a single column

In [15]:
df['Age'] = df['Age'].fillna(20)
df

    EmpID           Name   Age Department    Salary  Experience
0    1001   Aarav Sharma  22.0        NaN   35000.0         NaN
1    1002    Rohan Reddy  23.0         HR   36200.0         1.0
2    1003   Vikram Patel  24.0    Finance   37400.0         2.0
3    1004    Kiran Kumar  25.0      Sales   38600.0         3.0
4    1005    Rahul Verma  26.0  Marketing   39800.0         4.0
..    ...            ...   ...        ...       ...         ...
95   1096     Venu Gopal  37.0         IT  149000.0         5.0
96   1097   Ajay Krishna  38.0         HR  150200.0         6.0
97   1098   Pavan Kalyan  39.0    Finance  151400.0         7.0
98   1099  Karthik Reddy  20.0      Sales  152600.0         8.0
99   1100     Lokesh Rao  41.0  Marketing  153800.0         9.0

[100 rows x 6 columns]

- Fill different columns with different values

In [16]:

df.fillna({
    'Name': 'Unknown',
    'Age': 20,
    'Department': 'Unknown',
    'Salary': 'N/A',
    'Experience': 'N/A'
}, inplace=True)
df

    EmpID           Name   Age Department    Salary Experience
0    1001   Aarav Sharma  22.0    Unknown   35000.0        N/A
1    1002    Rohan Reddy  23.0         HR   36200.0        1.0
2    1003   Vikram Patel  24.0    Finance   37400.0        2.0
3    1004    Kiran Kumar  25.0      Sales   38600.0        3.0
4    1005    Rahul Verma  26.0  Marketing   39800.0        4.0
..    ...            ...   ...        ...       ...        ...
95   1096     Venu Gopal  37.0         IT  149000.0        5.0
96   1097   Ajay Krishna  38.0         HR  150200.0        6.0
97   1098   Pavan Kalyan  39.0    Finance  151400.0        7.0
98   1099  Karthik Reddy  20.0      Sales  152600.0        8.0
99   1100     Lokesh Rao  41.0  Marketing  153800.0        9.0

[100 rows x 6 columns]

- **Forward Fill (ffill())**

Rule: Fill missing values using the value from the previous row.

In [17]:


new_df = pd.DataFrame({
    "Name": ["Alice", None, "Charlie", None, "Eve"],
    "Salary": [50000, None, 60000, None, 70000]
})

new_df

      Name   Salary
0    Alice  50000.0
1      NaN      NaN
2  Charlie  60000.0
3      NaN      NaN
4      Eve  70000.0

In [18]:
new_df.ffill()

      Name   Salary
0    Alice  50000.0
1    Alice  50000.0
2  Charlie  60000.0
3  Charlie  60000.0
4      Eve  70000.0

- **Backward Fill (bfill())**

Rule: Fill missing values using the value from the next row.

In [19]:
new_df.bfill()

      Name   Salary
0    Alice  50000.0
1  Charlie  60000.0
2  Charlie  60000.0
3      Eve  70000.0
4      Eve  70000.0

- **Replace Missing Values(replace())**

In [20]:
new_df.replace('Alice', 'Bob')

      Name   Salary
0      Bob  50000.0
1      NaN      NaN
2  Charlie  60000.0
3      NaN      NaN
4      Eve  70000.0

In [21]:
df.replace('Finance', 'Finance & Accounting').tail(3)

    EmpID           Name   Age            Department    Salary Experience
97   1098   Pavan Kalyan  39.0  Finance & Accounting  151400.0        7.0
98   1099  Karthik Reddy  20.0                 Sales  152600.0        8.0
99   1100     Lokesh Rao  41.0             Marketing  153800.0        9.0


<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Function</th>
<th>Purpose</th>
</tr>
<tr>
<td><i>isna()</i> / <i>isnull()</i></td>
<td>Detect missing values</td>
</tr>
<tr>
<td><i>notna()</i> / <i>notnull()</i></td>
<td>Detect non-missing values</td>
</tr>
<tr>
<td><i>dropna()</i></td>
<td>Remove missing values</td>
</tr>
<tr>
<td><i>fillna()</i></td>
<td>Fill missing values</td>
</tr>
<tr>
<td><i>ffill()</i></td>
<td>Fill using previous value</td>
</tr>
<tr>
<td><i>bfill()</i></td>
<td>Fill using next value</td>
</tr>
<tr>
<td><i>replace()</i></td>
<td>Replace missing values</td>
</tr>
<tr>
<td><i>isna().sum()</i></td>
<td>Count missing values</td>
</tr>
<tr>
<td><i>isna().any()</i></td>
<td>Check if any missing values exist</td>
</tr>
<tr>
<td><i>isna().all()</i></td>
<td>Check if all values are missing</td>
</tr>
</table>