### **String Operations in Pandas**

String operations are used to work with text data in a DataFrame or Series.

To use string methods in Pandas, use the *.str* accessor.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "emp_id": [101, 102, 103, 104, 105],
    "name": [
        "  alice johnson  ",
        "BOB SMITH",
        "charlie Brown",
        "David Kumar",
        None
    ],
    "email": [
        "alice@gmail.com",
        "BOB@yahoo.com",
        "charlie@gmail.com",
        "david@hotmail.com",
        "emma@gmail.com"
    ],
    "city": [
        "new york",
        "LONDON",
        "mumbai",
        "Hyderabad",
        "CHENNAI"
    ],
    "phone": [
        "9876543210",
        "8765432109",
        "7654321098",
        "6543210987",
        "5432109876"
    ]
})

df

   emp_id               name              email       city       phone
0     101    alice johnson      alice@gmail.com   new york  9876543210
1     102          BOB SMITH      BOB@yahoo.com     LONDON  8765432109
2     103      charlie Brown  charlie@gmail.com     mumbai  7654321098
3     104        David Kumar  david@hotmail.com  Hyderabad  6543210987
4     105                NaN     emma@gmail.com    CHENNAI  5432109876

#### 1. **Case Conversion**

- *upper()*
- *lower()*
- *capitalize()*
- *title()*

In [2]:

print(df['name'].str.upper())
print(df['name'].str.lower())
print(df['name'].str.capitalize())
print(df['city'].str.title())

0      ALICE JOHNSON
1            BOB SMITH
2        CHARLIE BROWN
3          DAVID KUMAR
4                  NaN
Name: name, dtype: str
0      alice johnson
1            bob smith
2        charlie brown
3          david kumar
4                  NaN
Name: name, dtype: str
0      alice johnson
1            Bob smith
2        Charlie brown
3          David kumar
4                  NaN
Name: name, dtype: str
0     New York
1       London
2       Mumbai
3    Hyderabad
4      Chennai
Name: city, dtype: str

#### 2. **Remove Spaces**

- *lstrip()*
- *rstrip()*
- *strip()*

In [3]:
print(df['name'].str.lstrip())
print(df['name'].str.rstrip())
print(df['name'].str.strip())

0    alice johnson
1          BOB SMITH
2      charlie Brown
3        David Kumar
4                NaN
Name: name, dtype: str
0      alice johnson
1          BOB SMITH
2      charlie Brown
3        David Kumar
4                NaN
Name: name, dtype: str
0    alice johnson
1        BOB SMITH
2    charlie Brown
3      David Kumar
4              NaN
Name: name, dtype: str

#### 3. **Length of String**

- *len()*

In [4]:
df['name'].str.len() - df['name'].str.strip().str.len()

0    4.0
1    0.0
2    0.0
3    0.0
4    NaN
Name: name, dtype: float64

#### 4. **Replace Text**

- *replace()*

In [5]:
df['email'].str.replace('gmail', 'outlook').str.replace('yahoo', 'outlook')

0      alice@outlook.com
1        BOB@outlook.com
2    charlie@outlook.com
3      david@hotmail.com
4       emma@outlook.com
Name: email, dtype: str

#### 5. **Check Contains**

- *contains()*

In [6]:
print(df['email'])
df['email'].str.contains('gmail')

0      alice@gmail.com
1        BOB@yahoo.com
2    charlie@gmail.com
3    david@hotmail.com
4       emma@gmail.com
Name: email, dtype: str

0     True
1    False
2     True
3    False
4     True
Name: email, dtype: bool

#### 6. **Startswith / Endswith**

- *startswith()*
- *endswith()*

In [7]:
print(df['email'])
print(df['email'].str.startswith('a'))
print(df['email'].str.endswith('.com'))

0      alice@gmail.com
1        BOB@yahoo.com
2    charlie@gmail.com
3    david@hotmail.com
4       emma@gmail.com
Name: email, dtype: str
0     True
1    False
2    False
3    False
4    False
Name: email, dtype: bool
0    True
1    True
2    True
3    True
4    True
Name: email, dtype: bool

#### 7. **Split Strings**

- *split()*

In [8]:
df['email'].str.split('@')

0      [alice, gmail.com]
1        [BOB, yahoo.com]
2    [charlie, gmail.com]
3    [david, hotmail.com]
4       [emma, gmail.com]
Name: email, dtype: object

#### 8. **Extract email domain**

In [9]:
df['email'].str.split('@').str[1]

0      gmail.com
1      yahoo.com
2      gmail.com
3    hotmail.com
4      gmail.com
Name: email, dtype: object

#### 9. **Extract first name**

In [10]:
df['email'].str.split('@').str[0]

0      alice
1        BOB
2    charlie
3      david
4       emma
Name: email, dtype: object

#### 10. **Get Specific Characters**

In [11]:
print(df['name'])
# Indexing
print(df['name'].str.strip().str[0]) # first character
print(df['name'].str.strip().str[-1]) # last character
# Slicing
print(df['name'].str.strip().str[:3])

0      alice johnson
1            BOB SMITH
2        charlie Brown
3          David Kumar
4                  NaN
Name: name, dtype: str
0      a
1      B
2      c
3      D
4    NaN
Name: name, dtype: str
0      n
1      H
2      n
3      r
4    NaN
Name: name, dtype: str
0    ali
1    BOB
2    cha
3    Dav
4    NaN
Name: name, dtype: str

#### 11. **Count Occurrences**

In [12]:
print(df['email'])
df['email'].str.count('a')

0      alice@gmail.com
1        BOB@yahoo.com
2    charlie@gmail.com
3    david@hotmail.com
4       emma@gmail.com
Name: email, dtype: str

0    2
1    1
2    2
3    2
4    2
Name: email, dtype: int64

#### 12. **Find Position**

In [13]:
print(df['email'])
df['email'].str.index('@')

0      alice@gmail.com
1        BOB@yahoo.com
2    charlie@gmail.com
3    david@hotmail.com
4       emma@gmail.com
Name: email, dtype: str

0    5
1    3
2    7
3    5
4    4
Name: email, dtype: int64

#### 13. **Concatenate Strings**

In [14]:
df['name'].str.strip().str.capitalize()+ '-'+df['city'].str.title()

0    Alice johnson-New York
1          Bob smith-London
2      Charlie brown-Mumbai
3     David kumar-Hyderabad
4                       NaN
dtype: str

**Real-World Example**

In [15]:
# Clean employees names.
df['name'] = df['name'].str.strip().str.title()
# Emails are usually stored in lowercase.
df['email'] = df['email'].str.strip().str.lower()
# Cities are usually stored in title case.
df['city'] = df['city'].str.strip().str.title()
df # Clean dataframe

   emp_id           name              email       city       phone
0     101  Alice Johnson    alice@gmail.com   New York  9876543210
1     102      Bob Smith      bob@yahoo.com     London  8765432109
2     103  Charlie Brown  charlie@gmail.com     Mumbai  7654321098
3     104    David Kumar  david@hotmail.com  Hyderabad  6543210987
4     105            NaN     emma@gmail.com    Chennai  5432109876

Instead of writing code repeatedly:

In [16]:
cols = ['name', 'city']
for col in cols:
    df[col] = df[col].str.strip().str.title()

df['city'] = df['city'].str.strip().str.title()

df

   emp_id           name              email       city       phone
0     101  Alice Johnson    alice@gmail.com   New York  9876543210
1     102      Bob Smith      bob@yahoo.com     London  8765432109
2     103  Charlie Brown  charlie@gmail.com     Mumbai  7654321098
3     104    David Kumar  david@hotmail.com  Hyderabad  6543210987
4     105            NaN     emma@gmail.com    Chennai  5432109876


#### **Most Important Methods for Data Analysis**
```python
.str.lower()
.str.upper()
.str.title()
.str.strip()
.str.replace()
.str.contains()
.str.startswith()
.str.endswith()
.str.split()
.str.len()
```