### **GroupBy in Pandas**

*groupby()* is one of the most important operations in pandas. It is used to group rows that have the same value and then perform calculations on each group.

Think of it as:

Split → Apply → Combine

1. Split data into groups
2. Apply a function (sum, mean, count, etc.)
3. Combine the results

**General Syntax**
```python
df.groupby(group_column)[value_column].operation()
```

In [24]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Employees.csv')
df

    EmpID          Name  Age   Department  Salary  Experience
0    1001  Sneha Sharma   39        Sales   45401           7
1    1002   Sneha Kumar   49           IT   28124           0
2    1003   Neha Sharma   34  Engineering   40488           3
3    1004  Arjun Sharma   32  Engineering   42973           5
4    1005    Karan Nair   28           HR   35200           3
..    ...           ...  ...          ...     ...         ...
95   1096  Aditya Verma   45      Finance   88574          19
96   1097   Sneha Gupta   41           HR   68270          18
97   1098   Pooja Menon   47        Sales   39789           2
98   1099    Neha Reddy   41           HR   90979          18
99   1100    Divya Bose   45           HR   81131          16

[100 rows x 6 columns]

#### 1. **Basic *groupby()***

**Example:**

```python
df.groupby("Department")["Salary"].sum()
```

**Meaning:**

1. Group employees by Department.
2. Take Salary column.
3. Add salaries in each department.

In [25]:
df.groupby('Department')['Salary'].sum()

Department
Engineering    1240266
Finance         566291
HR             1348830
IT              417014
Marketing       646110
Operations      485180
Sales           687842
Support         583110
Name: Salary, dtype: int64

#### 2. **View Groups**

Shows row indexes in each group.

In [26]:
df.groupby('Department').groups

{'Engineering': [2, 3, 10, 13, 14, 16, 18, 24, 36, 43, 56, 60, 62, 64, 67, 77, 82, 83, 88, 89], 'Finance': [20, 23, 52, 53, 55, 74, 75, 87, 95], 'HR': [4, 9, 17, 19, 27, 30, 34, 35, 40, 41, 44, 47, 57, 63, 65, 76, 92, 94, 96, 98, 99], 'IT': [1, 15, 21, 31, 39, 68, 84], 'Marketing': [7, 38, 45, 46, 48, 50, 61, 66, 70, 71, 79, 90], 'Operations': [6, 25, 32, 42, 80, 86], 'Sales': [0, 11, 12, 22, 26, 28, 29, 54, 59, 72, 73, 81, 93, 97], 'Support': [5, 8, 33, 37, 49, 51, 58, 69, 78, 85, 91]}

#### 3. **Aggregation Functions**

- *sum()*
- *mean()*
- *min()*
- *max()*
- *count()*
- *median()*
- *first()*
- *last()*

- ##### ***sum()***

In [27]:
df.groupby('Department')['Salary'].sum()

Department
Engineering    1240266
Finance         566291
HR             1348830
IT              417014
Marketing       646110
Operations      485180
Sales           687842
Support         583110
Name: Salary, dtype: int64

- ##### ***mean()***

In [28]:
df.groupby('Department')['Salary'].mean()

Department
Engineering    62013.300000
Finance        62921.222222
HR             64230.000000
IT             59573.428571
Marketing      53842.500000
Operations     80863.333333
Sales          49131.571429
Support        53010.000000
Name: Salary, dtype: float64

- ##### ***min()***

In [29]:
df.groupby('Department')['Salary'].min()

Department
Engineering    28975
Finance        33257
HR             28995
IT             28124
Marketing      29296
Operations     49085
Sales          28027
Support        33247
Name: Salary, dtype: int64

- ##### ***max()***

In [30]:
df.groupby('Department')['Salary'].max()

Department
Engineering    119960
Finance         92901
HR             113382
IT             109273
Marketing      115243
Operations     115131
Sales          100749
Support         88349
Name: Salary, dtype: int64

- ##### ***count()***

In [31]:
df.groupby('Department')['Salary'].count()

Department
Engineering    20
Finance         9
HR             21
IT              7
Marketing      12
Operations      6
Sales          14
Support        11
Name: Salary, dtype: int64

#### 4. **Multiple Aggregations**

**Instead of running many queries:**

``` python
df.groupby("Department")["Salary"].sum()

df.groupby("Department")["Salary"].mean()

df.groupby("Department")["Salary"].max()
```

**Use *agg()*:**

```python
df.groupby("Department")["Salary"].agg(
    ["sum", "mean", "min", "max", "count"]
```

In [32]:
df.groupby('Department')['Salary'].agg(['sum', 'max', 'min', 'count', 'mean', 'median'])

                 sum     max    min  count          mean   median
Department
Engineering  1240266  119960  28975     20  62013.300000  55471.5
Finance       566291   92901  33257      9  62921.222222  60740.0
HR           1348830  113382  28995     21  64230.000000  61966.0
IT            417014  109273  28124      7  59573.428571  53275.0
Marketing     646110  115243  29296     12  53842.500000  47450.5
Operations    485180  115131  49085      6  80863.333333  77578.5
Sales         687842  100749  28027     14  49131.571429  40327.0
Support       583110   88349  33247     11  53010.000000  55491.0

#### 5. ***as_index=False***

**Default:**

```python
df.groupby("Department")["Salary"].sum()
```

Department becomes index.

**To keep it as a normal column:**
```python
df.groupby(
    "Department",
    as_index=False
)["Salary"].sum()
```

In [33]:
df.groupby('Department', as_index=False)['Salary'].sum()

    Department   Salary
0  Engineering  1240266
1      Finance   566291
2           HR  1348830
3           IT   417014
4    Marketing   646110
5   Operations   485180
6        Sales   687842
7      Support   583110

#### 6. **Get Particular Group**

In [34]:
df.groupby('Department').get_group('IT')

    EmpID             Name  Age Department  Salary  Experience
1    1002      Sneha Kumar   49         IT   28124           0
15   1016  Vikram Malhotra   27         IT   28834           0
21   1022       Aarav Nair   53         IT   60402           7
31   1032       Meera Bose   51         IT   95814          21
39   1040       Priya Nair   25         IT   41292           3
68   1069     Ananya Desai   47         IT   53275           9
84   1085      Aarav Menon   52         IT  109273          30

#### 7. **Sorting Groups**

**Default:**

```python
df.groupby("Department").sum()
```
Groups are sorted alphabetically.

**Disable sorting:**

```python
df.groupby(
    "Department",
    sort=False
).sum()
```

In [35]:
df.groupby('Department', sort=False)['Salary'].sum()

Department
Sales           687842
IT              417014
Engineering    1240266
HR             1348830
Support         583110
Operations      485180
Marketing       646110
Finance         566291
Name: Salary, dtype: int64

#### 8. **Group By Multiple Columns**

In [36]:
new_df = pd.DataFrame({
    "EmpID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Ravi","Priya","Kiran","Anu","Raj",
             "Deepa","Arjun","Sneha","Vijay","Pooja"],
    "Department": ["IT","HR","IT","HR","Sales",
                   "Sales","IT","HR","Sales","IT"],
    "City": ["Hyderabad","Chennai","Bangalore","Chennai",
             "Mumbai","Mumbai","Hyderabad","Bangalore",
             "Mumbai","Bangalore"],
    "Gender": ["M","F","M","F","M",
               "F","M","F","M","F"],
    "Salary": [50000,40000,60000,45000,55000,
               65000,70000,48000,52000,62000],
    "Bonus": [5000,3000,7000,3500,6000,
              8000,9000,4000,5500,7500]
})
new_df

   EmpID   Name Department       City Gender  Salary  Bonus
0    101   Ravi         IT  Hyderabad      M   50000   5000
1    102  Priya         HR    Chennai      F   40000   3000
2    103  Kiran         IT  Bangalore      M   60000   7000
3    104    Anu         HR    Chennai      F   45000   3500
4    105    Raj      Sales     Mumbai      M   55000   6000
5    106  Deepa      Sales     Mumbai      F   65000   8000
6    107  Arjun         IT  Hyderabad      M   70000   9000
7    108  Sneha         HR  Bangalore      F   48000   4000
8    109  Vijay      Sales     Mumbai      M   52000   5500
9    110  Pooja         IT  Bangalore      F   62000   7500

In [37]:
new_df.groupby(['Department', 'City'])['Salary'].sum()

Department  City
HR          Bangalore     48000
            Chennai       85000
IT          Bangalore    122000
            Hyderabad    120000
Sales       Mumbai       172000
Name: Salary, dtype: int64

#### 9. **Different Aggregations for Different Columns**

**Suppose:**

- Salary → average salary
- Bonus → total bonus
- EmpID → employee count

**Use a dictionary:**

```python
df.groupby("Department").agg({
    "Salary": "mean",
    "Bonus": "sum",
    "EmpID": "count"
})
```

In [38]:
new_df.groupby('Department').agg({
    'Salary':'mean',
    'Bonus':'sum',
    'EmpID':'count'
})

                  Salary  Bonus  EmpID
Department
HR          44333.333333  10500      3
IT          60500.000000  28500      4
Sales       57333.333333  19500      3

#### 10. **Multiple Aggregations on Multiple Columns**

In [39]:
new_df.groupby('Department').agg({
    'Salary':['sum', 'mean', 'max', 'min'],
    'Bonus':['sum', 'mean', 'max', 'min']
})

            Salary                              Bonus
               sum          mean    max    min    sum    mean   max   min
Department
HR          133000  44333.333333  48000  40000  10500  3500.0  4000  3000
IT          242000  60500.000000  70000  50000  28500  7125.0  9000  5000
Sales       172000  57333.333333  65000  52000  19500  6500.0  8000  5500

#### 11. **Named Aggregations**

In [40]:
new_df.groupby('Department').agg(
    avg_salary = ('Salary', 'mean'),
    total_bonus = ('Bonus','sum'),
    no_of_employees = ('EmpID', 'count')
)

              avg_salary  total_bonus  no_of_employees
Department
HR          44333.333333        10500                3
IT          60500.000000        28500                4
Sales       57333.333333        19500                3

#### 12. **Group by Multiple Value Columns**

In [41]:
new_df.groupby('Department')[['Salary', 'Bonus']].sum() # Salary & Bonus summed for each department

            Salary  Bonus
Department
HR          133000  10500
IT          242000  28500
Sales       172000  19500

#### 13. **Transform**

Returns the same number of rows as original DataFrame.

In [42]:
new_df['Max Salary'] = new_df.groupby('Department')['Salary'].transform('max')

In [43]:
new_df.sort_values(by=['Department', 'Salary'], ascending=[1,0])

   EmpID   Name Department       City Gender  Salary  Bonus  Max Salary
7    108  Sneha         HR  Bangalore      F   48000   4000       48000
3    104    Anu         HR    Chennai      F   45000   3500       48000
1    102  Priya         HR    Chennai      F   40000   3000       48000
6    107  Arjun         IT  Hyderabad      M   70000   9000       70000
9    110  Pooja         IT  Bangalore      F   62000   7500       70000
2    103  Kiran         IT  Bangalore      M   60000   7000       70000
0    101   Ravi         IT  Hyderabad      M   50000   5000       70000
5    106  Deepa      Sales     Mumbai      F   65000   8000       65000
4    105    Raj      Sales     Mumbai      M   55000   6000       65000
8    109  Vijay      Sales     Mumbai      M   52000   5500       65000

#### **Why do we need Transform?**

**Suppose you want to know:**

What is the average salary of each employee’s department?

**If you use agg():**

In [44]:
new_df.groupby('Department')['Salary'].agg('mean')

Department
HR       44333.333333
IT       60500.000000
Sales    57333.333333
Name: Salary, dtype: float64


You get only 3 rows, not 10.

But we want the average salary attached to every employee row.

**Using transform()**

In [45]:
new_df['Dept_avg_sal'] = new_df.groupby('Department')['Salary'].transform('mean')

In [46]:
new_df.sort_values(by='Department')

,EmpID,Name,Department,City,Gender,Salary,Bonus,Max Salary,Dept_avg_sal
1,102,Priya,HR,Chennai,F,40000,3000,48000,44333.333333
3,104,Anu,HR,Chennai,F,45000,3500,48000,44333.333333
7,108,Sneha,HR,Bangalore,F,48000,4000,48000,44333.333333
0,101,Ravi,IT,Hyderabad,M,50000,5000,70000,60500.000000
2,103,Kiran,IT,Bangalore,M,60000,7000,70000,60500.000000
6,107,Arjun,IT,Hyderabad,M,70000,9000,70000,60500.000000
9,110,Pooja,IT,Bangalore,F,62000,7500,70000,60500.000000
4,105,Raj,Sales,Mumbai,M,55000,6000,65000,57333.333333
5,106,Deepa,Sales,Mumbai,F,65000,8000,65000,57333.333333
8,109,Vijay,Sales,Mumbai,M,52000,5500,65000,57333.333333