### **Merge, Join, Concat Dataframes**

These are the three main ways to combine DataFrames in pandas:

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Method</th>
<th>Purpose</th>
<th>Similar to SQL</th>
<th>Combines By</th>
</tr>
<tr>
<td><i>merge()</i></td>
<td>Combine using common columns</td>
<td>JOIN</td>
<td>Columns (or indexes)</td>
</tr>
<tr>
<td><i>join()</i></td>
<td>Combine using indexes (or one column)</td>
<td>JOIN</td>
<td>Mainly indexes</td>
</tr>
<tr>
<td><i>concat()</i></td>
<td>Stack DataFrames</td>
<td>UNION</td>
<td>Rows or columns</td>
</tr>
</table>

In [1]:
import pandas as pd

customers = pd.read_csv(r'sample_datasets\merge_join_practice_data\customers.csv')
orders = pd.read_csv(r'sample_datasets\merge_join_practice_data\orders.csv')
products = pd.read_csv(r'sample_datasets\merge_join_practice_data\products.csv')

In [2]:
customers

   customer_id     name      city  age
0          101    Alice  New York   28
1          102      Bob    London   35
2          103  Charlie     Paris   42
3          104    David     Tokyo   31
4          105      Eva    Berlin   29

In [3]:
orders

   order_id  customer_id     product  amount        date
0      1001          101      Laptop    1200  2024-01-15
1      1002          102       Phone     800  2024-01-20
2      1003          101  Headphones     150  2024-02-01
3      1004          103      Tablet     600  2024-02-10
4      1005          106     Monitor     300  2024-03-05

In [4]:
products

  product_name     category  price
0       Laptop  Electronics   1200
1        Phone  Electronics    800
2   Headphones  Accessories    150
3       Tablet  Electronics    600
4      Monitor  Electronics    300
5     Keyboard  Accessories     80

#### 1. ***merge()***

Purpose: Combine DataFrames based on one or more common columns.

**Syntax:**
```python
pd.merge(
    left,
    right,
    how='inner',
    on=None,
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    suffixes=['_x', '_y']
)
```

**Parameters:**
- *left*: Left DataFrame.
- *right*: Right DataFrame.
- *how='inner'*: Type of join.
    - *'inner'* → Matching rows only.
    - *'left'* → All rows from left DataFrame.
    - *'right'* → All rows from right DataFrame.
    - *'outer'* → All rows from both DataFrames.
    - *'cross'* → Cartesian product (every row with every row).
- *on='column_name'*: Common column present in both DataFrames.
- *left_on='column'*: Join column from the left DataFrame.
- *right_on='column'*: Join column from the right DataFrame.
- *left_index=True*: Use the left DataFrame's index as the key.
- *right_index=True*: Use the right DataFrame's index as the key.
- *suffixes=['_x', '_y']*: Rename duplicate column names after merging.
- *indicator=False:*
    - *False (default)*: Don't add an indicator column.
    - *True*: Add a column named *_merge* showing the source of each row.
    - You can also provide a string (e.g., *indicator='source'*) to use a custom column name.

##### 1. **Inner Join (default)**

Keeps only matching rows.

In [5]:
inner_join = pd.merge(customers, orders, on='customer_id')
inner_join

,customer_id,name,city,age,order_id,product,amount,date
0,101,Alice,New York,28,1001,Laptop,1200,2024-01-15
1,101,Alice,New York,28,1003,Headphones,150,2024-02-01
2,102,Bob,London,35,1002,Phone,800,2024-01-20
3,103,Charlie,Paris,42,1004,Tablet,600,2024-02-10

##### 2. **Left Join**

Keeps all rows from the left DataFrame.

In [6]:
left_join_1 = pd.merge(customers, orders, on='customer_id', how='left')
left_join_1

,customer_id,name,city,age,order_id,product,amount,date
0,101,Alice,New York,28,1001.0,Laptop,1200.0,2024-01-15
1,101,Alice,New York,28,1003.0,Headphones,150.0,2024-02-01
2,102,Bob,London,35,1002.0,Phone,800.0,2024-01-20
3,103,Charlie,Paris,42,1004.0,Tablet,600.0,2024-02-10
4,104,David,Tokyo,31,NaN,NaN,NaN,NaN
5,105,Eva,Berlin,29,NaN,NaN,NaN,NaN

In [7]:
left_join_2 = pd.merge(orders, customers, on='customer_id', how='left')
left_join_2

,order_id,customer_id,product,amount,date,name,city,age
0,1001,101,Laptop,1200,2024-01-15,Alice,New York,28.0
1,1002,102,Phone,800,2024-01-20,Bob,London,35.0
2,1003,101,Headphones,150,2024-02-01,Alice,New York,28.0
3,1004,103,Tablet,600,2024-02-10,Charlie,Paris,42.0
4,1005,106,Monitor,300,2024-03-05,NaN,NaN,NaN

##### 3. **Right Join**

Keeps all rows from the right DataFrame.

Many people simply avoid *right joins* because the *left* version is often easier to read.

In [8]:
right_join = pd.merge(customers, orders, on='customer_id', how='right')
right_join

,customer_id,name,city,age,order_id,product,amount,date
0,101,Alice,New York,28.0,1001,Laptop,1200,2024-01-15
1,102,Bob,London,35.0,1002,Phone,800,2024-01-20
2,101,Alice,New York,28.0,1003,Headphones,150,2024-02-01
3,103,Charlie,Paris,42.0,1004,Tablet,600,2024-02-10
4,106,NaN,NaN,NaN,1005,Monitor,300,2024-03-05

##### 4. **Outer Join**

Keeps every row from both DataFrames.

In [9]:
outer_join = pd.merge(customers, orders, on='customer_id', how='outer')
outer_join

,customer_id,name,city,age,order_id,product,amount,date
0,101,Alice,New York,28.0,1001.0,Laptop,1200.0,2024-01-15
1,101,Alice,New York,28.0,1003.0,Headphones,150.0,2024-02-01
2,102,Bob,London,35.0,1002.0,Phone,800.0,2024-01-20
3,103,Charlie,Paris,42.0,1004.0,Tablet,600.0,2024-02-10
4,104,David,Tokyo,31.0,NaN,NaN,NaN,NaN
5,105,Eva,Berlin,29.0,NaN,NaN,NaN,NaN
6,106,NaN,NaN,NaN,1005.0,Monitor,300.0,2024-03-05

##### 5. **Merge on Different Column Names**

When to use

When the matching columns have different names in each DataFrame.

In [10]:
# Employee Data
employees = pd.DataFrame({
    "employee_id": [101, 102, 103, 104],
    "Name": ["Alice", "Bob", "Charlie", "David"]
})
# Salary Data
salary = pd.DataFrame({
    "id": [101, 102, 104, 105],
    "Salary": [50000, 60000, 70000, 80000]
})

In [11]:
result1 = pd.merge(
    employees,
    salary, 
    left_on='employee_id', 
    right_on='id')
result1

   employee_id   Name   id  Salary
0          101  Alice  101   50000
1          102    Bob  102   60000
2          104  David  104   70000

##### 6. **Merge on Multiple Columns**

In [12]:
# Employees
employees = pd.DataFrame({
    "EmpID": [101,101,102,103],
    "Department": ["HR","IT","IT","Sales"],
    "Name": ["Alice","Alice","Bob","Charlie"]
})
# Salary
salary = pd.DataFrame({
    "EmpID": [101,101,102,104],
    "Department": ["HR","Finance","IT","Sales"],
    "Salary": [50000,65000,60000,70000]
})

In [13]:
print(employees)
print(salary)

   EmpID Department     Name
0    101         HR    Alice
1    101         IT    Alice
2    102         IT      Bob
3    103      Sales  Charlie
   EmpID Department  Salary
0    101         HR   50000
1    101    Finance   65000
2    102         IT   60000
3    104      Sales   70000

In [14]:
result2 = pd.merge(
    employees,
    salary,
    on=['EmpID', 'Department']
)
result2

   EmpID Department   Name  Salary
0    101         HR  Alice   50000
1    102         IT    Bob   60000

**Notice:**

- (101, HR) matches
- (101, IT) does not match (101, Finance)

Both columns must match.

##### 7. **Add Suffixes for Duplicate Column Names**

Why use suffixes?

Without suffixes, pandas automatically creates *_x* and *_y*, which are less descriptive.

In [15]:
# Employee Details
employees = pd.DataFrame({
    "EmpID": [101,102,103],
    "Department": ["HR","IT","Sales"]
})
# Employee Transfers
transfers = pd.DataFrame({
    "EmpID": [101,102,103],
    "Department": ["Finance","IT","Marketing"]
})
print(employees)
print(transfers)

   EmpID Department
0    101         HR
1    102         IT
2    103      Sales
   EmpID Department
0    101    Finance
1    102         IT
2    103  Marketing

In [16]:
result3 = pd.merge(
    employees,
    transfers,
    on='EmpID',
    suffixes=['_old', '_new']
    )
result3

   EmpID Department_old Department_new
0    101             HR        Finance
1    102             IT             IT
2    103          Sales      Marketing

##### 8. **Merge on Index**

In [17]:
# Employees
employees = pd.DataFrame({
    "Name": ["Alice","Bob","Charlie"]
}, index=[101,102,103])
# Salary
salary = pd.DataFrame({
    "Salary": [50000,60000,70000]
}, index=[101,102,104])

In [18]:
result4 = pd.merge(
    employees,
    salary,
    left_index=True,
    right_index=True,
    how='outer'
)
result4

        Name   Salary
101    Alice  50000.0
102      Bob  60000.0
103  Charlie      NaN
104      NaN  70000.0

##### 9. **Useful Merge Indicators**

See where each row came from:

In [19]:
result5 = pd.merge(
    customers,
    orders, 
    on='customer_id', 
    how='outer',
    indicator=True)
result5

,customer_id,name,city,age,order_id,product,amount,date,_merge
0,101,Alice,New York,28.0,1001.0,Laptop,1200.0,2024-01-15,both
1,101,Alice,New York,28.0,1003.0,Headphones,150.0,2024-02-01,both
2,102,Bob,London,35.0,1002.0,Phone,800.0,2024-01-20,both
3,103,Charlie,Paris,42.0,1004.0,Tablet,600.0,2024-02-10,both
4,104,David,Tokyo,31.0,NaN,NaN,NaN,NaN,left_only
5,105,Eva,Berlin,29.0,NaN,NaN,NaN,NaN,left_only
6,106,NaN,NaN,NaN,1005.0,Monitor,300.0,2024-03-05,right_only

##### 10. **Joining Three DataFrames**

In [20]:
print(customers)
print(orders)
print(products)

   customer_id     name      city  age
0          101    Alice  New York   28
1          102      Bob    London   35
2          103  Charlie     Paris   42
3          104    David     Tokyo   31
4          105      Eva    Berlin   29
   order_id  customer_id     product  amount        date
0      1001          101      Laptop    1200  2024-01-15
1      1002          102       Phone     800  2024-01-20
2      1003          101  Headphones     150  2024-02-01
3      1004          103      Tablet     600  2024-02-10
4      1005          106     Monitor     300  2024-03-05
  product_name     category  price
0       Laptop  Electronics   1200
1        Phone  Electronics    800
2   Headphones  Accessories    150
3       Tablet  Electronics    600
4      Monitor  Electronics    300
5     Keyboard  Accessories     80

In [21]:
result6 = (
    customers
    .merge(orders, on='customer_id', how='left')
    .merge(products, left_on='product', right_on='product_name', how='left')
)
result6

,customer_id,name,city,age,order_id,product,amount,date,product_name,category,price
0,101,Alice,New York,28,1001.0,Laptop,1200.0,2024-01-15,Laptop,Electronics,1200.0
1,101,Alice,New York,28,1003.0,Headphones,150.0,2024-02-01,Headphones,Accessories,150.0
2,102,Bob,London,35,1002.0,Phone,800.0,2024-01-20,Phone,Electronics,800.0
3,103,Charlie,Paris,42,1004.0,Tablet,600.0,2024-02-10,Tablet,Electronics,600.0
4,104,David,Tokyo,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,105,Eva,Berlin,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### 11. **Self Join**

A self join means joining a DataFrame with itself.

In [22]:
# Example: Employees and Managers

employees = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
    "emp_name": ["Alice", "Bob", "Charlie", "David"],
    "manager_id": [None, 1, 1, 2]
})

print(employees)

   emp_id emp_name  manager_id
0       1    Alice         NaN
1       2      Bob         1.0
2       3  Charlie         1.0
3       4    David         2.0

In [23]:
result7 = (
    employees
    .merge(employees, left_on='manager_id', right_on='emp_id', suffixes=('_employee', 'manager'), how='left')
)
result7

,emp_id_employee,emp_name_employee,manager_id_employee,emp_idmanager,emp_namemanager,manager_idmanager
0,1,Alice,NaN,NaN,NaN,NaN
1,2,Bob,1.0,1.0,Alice,NaN
2,3,Charlie,1.0,1.0,Alice,NaN
3,4,David,2.0,2.0,Bob,1.0

##### 12. **Cross Join**

A cross join (Cartesian product) combines every row from the first DataFrame with every row from the second DataFrame.

In [24]:
# Example
colors = pd.DataFrame({
    "Color": ["Red", "Blue"]
})

sizes = pd.DataFrame({
    "Size": ["S", "M", "L"]
})

In [25]:
result8 = colors.merge(sizes, how='cross')
result8

  Color Size
0   Red    S
1   Red    M
2   Red    L
3  Blue    S
4  Blue    M
5  Blue    L

##### **Option 1: *pd.merge()***
```python
result = pd.merge(df1, df2, on='id', how='inner')
```
- This is a function in the pandas module.
- It explicitly shows that you're using pandas to merge two DataFrames.
- Some people prefer it because it looks similar to other pandas functions like pd.concat().

##### **Option 2: *DataFrame.merge()***
```python
result = df1.merge(df2, on='id', how='inner')
```
- This is a method of the DataFrame object.
- It starts from the left DataFrame (df1) and merges df2 into it.
- It is convenient when you want to chain multiple operations.

#### 2. ***join()***

join() is a method used to combine two DataFrames based on their indexes by default.

**Syntax:**
```python
df.join(
    other,
    on=None,
    how='left',
    lsuffix='',
    rsuffix=''
)
```

**Parameters:**
- *other*: DataFrame to join.
- *on='column_name'*: Column in the calling DataFrame to join on the index of the other DataFrame.
- *how='left'*: Type of join.
    - *'left'*
    - *'right'*
    - *'inner'*
    - *'outer'*
    - *'cross'*
- *lsuffix=''*: Suffix for overlapping column names in the left DataFrame.
- *rsuffix=''*: Suffix for overlapping column names in the right DataFrame.

In [26]:

students = pd.DataFrame({
    'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Kumar']
}, index=[101, 102, 103, 104, 107,])


marks = pd.DataFrame({
    'Marks': [85, 90, 78, 70, 84]
}, index=[101, 102, 104, 105, 106])

print(students)
print(marks)

      Name
101   Amit
102  Priya
103  Rahul
104  Sneha
107  Kumar
     Marks
101     85
102     90
104     78
105     70
106     84

##### 1. **Basic *join()* (Default = Left Join)**

In [27]:
students.join(marks)

      Name  Marks
101   Amit   85.0
102  Priya   90.0
103  Rahul    NaN
104  Sneha   78.0
107  Kumar    NaN

##### 2. **Outer *join()***

In [28]:
students.join(marks, how='outer')

      Name  Marks
101   Amit   85.0
102  Priya   90.0
103  Rahul    NaN
104  Sneha   78.0
105    NaN   70.0
106    NaN   84.0
107  Kumar    NaN

##### 3. **Joining on a Column Using on**

Suppose student IDs are stored as a column instead of the index.

In [29]:
students = pd.DataFrame({
    'StudentID': [101,102,103,104],
    'Name': ['Amit','Priya','Rahul','Sneha']
})

marks = pd.DataFrame({
    'Marks': [85,90,78]
}, index=[101,102,104])
print(students)
print(marks)

   StudentID   Name
0        101   Amit
1        102  Priya
2        103  Rahul
3        104  Sneha
     Marks
101     85
102     90
104     78

In [30]:
students.join(marks, on='StudentID')

   StudentID   Name  Marks
0        101   Amit   85.0
1        102  Priya   90.0
2        103  Rahul    NaN
3        104  Sneha   78.0

##### 4. **Overlapping Column Names**

Suppose both DataFrames contain a Name column.

In [31]:

students = pd.DataFrame({
    'Name': ['Amit','Priya']
}, index=[101,102])

teachers = pd.DataFrame({
    'Name': ['Raj','Meena']
}, index=[101,102])
print(students)
print(teachers)

      Name
101   Amit
102  Priya
      Name
101    Raj
102  Meena

In [32]:
# Without suffixs:
#students.join(teachers) # ValueError: columns overlap but no suffix specified
# Correct way:
students.join(teachers, lsuffix='_Student', rsuffix='_Teacher')

    Name_Student Name_Teacher
101         Amit          Raj
102        Priya        Meena

#### ***join()* vs *merge()***

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Feature</th>
<th><i>join()</i></th>
<th><i>merge()</i></th>
</tr>
<tr>
<td>Default join key</td>
<td>Index</td>
<td>Column(s)</td>
</tr>
<tr>
<td>Default join type</td>
<td>Left</td>
<td>Inner</td>
</tr>
<tr>
<td>Best for</td>
<td>Index-based joins</td>
<td>Column-based joins</td>
</tr>
<tr>
<td>SQL-like operations</td>
<td>Limited</td>
<td>More flexible</td>
</tr>
</table>

#### 3. ***concat()***

*concat()* is used to combine DataFrames or Series along rows or columns.

**Syntax:**
```python
pd.concat(objs, axis=0, ignore_index=False)
```
**Parameters:**
- objs: List of DataFrames/Series to combine.
- axis=0: Concatenate vertically (rows).
- axis=1: Concatenate horizontally (columns).
- ignore_index=True: Reset the index in the resulting DataFrame.

In [34]:
employees1 = pd.read_csv(r'sample_datasets\merge_join_practice_data\employees_q1.csv')
employees2 = pd.read_csv(r'sample_datasets\merge_join_practice_data\employees_q2.csv')
print(employees1)
print(employees2)

  emp_id   name department  salary
0   E001   John      Sales   65000
1   E002  Sarah  Marketing   72000
2   E003   Mike         IT   85000
  emp_id  name department  salary
0   E003  Mike         IT   87000
1   E004  Anna         HR   68000
2   E005   Tom      Sales   69000

##### 1. **Concatenate Rows (Vertical)**

In [ ]:
all_emp_v = pd.concat([employees1, employees2])
all_emp_v

  emp_id   name department  salary
0   E001   John      Sales   65000
1   E002  Sarah  Marketing   72000
2   E003   Mike         IT   85000
0   E003   Mike         IT   87000
1   E004   Anna         HR   68000
2   E005    Tom      Sales   69000

Reset index:

In [ ]:
all_emp_v2 = pd.concat([employees1, employees2], ignore_index=True)
all_emp_v2

  emp_id   name department  salary
0   E001   John      Sales   65000
1   E002  Sarah  Marketing   72000
2   E003   Mike         IT   85000
3   E003   Mike         IT   87000
4   E004   Anna         HR   68000
5   E005    Tom      Sales   69000

##### 2. **Concatenate Columns (Horizontal)**

In [ ]:
all_emp_h = pd.concat([employees1, employees2], axis=1)
all_emp_h

  emp_id   name department  salary emp_id  name department  salary
0   E001   John      Sales   65000   E003  Mike         IT   87000
1   E002  Sarah  Marketing   72000   E004  Anna         HR   68000
2   E003   Mike         IT   85000   E005   Tom      Sales   69000

##### 3. **Concatenate DataFrames with Different Columns**

In [ ]:
pd.concat([employees,customers])

   emp_id emp_name  manager_id  customer_id     name      city   age
0     1.0    Alice         NaN          NaN      NaN       NaN   NaN
1     2.0      Bob         1.0          NaN      NaN       NaN   NaN
2     3.0  Charlie         1.0          NaN      NaN       NaN   NaN
3     4.0    David         2.0          NaN      NaN       NaN   NaN
0     NaN      NaN         NaN        101.0    Alice  New York  28.0
1     NaN      NaN         NaN        102.0      Bob    London  35.0
2     NaN      NaN         NaN        103.0  Charlie     Paris  42.0
3     NaN      NaN         NaN        104.0    David     Tokyo  31.0
4     NaN      NaN         NaN        105.0      Eva    Berlin  29.0

##### 4. **Add Keys to Identify Source DataFrame**

In [ ]:
result9 = pd.concat([employees1, employees2], keys=['Team_A', 'Team_B'])
result9

         emp_id   name department  salary
Team_A 0   E001   John      Sales   65000
       1   E002  Sarah  Marketing   72000
       2   E003   Mike         IT   85000
Team_B 0   E003   Mike         IT   87000
       1   E004   Anna         HR   68000
       2   E005    Tom      Sales   69000