### **Pivot Tables**
A pivot table summarizes and aggregates data, similar to Excel's PivotTable.

**Syntax:**
```python
pd.pivot_table(
    data=df,              # DataFrame to summarize
    values='Sales',       # Column to aggregate
    index='Region',       # Row groups
    columns='Category',   # Column groups
    aggfunc='sum',        # Aggregate using sum
    fill_value=0,         # Replace NaN with 0
    margins=True          # Add grand totals
)
```

**Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
<th>Default</th>
</tr>
<tr>
<td><i>data</i></td>
<td>The DataFrame to summarize.</td>
<td>Required</td>
</tr>
<tr>
<td><i>values</i></td>
<td>Column(s) to aggregate. Can be a string or list of column names.</td>
<td>None</td>
</tr>
<tr>
<td><i>index</i></td>
<td>Column(s) to use as row labels. Can be a string or list.</td>
<td>None</td>
</tr>
<tr>
<td><i>columns</i></td>
<td>Column(s) to use as column labels. Can be a string or list.</td>
<td>None</td>
</tr>
<tr>
<td><i>aggfunc</i></td>
<td>Aggregation function(s) to apply (e.g., 'mean', 'sum', 'count').</td>
<td>'mean'</td>
</tr>
<tr>
<td><i>fill_value</i></td>
<td>Value to replace missing (NaN) values in the result.</td>
<td>None</td>
</tr>
<tr>
<td><i>margins</i></td>
<td>Adds row/column totals (All).</td>
<td>False</td>
</tr>
<tr>
<td><i>dropna</i></td>
<td>If True, excludes columns whose entries are all NaN.</td>
<td>True</td>
</tr>
<tr>
<td><i>margins_name</i></td>
<td>Name for the totals row/column when margins=True.</td>
<td>'All'</td>
</tr>
<tr>
<td><i>observed</i></td>
<td>For categorical groupers, if True, shows only observed category combinations.</td>
<td>True (in recent pandas versions)</td>
</tr>
<tr>
<td><i>sort</i></td>
<td>Sorts the resulting index and columns.</td>
<td>True</td>
</tr>
</table>

In [10]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Sales.csv')
df

,Order_ID,Region,Category,Product,Salesperson,Quantity,Sales,Year
0,1001,East,Electronics,Laptop,Alice,2,1200,2023
1,1002,West,Furniture,Chair,Bob,5,700,2023
2,1003,North,Clothing,Shirt,Charlie,8,450,2023
3,1004,South,Electronics,Mobile,David,3,950,2023
4,1005,East,Furniture,Table,Emma,4,800,2023
5,1006,West,Clothing,Jeans,Frank,7,650,2023
6,1007,North,Electronics,Tablet,Alice,2,1100,2023
7,1008,South,Furniture,Sofa,Bob,6,1500,2023
8,1009,East,Clothing,Jacket,Charlie,9,900,2023
9,1010,West,Electronics,Headphones,David,5,1300,2023
10,1011,North,Furniture,Desk,Emma,3,600,2024
11,1012,South,Clothing,T-Shirt,Frank,8,500,2024
12,1013,East,Electronics,Laptop,Alice,1,1250,2024
13,1014,West,Furniture,Chair,Bob,4,720,2024
14,1015,North,Clothing,Shirt,Charlie,6,480,2024
15,1016,South,Electronics,Mobile,David,2,980,2024
16,1017,East,Furniture,Table,Emma,5,850,2024
17,1018,West,Clothing,Jeans,Frank,9,690,2024
18,1019,North,Electronics,Tablet,Alice,3,1120,2024
19,1020,South,Furniture,Sofa,Bob,7,1550,2024
20,1021,East,Clothing,Jacket,Charlie,8,940,2025
21,1022,West,Electronics,Headphones,David,4,1270,2025
22,1023,North,Furniture,Desk,Emma,2,610,2025
23,1024,South,Clothing,T-Shirt,Frank,6,530,2025
24,1025,East,Electronics,Laptop,Alice,3,1180,2025
25,1026,West,Furniture,Chair,Bob,5,710,2025
26,1027,North,Clothing,Shirt,Charlie,7,460,2025
27,1028,South,Electronics,Mobile,David,1,970,2025
28,1029,East,Furniture,Table,Emma,4,830,2025
29,1030,West,Clothing,Jeans,Frank,8,675,2025
30,1031,North,Electronics,Tablet,Alice,2,1150,2026
31,1032,South,Furniture,Sofa,Bob,6,1490,2026
32,1033,East,Clothing,Jacket,Charlie,9,910,2026
33,1034,West,Electronics,Headphones,David,5,1320,2026
34,1035,North,Furniture,Desk,Emma,3,620,2026
35,1036,South,Clothing,T-Shirt,Frank,7,520,2026
36,1037,East,Electronics,Laptop,Alice,2,1210,2026
37,1038,West,Furniture,Chair,Bob,4,730,2026
38,1039,North,Clothing,Shirt,Charlie,8,470,2026
39,1040,South,Electronics,Mobile,David,3,990,2026

#### 1. **Simple Pivot Table**

Average sales by region:

In [11]:
pivot_table1 = pd.pivot_table(
    df,
    index='Region',
    values='Sales'
)
pivot_table1

         Sales
Region
East    1007.0
North    706.0
South    998.0
West     876.5

Since no aggfunc is specified, pandas calculates the mean (average) Sales for each Region.

#### 2. **Rows and Columns**

Sales by region and product:

In [12]:
pivot_table2 = pd.pivot_table(
    df,
    index='Region',
    columns='Category',
    values='Sales'
)
pivot_table2

Category    Clothing  Electronics    Furniture
Region
East      916.666667  1210.000000   826.666667
North     465.000000  1123.333333   610.000000
South     516.666667   972.500000  1513.333333
West      671.666667  1296.666667   715.000000

#### 3. **Different Aggregations**

Sum sales instead of mean:

In [13]:
pivot_table3 = pd.pivot_table(
    df,
    index='Region',
    columns='Category',
    values='Sales',
    aggfunc='sum'
)
pivot_table3

Category  Clothing  Electronics  Furniture
Region
East          2750         4840       2480
North         1860         3370       1830
South         1550         3890       4540
West          2015         3890       2860

Multiple aggregations:

In [14]:
pivot_table4 = pd.pivot_table(
    df,
    index='Region',
    columns='Category',
    values='Sales',
    aggfunc=['sum', 'mean']
)
pivot_table4

              sum                              mean
Category Clothing Electronics Furniture    Clothing  Electronics    Furniture
Region
East         2750        4840      2480  916.666667  1210.000000   826.666667
North        1860        3370      1830  465.000000  1123.333333   610.000000
South        1550        3890      4540  516.666667   972.500000  1513.333333
West         2015        3890      2860  671.666667  1296.666667   715.000000

#### 4. **Add Totals**

In [15]:
pivot_table5 = pd.pivot_table(
    df,
    index='Region',
    columns='Category',
    values='Sales',
    aggfunc='sum',
    margins=True
)
pivot_table5

Category  Clothing  Electronics  Furniture    All
Region
East          2750         4840       2480  10070
North         1860         3370       1830   7060
South         1550         3890       4540   9980
West          2015         3890       2860   8765
All           8175        15990      11710  35875

#### 5. **Multiple Index Levels**

In [16]:
pivot_table6 = pd.pivot_table(
    df,
    index=['Region', 'Category'],
    values='Sales',
    aggfunc='sum',
    margins=True
)
pivot_table6

                    Sales
Region Category
East   Clothing      2750
       Electronics   4840
       Furniture     2480
North  Clothing      1860
       Electronics   3370
       Furniture     1830
South  Clothing      1550
       Electronics   3890
       Furniture     4540
West   Clothing      2015
       Electronics   3890
       Furniture     2860
All                 35875

#### 6. **Fill Missing Values**

**without fill_value**

In [17]:
pivot_table8 = pd.pivot_table(
    df,
    index=['Region', 'Category'],
    columns='Product',
    values='Sales',
    aggfunc='sum'
    
)
pivot_table8

Product              Chair    Desk  Headphones  Jacket   Jeans  Laptop  \
Region Category
East   Clothing        NaN     NaN         NaN  2750.0     NaN     NaN
       Electronics     NaN     NaN         NaN     NaN     NaN  4840.0
       Furniture       NaN     NaN         NaN     NaN     NaN     NaN
North  Clothing        NaN     NaN         NaN     NaN     NaN     NaN
       Electronics     NaN     NaN         NaN     NaN     NaN     NaN
       Furniture       NaN  1830.0         NaN     NaN     NaN     NaN
South  Clothing        NaN     NaN         NaN     NaN     NaN     NaN
       Electronics     NaN     NaN         NaN     NaN     NaN     NaN
       Furniture       NaN     NaN         NaN     NaN     NaN     NaN
West   Clothing        NaN     NaN         NaN     NaN  2015.0     NaN
       Electronics     NaN     NaN      3890.0     NaN     NaN     NaN
       Furniture    2860.0     NaN         NaN     NaN     NaN     NaN

Product             Mobile   Shirt    Sofa  T-Shirt   Table  Tablet
Region Category
East   Clothing        NaN     NaN     NaN      NaN     NaN     NaN
       Electronics     NaN     NaN     NaN      NaN     NaN     NaN
       Furniture       NaN     NaN     NaN      NaN  2480.0     NaN
North  Clothing        NaN  1860.0     NaN      NaN     NaN     NaN
       Electronics     NaN     NaN     NaN      NaN     NaN  3370.0
       Furniture       NaN     NaN     NaN      NaN     NaN     NaN
South  Clothing        NaN     NaN     NaN   1550.0     NaN     NaN
       Electronics  3890.0     NaN     NaN      NaN     NaN     NaN
       Furniture       NaN     NaN  4540.0      NaN     NaN     NaN
West   Clothing        NaN     NaN     NaN      NaN     NaN     NaN
       Electronics     NaN     NaN     NaN      NaN     NaN     NaN
       Furniture       NaN     NaN     NaN      NaN     NaN     NaN

**with fill_value**

In [18]:
pivot_table9 = pd.pivot_table(
    df,
    index=['Region', 'Category'],
    columns='Product',
    values='Sales',
    aggfunc='sum',
    fill_value=0,
    margins=True,
    margins_name='Total'
)
pivot_table9

Product             Chair  Desk  Headphones  Jacket  Jeans  Laptop  Mobile  \
Region Category
East   Clothing         0     0           0    2750      0       0       0
       Electronics      0     0           0       0      0    4840       0
       Furniture        0     0           0       0      0       0       0
North  Clothing         0     0           0       0      0       0       0
       Electronics      0     0           0       0      0       0       0
       Furniture        0  1830           0       0      0       0       0
South  Clothing         0     0           0       0      0       0       0
       Electronics      0     0           0       0      0       0    3890
       Furniture        0     0           0       0      0       0       0
West   Clothing         0     0           0       0   2015       0       0
       Electronics      0     0        3890       0      0       0       0
       Furniture     2860     0           0       0      0       0       0
Total                2860  1830        3890    2750   2015    4840    3890

Product             Shirt  Sofa  T-Shirt  Table  Tablet  Total
Region Category
East   Clothing         0     0        0      0       0   2750
       Electronics      0     0        0      0       0   4840
       Furniture        0     0        0   2480       0   2480
North  Clothing      1860     0        0      0       0   1860
       Electronics      0     0        0      0    3370   3370
       Furniture        0     0        0      0       0   1830
South  Clothing         0     0     1550      0       0   1550
       Electronics      0     0        0      0       0   3890
       Furniture        0  4540        0      0       0   4540
West   Clothing         0     0        0      0       0   2015
       Electronics      0     0        0      0       0   3890
       Furniture        0     0        0      0       0   2860
Total                1860  4540     1550   2480    3370  35875