### **Reshaping Data**

Reshaping Data means changing the structure or layout of a DataFrame without changing the actual data. It helps you organize data into a format that's easier to analyze or visualize.

Some of the most commonly used reshaping methods in Pandas include:

- *pivot()*
- *pivot_table()*
- *melt()*
- *stack()*
- *unstack()*
- *explode()*
- *transpose() (.T)*
- *set_index()*
- *reset_index()*
- *wide_to_long()*

#### 1. **Pivot()**

pivot() reshapes a DataFrame by turning unique values form one column into new columns.

- Convert rows into columns.
- Does not perform aggregation.
- Requires unique values.

**Syntax:**
```python
DataFrame.pivot( 
    data=df,
    index=None, 
    columns=None, 
    values=None
)
```

**Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
</tr>
<tr>
<td><i>data</i></td>
<td>DataFrame to summarize</td>
</tr>
<tr>
<td><i>index</i></td>
<td>Column to use as the row index.</td>
</tr>
<tr>
<td><i>columns</i></td>
<td>Column whose unique values become new column names.</td>
</tr>
<tr>
<td><i>values</i></td>
<td>Column whose values fill the new table.</td>
</tr>
</table>

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Date": ["2025-01-01", "2025-01-01", "2025-01-02", "2025-01-02"],
    "Product": ["Laptop", "Phone", "Laptop", "Phone"],
    "Sales": [50000, 20000, 60000, 25000]
})

print(df)

         Date Product  Sales
0  2025-01-01  Laptop  50000
1  2025-01-01   Phone  20000
2  2025-01-02  Laptop  60000
3  2025-01-02   Phone  25000

In [2]:

pivot_1 = pd.pivot(
    df,
    index='Date',
    columns='Product',
    values='Sales'

)
pivot_1

Product     Laptop  Phone
Date
2025-01-01   50000  20000
2025-01-02   60000  25000

#### 2. **Pivot Tables**
A pivot table summarizes and aggregates data, similar to Excel's PivotTable.

- Similar to *pivot()*, but supports aggregation.
- Can handle duplicate values.

**Syntax:**
```python
pd.pivot_table(
    data=df,              # DataFrame to summarize
    values='Sales',       # Column to aggregate
    index='Region',       # Row groups
    columns='Category',   # Column groups
    aggfunc='sum',        # Aggregate using sum
    fill_value=0,         # Replace NaN with 0
    margins=True          # Add grand totals
)

In [3]:
sales = pd.read_csv(r'sample_datasets\Sales.csv')
sales

,Order_ID,Region,Category,Product,Salesperson,Quantity,Sales,Year
0,1001,East,Electronics,Laptop,Alice,2,1200,2023
1,1002,West,Furniture,Chair,Bob,5,700,2023
2,1003,North,Clothing,Shirt,Charlie,8,450,2023
3,1004,South,Electronics,Mobile,David,3,950,2023
4,1005,East,Furniture,Table,Emma,4,800,2023
5,1006,West,Clothing,Jeans,Frank,7,650,2023
6,1007,North,Electronics,Tablet,Alice,2,1100,2023
7,1008,South,Furniture,Sofa,Bob,6,1500,2023
8,1009,East,Clothing,Jacket,Charlie,9,900,2023
9,1010,West,Electronics,Headphones,David,5,1300,2023
10,1011,North,Furniture,Desk,Emma,3,600,2024
11,1012,South,Clothing,T-Shirt,Frank,8,500,2024
12,1013,East,Electronics,Laptop,Alice,1,1250,2024
13,1014,West,Furniture,Chair,Bob,4,720,2024
14,1015,North,Clothing,Shirt,Charlie,6,480,2024
15,1016,South,Electronics,Mobile,David,2,980,2024
16,1017,East,Furniture,Table,Emma,5,850,2024
17,1018,West,Clothing,Jeans,Frank,9,690,2024
18,1019,North,Electronics,Tablet,Alice,3,1120,2024
19,1020,South,Furniture,Sofa,Bob,7,1550,2024
20,1021,East,Clothing,Jacket,Charlie,8,940,2025
21,1022,West,Electronics,Headphones,David,4,1270,2025
22,1023,North,Furniture,Desk,Emma,2,610,2025
23,1024,South,Clothing,T-Shirt,Frank,6,530,2025
24,1025,East,Electronics,Laptop,Alice,3,1180,2025
25,1026,West,Furniture,Chair,Bob,5,710,2025
26,1027,North,Clothing,Shirt,Charlie,7,460,2025
27,1028,South,Electronics,Mobile,David,1,970,2025
28,1029,East,Furniture,Table,Emma,4,830,2025
29,1030,West,Clothing,Jeans,Frank,8,675,2025
30,1031,North,Electronics,Tablet,Alice,2,1150,2026
31,1032,South,Furniture,Sofa,Bob,6,1490,2026
32,1033,East,Clothing,Jacket,Charlie,9,910,2026
33,1034,West,Electronics,Headphones,David,5,1320,2026
34,1035,North,Furniture,Desk,Emma,3,620,2026
35,1036,South,Clothing,T-Shirt,Frank,7,520,2026
36,1037,East,Electronics,Laptop,Alice,2,1210,2026
37,1038,West,Furniture,Chair,Bob,4,730,2026
38,1039,North,Clothing,Shirt,Charlie,8,470,2026
39,1040,South,Electronics,Mobile,David,3,990,2026

In [4]:
pivot_table1 = pd.pivot_table(
    sales,
    index='Year',
    columns= ['Category', 'Product'],
    values='Sales',
    aggfunc='sum',
    fill_value=0,
    margins=True,
    margins_name='Total'
)
pivot_table1

Category Clothing                     Electronics                       \
Product    Jacket Jeans Shirt T-Shirt  Headphones Laptop Mobile Tablet
Year
2023          900   650   450       0        1300   1200    950   1100
2024            0   690   480     500           0   1250    980   1120
2025          940   675   460     530        1270   1180    970      0
2026          910     0   470     520        1320   1210    990   1150
Total        2750  2015  1860    1550        3890   4840   3890   3370

Category Furniture                    Total
Product      Chair  Desk  Sofa Table
Year
2023           700     0  1500   800   9550
2024           720   600  1550   850   8740
2025           710   610     0   830   8175
2026           730   620  1490     0   9410
Total         2860  1830  4540  2480  35875

#### 3. **melt()**

melt() converts multiple columns into rows, producing a long-format DataFrame

*pandas.melt()* is used to unpivot a DataFrame from a wide format to a long format.

**Syntax:**
```python
pd.melt(
    frame,
    id_vars=None,
    value_vars=None,
    var_name=None,
    value_name='value'
)
```
**Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>What it does</th>
<th>Default</th>
</tr>
<tr>
<td><i>frame</i></td>
<td>The DataFrame to reshape</td>
<td>Required</td>
</tr>
<tr>
<td><i>id_vars</i></td>
<td>Columns to keep unchanged (identifiers)</td>
<td>None</td>
</tr>
<tr>
<td><i>value_vars</i></td>
<td>Columns to convert into rows</td>
<td>All columns except id_vars</td>
</tr>
<tr>
<td><i>var_name</i></td>
<td>Name of the new column holding original column names</td>
<td>"variable"</td>
</tr>
<tr>
<td><i>value_name</i></td>
<td>Name of the new column holding values</td>
<td>"value"</td>
</tr>
<tr>
<td><i>ignore_index</i></td>
<td>Whether to reset the index (True) or keep the original index (False)</td>
<td>True</td>
</tr>
</table>

In [5]:
students = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank'],
    'Class': ['10A', '10A', '10B', '10B', '10A', '10B'],
    'Math': [85, 78, 92, 88, 95, 81],
    'Science': [90, 82, 89, 91, 96, 85],
    'English': [88, 80, 94, 86, 92, 83],
    'Computer': [95, 84, 97, 90, 99, 88]
})

students

   Student_ID     Name Class  Math  Science  English  Computer
0         101    Alice   10A    85       90       88        95
1         102      Bob   10A    78       82       80        84
2         103  Charlie   10B    92       89       94        97
3         104    David   10B    88       91       86        90
4         105     Emma   10A    95       96       92        99
5         106    Frank   10B    81       85       83        88

**Example 1: Keep only Name as identifier**

Since only Name is an identifier, every other column is melted, including:

- Student_ID
- Class
- Math
- Science
- English
- Computer

In [6]:
unpivot_stu1 = pd.melt(
    students,
    id_vars='Name'
)
unpivot_stu1

       Name    variable value
0     Alice  Student_ID   101
1       Bob  Student_ID   102
2   Charlie  Student_ID   103
3     David  Student_ID   104
4      Emma  Student_ID   105
5     Frank  Student_ID   106
6     Alice       Class   10A
7       Bob       Class   10A
8   Charlie       Class   10B
9     David       Class   10B
10     Emma       Class   10A
11    Frank       Class   10B
12    Alice        Math    85
13      Bob        Math    78
14  Charlie        Math    92
15    David        Math    88
16     Emma        Math    95
17    Frank        Math    81
18    Alice     Science    90
19      Bob     Science    82
20  Charlie     Science    89
21    David     Science    91
22     Emma     Science    96
23    Frank     Science    85
24    Alice     English    88
25      Bob     English    80
26  Charlie     English    94
27    David     English    86
28     Emma     English    92
29    Frank     English    83
30    Alice    Computer    95
31      Bob    Computer    84
32  Charlie    Computer    97
33    David    Computer    90
34     Emma    Computer    99
35    Frank    Computer    88

**Example 2: Melt only Math and Science**

In [7]:
unpivot_stu2 = pd.melt(
    students,
    id_vars=['Student_ID', 'Name'],
    value_vars=['Math', 'Science'],
    var_name='Subject',
    value_name='Marks'
)
unpivot_stu2

    Student_ID     Name  Subject  Marks
0          101    Alice     Math     85
1          102      Bob     Math     78
2          103  Charlie     Math     92
3          104    David     Math     88
4          105     Emma     Math     95
5          106    Frank     Math     81
6          101    Alice  Science     90
7          102      Bob  Science     82
8          103  Charlie  Science     89
9          104    David  Science     91
10         105     Emma  Science     96
11         106    Frank  Science     85

**Example 3: Melt all subject columns**

In [8]:
unpivot_stu3 = pd.melt(
    students,
    id_vars=['Student_ID', 'Name', 'Class'],
    var_name='Subject',
    value_name='Marks'
)
    # you didn't specify value_vars, so pandas uses its default behavior.
    #If value_vars=None (the default), pandas automatically selects all columns that are NOT in id_vars
unpivot_stu3

    Student_ID     Name Class   Subject  Marks
0          101    Alice   10A      Math     85
1          102      Bob   10A      Math     78
2          103  Charlie   10B      Math     92
3          104    David   10B      Math     88
4          105     Emma   10A      Math     95
5          106    Frank   10B      Math     81
6          101    Alice   10A   Science     90
7          102      Bob   10A   Science     82
8          103  Charlie   10B   Science     89
9          104    David   10B   Science     91
10         105     Emma   10A   Science     96
11         106    Frank   10B   Science     85
12         101    Alice   10A   English     88
13         102      Bob   10A   English     80
14         103  Charlie   10B   English     94
15         104    David   10B   English     86
16         105     Emma   10A   English     92
17         106    Frank   10B   English     83
18         101    Alice   10A  Computer     95
19         102      Bob   10A  Computer     84
20         103  Charlie   10B  Computer     97
21         104    David   10B  Computer     90
22         105     Emma   10A  Computer     99
23         106    Frank   10B  Computer     88

#### 4. **Stack()**

*stack()* is a reshaping method in pandas that moves one or more column levels into the row index.

**Syntax:**
```python
DataFrame.stack(level=-1, future_stack=True)
```
**Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
<th>Default</th>
</tr>
<tr>
<td><i>level</i></td>
<td>Column level(s) to stack (for MultiIndex columns)</td>
<td>-1</td>
</tr>
<tr>
<td><i>future_stack</i></td>
<td>Uses the newer implementation</td>
<td>True</td>
</tr>
</table>

In [9]:
df = pd.DataFrame({
    'Math': [90, 80, 70, 85],
    'Science': [85, 88, 73, 80]
},
index=['Alice', 'Bob', 'Charlie', 'David'])

print(df)
df.index

         Math  Science
Alice      90       85
Bob        80       88
Charlie    70       73
David      85       80

Index(['Alice', 'Bob', 'Charlie', 'David'], dtype='str')

In [10]:
stacked1 = df.stack()
print(stacked1)
print(stacked1.index),
print(type(stacked1))

Alice    Math       90
         Science    85
Bob      Math       80
         Science    88
Charlie  Math       70
         Science    73
David    Math       85
         Science    80
dtype: int64
MultiIndex([(  'Alice',    'Math'),
            (  'Alice', 'Science'),
            (    'Bob',    'Math'),
            (    'Bob', 'Science'),
            ('Charlie',    'Math'),
            ('Charlie', 'Science'),
            (  'David',    'Math'),
            (  'David', 'Science')],
           )
<class 'pandas.Series'>

**Example with Missing Values**

In [11]:
df = pd.DataFrame({
    'Math': [90, None, 70, 85],
    'Science': [85, 88, None, 80]
},
index=['Alice', 'Bob', 'Charlie', 'David'])
df

         Math  Science
Alice    90.0     85.0
Bob       NaN     88.0
Charlie  70.0      NaN
David    85.0     80.0

Stack (By Default Stack keeps missing values)

In [12]:
stacked2 = df.stack()
stacked2

Alice    Math       90.0
         Science    85.0
Bob      Math        NaN
         Science    88.0
Charlie  Math       70.0
         Science     NaN
David    Math       85.0
         Science    80.0
dtype: float64

Removing missng values

In [13]:
stacked3 = df.stack().dropna()
stacked3

Alice    Math       90.0
         Science    85.0
Bob      Science    88.0
Charlie  Math       70.0
David    Math       85.0
         Science    80.0
dtype: float64

**Example with MultiIndex Columns**

In [14]:
arrays = [
    ['Marks', 'Marks', 'Grade', 'Grade'],
    ['Math', 'Science', 'Math', 'Science']
]

columns = pd.MultiIndex.from_arrays(arrays)
df = pd.DataFrame([
    [90, 85, 'A', 'B'],
    [80, 88, 'B', 'A']
], index=['Alice', 'Bob'], columns=columns)
df

      Marks         Grade
       Math Science  Math Science
Alice    90      85     A       B
Bob      80      88     B       A

**The columns now have 2 levels.**

**Level 0**
- Marks
- Marks
- Grade
- Grade

**Level 1 or (-1)**
- Math
- Science
- Math
- Science

**Stack the last column level (default)**

In [15]:
print(df.stack())
stacked4 = df.stack(level=-1)
stacked4

               Marks Grade
Alice Math        90     A
      Science     85     B
Bob   Math        80     B
      Science     88     A

               Marks Grade
Alice Math        90     A
      Science     85     B
Bob   Math        80     B
      Science     88     A

**Stack column level 0**

In [16]:
stacked5 = df.stack(level=0)
stacked5

            Math Science
Alice Marks   90      85
      Grade    A       B
Bob   Marks   80      88
      Grade    B       A

**Stack both column levels**

In [17]:
stacked6 = df.stack(level=[0,1])
stacked6

Alice  Marks  Math       90
              Science    85
       Grade  Math        A
              Science     B
Bob    Marks  Math       80
              Science    88
       Grade  Math        B
              Science     A
dtype: object

#### 4. **unstack()**

*unstack()* does the opposite to *stack()*.

It converts an index level into columns.

**Example 1 — Basic unstack()**

In [18]:
print(stacked6)
unstacked1 = stacked6.unstack()
unstacked1

Alice  Marks  Math       90
              Science    85
       Grade  Math        A
              Science     B
Bob    Marks  Math       80
              Science    88
       Grade  Math        B
              Science     A
dtype: object

            Math Science
Alice Grade    A       B
      Marks   90      85
Bob   Grade    B       A
      Marks   80      88

**Unstack by level number**

From this, you can tell:


Level 0

- Student (Alice, Bob)

Level 1

- Type (Marks, Grade)

Level 2 

-Subject (Math, Science)

**Move the last level (Subject)**

In [19]:
print(stacked6)
unstacked2 = stacked6.unstack(-1)
unstacked2

Alice  Marks  Math       90
              Science    85
       Grade  Math        A
              Science     B
Bob    Marks  Math       80
              Science    88
       Grade  Math        B
              Science     A
dtype: object

            Math Science
Alice Grade    A       B
      Marks   90      85
Bob   Grade    B       A
      Marks   80      88

**Move the second level (Type)**

In [20]:
unstacked3 = stacked6.unstack(level=1)
unstacked3

              Grade Marks
Alice Math        A    90
      Science     B    85
Bob   Math        B    80
      Science     A    88

**Move the first level (Student)**

In [21]:
unstacked4 = stacked6.unstack(level=0)
unstacked4

              Alice Bob
Grade Math        A   B
      Science     B   A
Marks Math       90  80
      Science    85  88

**Move last two levels(Subject/Type)**

In [22]:
unstacked5 = stacked6.unstack(level=[1,2])
unstacked5

      Marks         Grade
       Math Science  Math Science
Alice    90      85     A       B
Bob      80      88     B       A

#### 5. **explode()**

*explode()* is a Pandas method used to split list-like values in a column into multiple rows.

It is very useful when a single cell contains multiple values (like a list) and you want one value per row.


**Syntax:**
```python
df.explode(column, ignore_index=False)
```

**Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
</tr>
<tr>
<td><i>column</i></td>
<td>Column name (or list of column names) to explode.</td>
</tr>
<tr>
<td><i>ignore_index</i></td>
<td>If True, creates a new index (0,1,2...). Default is False.</td>
</tr>
</table>

**Sample Datasets to practice *explode()***

In [23]:
students1 = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'Charlie'],
    'Subjects': [
        ['Math', 'Science'],
        ['English'],
        ['Physics', 'Chemistry', 'Biology']
    ]
})

orders = pd.DataFrame({
    'Order_ID': [101, 102, 103],
    'Products': [
        ['Laptop', 'Mouse'],
        ['Keyboard'],
        ['Monitor', 'Webcam', 'Speaker']
    ]
})

post = pd.DataFrame({
    'Post': ['P1', 'P2'],
    'Tags': [
        ['Python', 'Pandas', 'Data'],
        ['SQL', 'MySQL']
    ]
})
print(students1)
print()
print(orders)
print()
print(post)

   Student                       Subjects
0    Alice                [Math, Science]
1      Bob                      [English]
2  Charlie  [Physics, Chemistry, Biology]

   Order_ID                    Products
0       101             [Laptop, Mouse]
1       102                  [Keyboard]
2       103  [Monitor, Webcam, Speaker]

  Post                    Tags
0   P1  [Python, Pandas, Data]
1   P2            [SQL, MySQL]

**Exploding One Column**

In [24]:
print(post)
post.explode('Tags')

  Post                    Tags
0   P1  [Python, Pandas, Data]
1   P2            [SQL, MySQL]

  Post    Tags
0   P1  Python
0   P1  Pandas
0   P1    Data
1   P2     SQL
1   P2   MySQL

In [25]:
print(orders)
orders.explode('Products')

   Order_ID                    Products
0       101             [Laptop, Mouse]
1       102                  [Keyboard]
2       103  [Monitor, Webcam, Speaker]

   Order_ID  Products
0       101    Laptop
0       101     Mouse
1       102  Keyboard
2       103   Monitor
2       103    Webcam
2       103   Speaker

In [26]:
print(students1)
students1.explode('Subjects')

   Student                       Subjects
0    Alice                [Math, Science]
1      Bob                      [English]
2  Charlie  [Physics, Chemistry, Biology]

   Student   Subjects
0    Alice       Math
0    Alice    Science
1      Bob    English
2  Charlie    Physics
2  Charlie  Chemistry
2  Charlie    Biology

Notice:

- Alice appears twice.
- Charlie appears three times.
- The index is repeated.

**Reset the Index**

In [27]:
students1.explode('Subjects', ignore_index=True)

   Student   Subjects
0    Alice       Math
1    Alice    Science
2      Bob    English
3  Charlie    Physics
4  Charlie  Chemistry
5  Charlie    Biology

In [28]:
orders.explode('Products', ignore_index=True)

   Order_ID  Products
0       101    Laptop
1       101     Mouse
2       102  Keyboard
3       103   Monitor
4       103    Webcam
5       103   Speaker

In [29]:
post.explode('Tags', ignore_index=True)

  Post    Tags
0   P1  Python
1   P1  Pandas
2   P1    Data
3   P2     SQL
4   P2   MySQL

**Exploding Multiple Columns**

If two columns contain lists of the same length, you can explode them together.

In [30]:
students2 = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Subject': [
        ['Math', 'Science'],
        ['English', 'History']
    ],
    'Marks': [
        [90, 85],
        [88, 92]
    ]
})
students2

    Name             Subject     Marks
0  Alice     [Math, Science]  [90, 85]
1    Bob  [English, History]  [88, 92]

In [31]:
students2.explode(['Subject', 'Marks'], ignore_index=True)

    Name  Subject Marks
0  Alice     Math    90
1  Alice  Science    85
2    Bob  English    88
3    Bob  History    92

> **Important:** When exploding multiple columns, the lists in each row must have the same length.