### **Apply Functions in Pandas**

*map()*, *apply()*, and *applymap()* are all used to transform data in pandas, but they work on different objects.

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Method</th>
<th>Works on</th>
<th>Purpose</th>
</tr>
<tr>
<td><i>map()</i></td>
<td>Single Series (one column)</td>
<td>Replace or transform values one by one</td>
</tr>
<tr>
<td><i>apply()</i></td>
<td>Series or DataFrame</td>
<td>Apply a function to rows, columns, or a Series</td>
</tr>
<tr>
<td><i>applymap()</i></td>
<td>Entire DataFrame</td>
<td>Apply a function to every individual cell (deprecated in recent pandas versions; use DataFrame.map() instead if available)</td>
</tr>
</table>

In [1]:
import pandas as pd
df = pd.read_csv(r'sample_datasets\Students.csv')
df.head()

,Student_ID,Name,Gender,Department,Year,Math,Science,English,City
0,1001,Krishna,M,CSE,2,67,67,92,Vijayawada
1,1002,Meera,F,MECH,1,43,67,54,Vijayawada
2,1003,Keerthi,F,CSE,4,77,95,95,Pune
3,1004,Priya,F,CSE,4,82,85,73,Chennai
4,1005,Rahul,M,ECE,4,73,77,35,Vijayawada

#### 1. ***map()***

Works only on a Series (single column).

**Syntax**
```python
Series.map(arg)
```

**arg can be:**

- Dictionary
- Function
- Series

**Example 1: Dictionary Mapping**(Add State from city)

In [2]:
state_code = {
    'Vijayawada': 'AP',
    'Visakhapatnam': 'AP',
    'Pune': 'MH',
    'Delhi':'DH',
    'Chennai':'TN',
    'Mumbai':'MH',
    'Bengaluru':'KA',
    'Hyderabad': 'TS'
}
df['State_code'] = df['City'].map(state_code)
df.head()

,Student_ID,Name,Gender,Department,Year,Math,Science,English,City,State_code
0,1001,Krishna,M,CSE,2,67,67,92,Vijayawada,AP
1,1002,Meera,F,MECH,1,43,67,54,Vijayawada,AP
2,1003,Keerthi,F,CSE,4,77,95,95,Pune,MH
3,1004,Priya,F,CSE,4,82,85,73,Chennai,TN
4,1005,Rahul,M,ECE,4,73,77,35,Vijayawada,AP

**Example 2: Convert Gender to short form**

In [3]:
df['Gender'] = df['Gender'].map({
    'M': 'Male',
    'F':'Female'
})
df

,Student_ID,Name,Gender,Department,Year,Math,Science,English,City,State_code
0,1001,Krishna,Male,CSE,2,67,67,92,Vijayawada,AP
1,1002,Meera,Female,MECH,1,43,67,54,Vijayawada,AP
2,1003,Keerthi,Female,CSE,4,77,95,95,Pune,MH
3,1004,Priya,Female,CSE,4,82,85,73,Chennai,TN
4,1005,Rahul,Male,ECE,4,73,77,35,Vijayawada,AP
...,...,...,...,...,...,...,...,...,...,...
95,1096,Sneha,Female,CSE,3,66,73,73,Chennai,TN
96,1097,Vivaan,Male,MECH,2,58,53,60,Mumbai,MH
97,1098,Aarav,Male,CSE,2,46,73,68,Vijayawada,AP
98,1099,Divya,Female,MECH,2,84,79,88,Pune,MH
99,1100,Arjun,Female,CSE,1,69,47,37,Pune,MH

**Example 3: String Length**

In [4]:
df['Name_Len'] = df['Name'].map(lambda x : len(x))
df

,Student_ID,Name,Gender,Department,Year,Math,Science,English,City,State_code,Name_Len
0,1001,Krishna,Male,CSE,2,67,67,92,Vijayawada,AP,7
1,1002,Meera,Female,MECH,1,43,67,54,Vijayawada,AP,5
2,1003,Keerthi,Female,CSE,4,77,95,95,Pune,MH,7
3,1004,Priya,Female,CSE,4,82,85,73,Chennai,TN,5
4,1005,Rahul,Male,ECE,4,73,77,35,Vijayawada,AP,5
...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Sneha,Female,CSE,3,66,73,73,Chennai,TN,5
96,1097,Vivaan,Male,MECH,2,58,53,60,Mumbai,MH,6
97,1098,Aarav,Male,CSE,2,46,73,68,Vijayawada,AP,5
98,1099,Divya,Female,MECH,2,84,79,88,Pune,MH,5
99,1100,Arjun,Female,CSE,1,69,47,37,Pune,MH,5

**When to use map()**

- Replace values
- Create labels
- Transform one column

#### 2. ***apply()***

apply() is much more flexible.

**It Works on:**

- Series
- DataFrame

**Syntax:**
```python
Series.apply(function)
#or
DataFrame.apply(function, axis=0)

```
- axis=1 means work row by row.

- axis=0 means work column by column.

**Example 1: Calculate Total Marks**

In [5]:
df['Total'] = df[['Math', 'Science', 'English']].apply(sum, axis=1)
df[['Name', 'Math', 'Science', 'English', 'Total']].head()

      Name  Math  Science  English  Total
0  Krishna    67       67       92    226
1    Meera    43       67       54    164
2  Keerthi    77       95       95    267
3    Priya    82       85       73    240
4    Rahul    73       77       35    185

**Example 2: Grades based on total scores**

In [6]:
df['Grade'] = df['Total'].apply(
    lambda x: 'A' if x >= 270
    else 'B' if x >= 240
    else 'C'
)
df[['Name', 'Math', 'Science', 'English', 'Total', 'Grade']].head()

      Name  Math  Science  English  Total Grade
0  Krishna    67       67       92    226     C
1    Meera    43       67       54    164     C
2  Keerthi    77       95       95    267     B
3    Priya    82       85       73    240     B
4    Rahul    73       77       35    185     C

**Example 3: Highest mark in each student**

In [7]:
df['Highest'] = df[['Math', 'Science', 'English']].apply(max, axis=1)
df[['Name', 'Math','Science', 'English', 'Highest']].head()

      Name  Math  Science  English  Highest
0  Krishna    67       67       92       92
1    Meera    43       67       54       67
2  Keerthi    77       95       95       95
3    Priya    82       85       73       85
4    Rahul    73       77       35       77

**Example 4: Calculate Average**

In [8]:
df['Average'] = df[['Math', 'Science', 'English']].apply(lambda x: x.mean(), axis=1)
df[['Name', 'Math','Science', 'English', 'Average']].head()

      Name  Math  Science  English    Average
0  Krishna    67       67       92  75.333333
1    Meera    43       67       54  54.666667
2  Keerthi    77       95       95  89.000000
3    Priya    82       85       73  80.000000
4    Rahul    73       77       35  61.666667

#### 3. ***applymap()* (Element-wise)**

*applymap()* applies a function to every individual cell in a DataFrame.

> Note: In recent versions of pandas, DataFrame.applymap() is deprecated. Use DataFrame.map() for element-wise operations instead.

**Example 1: Add 10 Marks to Every Subject**

In [9]:
print(df[['Math', 'Science', 'English']].head())
df[['Math', 'Science', 'English']].map(lambda x : x + 10).head()

   Math  Science  English
0    67       67       92
1    43       67       54
2    77       95       95
3    82       85       73
4    73       77       35

   Math  Science  English
0    77       77      102
1    53       77       64
2    87      105      105
3    92       95       83
4    83       87       45

**Example 2: Multiply Every Mark by 2**

In [10]:
print(df[['Math', 'Science', 'English']].head())
df[['Math', 'Science', 'English']].map(lambda x : x * 2).head()

   Math  Science  English
0    67       67       92
1    43       67       54
2    77       95       95
3    82       85       73
4    73       77       35

   Math  Science  English
0   134      134      184
1    86      134      108
2   154      190      190
3   164      170      146
4   146      154       70

**Example 3: Convert Numbers to Strings**

In [11]:
print(df[['Math', 'Science', 'English']].head())
df[['Math', 'Science', 'English']].map(lambda x : f'{x} Marks').head()

   Math  Science  English
0    67       67       92
1    43       67       54
2    77       95       95
3    82       85       73
4    73       77       35

       Math   Science   English
0  67 Marks  67 Marks  92 Marks
1  43 Marks  67 Marks  54 Marks
2  77 Marks  95 Marks  95 Marks
3  82 Marks  85 Marks  73 Marks
4  73 Marks  77 Marks  35 Marks

Easy way to remember
- map() → One column (Series).
- apply() → Rows, columns, or a Series.
- df.map() → Every cell in a DataFrame.

In [12]:
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Department', 'Year', 'Math', 'Science',
       'English', 'City', 'State_code', 'Name_Len', 'Total', 'Grade',
       'Highest', 'Average'],
      dtype='str')