### **Remove Duplicate Rows**

*duplicated()* and *drop_duplicates()* are two closely related pandas methods used to find and remove duplicate rows.

#### 1. **duplicated()**

*duplicated()* checks whether a row is a duplicate of a previous row.

It returns a Boolean Series:

- False → First occurrence
- True → Duplicate occurrence

**Syntax:**
```python
df.duplicated(
    subset=None,
    keep='first'
)
```

**Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
</tr>
<tr>
<td><i>subset</i></td>
<td>Column(s) to check duplicates</td>
</tr>
<tr>
<td><i>keep</i></td>
<td>Which duplicate to keep ('first', 'last', False)</td>
</tr>
</table>

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'David', 'Bob'],
    'Age': [20, 21, 20, 23, 21],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai']
})

print(df)

    Name  Age     City
0  Alice   20    Delhi
1    Bob   21   Mumbai
2  Alice   20    Delhi
3  David   23  Chennai
4    Bob   21   Mumbai

##### **Find duplicate rows**

In [2]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

##### **Show only duplicate rows**

In [3]:
df[df.duplicated()]

    Name  Age    City
2  Alice   20   Delhi
4    Bob   21  Mumbai

##### **Check duplicates using one column**

In [4]:
df.duplicated(subset='Name')
# Only the Name column is checked.

0    False
1    False
2     True
3    False
4     True
dtype: bool

##### **Keep last occurrence**

By default *keep='first'*

In [5]:
df.duplicated(keep='last')

0     True
1     True
2    False
3    False
4    False
dtype: bool

##### **Mark all duplicates**

Every duplicate row is marked as True.

In [6]:
df.duplicated(keep=False)

0     True
1     True
2     True
3    False
4     True
dtype: bool

#### 2. **drop_duplicates()**

Removes duplicate rows.

Instead of returning *True/False*, it returns a new DataFrame.

**Syntax:**
```python
df.drop_duplicates(
    subset=None,
    keep='first',
    inplace=False,
    ignore_index=False
)
```

**Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
</tr>
<tr>
<td><i>subset</i></td>
<td>Columns used to identify duplicates</td>
</tr>
<tr>
<td><i>keep</i></td>
<td>'first', 'last', or False</td>
</tr>
<tr>
<td><i>inplace</i></td>
<td>Modify original DataFrame</td>
</tr>
<tr>
<td><i>ignore_index</i></td>
<td>Reset the index in the result</td>
</tr>
</table>

##### **Remove duplicates**

In [7]:
df.drop_duplicates()

    Name  Age     City
0  Alice   20    Delhi
1    Bob   21   Mumbai
3  David   23  Chennai

##### **Remove duplicates using one column**

In [8]:
df.drop_duplicates(subset='Name')

    Name  Age     City
0  Alice   20    Delhi
1    Bob   21   Mumbai
3  David   23  Chennai

##### **Keep last occurrence**

In [9]:
df.drop_duplicates(keep='last')

    Name  Age     City
2  Alice   20    Delhi
3  David   23  Chennai
4    Bob   21   Mumbai

##### **Remove all duplicates**

In [10]:
df.drop_duplicates(keep=False)

    Name  Age     City
3  David   23  Chennai

##### **Reset index**

With *ignore_index=False*

By default *ignore_index* is *False*

In [11]:
df.drop_duplicates()

    Name  Age     City
0  Alice   20    Delhi
1    Bob   21   Mumbai
3  David   23  Chennai

With *ignore_index=True*

In [12]:
df.drop_duplicates(ignore_index=True)

    Name  Age     City
0  Alice   20    Delhi
1    Bob   21   Mumbai
2  David   23  Chennai

##### **Modify the original DataFrame**

In [13]:
print(df)
df.drop_duplicates(ignore_index=True, inplace=True)
df

    Name  Age     City
0  Alice   20    Delhi
1    Bob   21   Mumbai
2  Alice   20    Delhi
3  David   23  Chennai
4    Bob   21   Mumbai

    Name  Age     City
0  Alice   20    Delhi
1    Bob   21   Mumbai
2  David   23  Chennai