### **Summary**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Method</th>
<th>Purpose</th>
</tr>
<tr>
<td><i>set_index()</i></td>
<td>Convert column(s) into index</td>
</tr>
<tr>
<td><i>reset_index()</i></td>
<td>Convert index back into columns</td>
</tr>
<tr>
<td><i>MultiIndex</i></td>
<td>Hierarchical index with multiple levels</td>
</tr>
</table>

#### 1. **set_index()**

*set_index()* changes one or more columns into the DataFrame's index.


**Syntax:**
```python
df.set_index(keys, drop=True, inplace=False)
```
**Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
</tr>
<tr>
<td><i>keys</i></td>
<td>Column(s) to become index</td>
</tr>
<tr>
<td><i>drop=True</i></td>
<td>Remove column after making it index</td>
</tr>
<tr>
<td><i>drop=False</i></td>
<td>Keep original column</td>
</tr>
<tr>
<td><i>inplace=True</i></td>
<td>Modify original DataFrame</td>
</tr>
</table>

In [1]:
import pandas as pd
# Sample data
df = pd.DataFrame({
    'Student_ID':[101,102,103,104],
    'Name':['Alice','Bob','Charlie','David'],
    'Math':[90,75,88,95]
})

print(df)

   Student_ID     Name  Math
0         101    Alice    90
1         102      Bob    75
2         103  Charlie    88
3         104    David    95

##### **Example 1 (Single Index)**

In [2]:
df.set_index('Student_ID', inplace=True)
df

               Name  Math
Student_ID
101           Alice    90
102             Bob    75
103         Charlie    88
104           David    95

#### 2. **reset_index()**

Converts the index back into normal columns.

**Syntax:**
```python
df.reset_index(drop=False, inplace=False)
```

**Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
</tr>
<tr>
<td><i>drop</i></td>
<td>If True, discard the index instead of creating a column</td>
</tr>
<tr>
<td><i>inplace</i></td>
<td>Modify original DataFrame</td>
</tr>
</table>

In [3]:
print(df)
df.reset_index(inplace=True)
df

               Name  Math
Student_ID
101           Alice    90
102             Bob    75
103         Charlie    88
104           David    95

   Student_ID     Name  Math
0         101    Alice    90
1         102      Bob    75
2         103  Charlie    88
3         104    David    95

#### 3. **MultiIndex**


A MultiIndex is an index with multiple levels.

In [4]:
df = pd.DataFrame({
    'Region':['East','East','West','West'],
    'Year':[2024,2025,2024,2025],
    'Sales':[1000,1200,900,1100]
})

df = df.set_index(['Region','Year'])

print(df)

             Sales
Region Year
East   2024   1000
       2025   1200
West   2024    900
       2025   1100

**Access data**

- Entire Region

In [5]:
df.loc['West']

      Sales
Year
2024    900
2025   1100

- Specific Row

In [6]:
df.loc[('East', 2024)]

Sales    1000
Name: (East, 2024), dtype: int64