### **Date & Time Functions**

Date & time operations are one of the most important pandas topics for data analysis (sales, logs, stock data, attendance, etc.).

#### **Create example dataset**

In [1]:
import pandas as pd

data = {
    'Order_ID': [1001, 1002, 1003, 1004, 1005, 1006],
    'Customer': ['Ravi', 'Asha', 'Kiran', 'Neha', 'Arjun', 'Priya'],
    'City': ['Hyderabad', 'Bengaluru', 'Chennai', 'Mumbai', 'Hyderabad', 'Pune'],
    'Order_Time': [
        '2026-07-20 09:15:00',
        '2026-07-20 14:30:00',
        '2026-07-21 11:45:00',
        '2026-07-21 18:10:00',
        '2026-07-22 08:50:00',
        '2026-07-23 16:20:00'
    ],
    'Delivery_Time': [
        '2026-07-21 12:00:00',
        '2026-07-22 10:00:00',
        '2026-07-22 15:30:00',
        '2026-07-24 09:15:00',
        '2026-07-23 11:20:00',
        '2026-07-25 13:45:00'
    ],
    'Amount': [2500, 1800, 3200, 1500, 4100, 2750]
}

df = pd.DataFrame(data)
df

,Order_ID,Customer,City,Order_Time,Delivery_Time,Amount
0,1001,Ravi,Hyderabad,2026-07-20 09:15:00,2026-07-21 12:00:00,2500
1,1002,Asha,Bengaluru,2026-07-20 14:30:00,2026-07-22 10:00:00,1800
2,1003,Kiran,Chennai,2026-07-21 11:45:00,2026-07-22 15:30:00,3200
3,1004,Neha,Mumbai,2026-07-21 18:10:00,2026-07-24 09:15:00,1500
4,1005,Arjun,Hyderabad,2026-07-22 08:50:00,2026-07-23 11:20:00,4100
5,1006,Priya,Pune,2026-07-23 16:20:00,2026-07-25 13:45:00,2750

In [2]:
df.dtypes

Order_ID         int64
Customer           str
City               str
Order_Time         str
Delivery_Time      str
Amount           int64
dtype: object

#### 1. **Convert string to datetime**

This is the first thing you should always do.

In [3]:
df['Order_Time'] = pd.to_datetime(df['Order_Time'])
df['Delivery_Time'] = pd.to_datetime(df['Delivery_Time'])

In [4]:
df.dtypes

Order_ID                  int64
Customer                    str
City                        str
Order_Time       datetime64[us]
Delivery_Time    datetime64[us]
Amount                    int64
dtype: object

#### 2. **Extract date parts (.dt accessor)**

Year, month, day

In [5]:
df['Ord_Year'] = df['Order_Time'].dt.year
df['Ord_Month'] = df['Order_Time'].dt.month
df['Ord_Day'] = df['Order_Time'].dt.day
df[['Order_Time', 'Ord_Year', 'Ord_Month', 'Ord_Day']]

           Order_Time  Ord_Year  Ord_Month  Ord_Day
0 2026-07-20 09:15:00      2026          7       20
1 2026-07-20 14:30:00      2026          7       20
2 2026-07-21 11:45:00      2026          7       21
3 2026-07-21 18:10:00      2026          7       21
4 2026-07-22 08:50:00      2026          7       22
5 2026-07-23 16:20:00      2026          7       23

#### 3. **Extract Month & Weekday Name**

In [6]:
df['Ord_Month_Name'] = df['Order_Time'].dt.month_name()
df['Ord_Day_Name'] = df['Order_Time'].dt.day_name()
df[['Order_Time', 'Ord_Year', 'Ord_Month_Name', 'Ord_Day_Name']]

           Order_Time  Ord_Year Ord_Month_Name Ord_Day_Name
0 2026-07-20 09:15:00      2026           July       Monday
1 2026-07-20 14:30:00      2026           July       Monday
2 2026-07-21 11:45:00      2026           July      Tuesday
3 2026-07-21 18:10:00      2026           July      Tuesday
4 2026-07-22 08:50:00      2026           July    Wednesday
5 2026-07-23 16:20:00      2026           July     Thursday

#### 4. **Extract Time parts**

In [7]:
df['Ord_Time'] = df['Order_Time'].dt.time
df['Ord_Hour'] = df['Order_Time'].dt.hour
df['Ord_Min'] = df['Order_Time'].dt.minute
df[['Order_Time', 'Ord_Time','Ord_Hour', 'Ord_Min']]

           Order_Time  Ord_Time  Ord_Hour  Ord_Min
0 2026-07-20 09:15:00  09:15:00         9       15
1 2026-07-20 14:30:00  14:30:00        14       30
2 2026-07-21 11:45:00  11:45:00        11       45
3 2026-07-21 18:10:00  18:10:00        18       10
4 2026-07-22 08:50:00  08:50:00         8       50
5 2026-07-23 16:20:00  16:20:00        16       20

#### 5. **Extract Only the date**

In [8]:
df['Ord_Date'] = df['Order_Time'].dt.date
df[['Order_Time', 'Ord_Date']]

           Order_Time    Ord_Date
0 2026-07-20 09:15:00  2026-07-20
1 2026-07-20 14:30:00  2026-07-20
2 2026-07-21 11:45:00  2026-07-21
3 2026-07-21 18:10:00  2026-07-21
4 2026-07-22 08:50:00  2026-07-22
5 2026-07-23 16:20:00  2026-07-23

#### 6. **Current date and time**

**Current date&time**

In [9]:
print(pd.Timestamp.now())

2026-08-05 16:27:47.116694

**Only current data**

In [10]:
print(pd.Timestamp.today().date())

2026-08-05

#### 7. **Date arithmetic pd.Timedelta() (add/subtract days)**

**Add expected delivery (48 hours)**

In [11]:
df['Expected_Delivery'] = df['Order_Time'] + pd.Timedelta(hours=48)
df[['Order_Time', 'Expected_Delivery']]

           Order_Time   Expected_Delivery
0 2026-07-20 09:15:00 2026-07-22 09:15:00
1 2026-07-20 14:30:00 2026-07-22 14:30:00
2 2026-07-21 11:45:00 2026-07-23 11:45:00
3 2026-07-21 18:10:00 2026-07-23 18:10:00
4 2026-07-22 08:50:00 2026-07-24 08:50:00
5 2026-07-23 16:20:00 2026-07-25 16:20:00

**Add 7 days**

In [12]:
df['Follow_Up_Date'] = df['Order_Time'] + pd.Timedelta(days=7)
df[['Order_Time', 'Follow_Up_Date']]

           Order_Time      Follow_Up_Date
0 2026-07-20 09:15:00 2026-07-27 09:15:00
1 2026-07-20 14:30:00 2026-07-27 14:30:00
2 2026-07-21 11:45:00 2026-07-28 11:45:00
3 2026-07-21 18:10:00 2026-07-28 18:10:00
4 2026-07-22 08:50:00 2026-07-29 08:50:00
5 2026-07-23 16:20:00 2026-07-30 16:20:00

**Subtract 30 Minutes**

In [13]:
df['Prep_Start'] = df['Order_Time'] - pd.Timedelta(minutes=30)
df[['Order_Time', 'Prep_Start']]

           Order_Time          Prep_Start
0 2026-07-20 09:15:00 2026-07-20 08:45:00
1 2026-07-20 14:30:00 2026-07-20 14:00:00
2 2026-07-21 11:45:00 2026-07-21 11:15:00
3 2026-07-21 18:10:00 2026-07-21 17:40:00
4 2026-07-22 08:50:00 2026-07-22 08:20:00
5 2026-07-23 16:20:00 2026-07-23 15:50:00

#### 8. **Difference between two datetime columns**

Calculate delivery duration

In [14]:
df['Delivery_Duration'] = df['Delivery_Time'] - df['Order_Time']
df[['Order_Time', 'Delivery_Time', 'Delivery_Duration']]

           Order_Time       Delivery_Time Delivery_Duration
0 2026-07-20 09:15:00 2026-07-21 12:00:00   1 days 02:45:00
1 2026-07-20 14:30:00 2026-07-22 10:00:00   1 days 19:30:00
2 2026-07-21 11:45:00 2026-07-22 15:30:00   1 days 03:45:00
3 2026-07-21 18:10:00 2026-07-24 09:15:00   2 days 15:05:00
4 2026-07-22 08:50:00 2026-07-23 11:20:00   1 days 02:30:00
5 2026-07-23 16:20:00 2026-07-25 13:45:00   1 days 21:25:00

#### 9. **Filter by date**

Orders placed on July 21

In [15]:
df.loc[df['Order_Time'].dt.date == pd.to_datetime('2026-07-21').date(), 'Order_ID':'Amount']

   Order_ID Customer     City          Order_Time       Delivery_Time  Amount
2      1003    Kiran  Chennai 2026-07-21 11:45:00 2026-07-22 15:30:00    3200
3      1004     Neha   Mumbai 2026-07-21 18:10:00 2026-07-24 09:15:00    1500

Orders after July 21

In [16]:
df.loc[df['Order_Time'] > '2026-07-21', 'Order_ID':'Amount']

,Order_ID,Customer,City,Order_Time,Delivery_Time,Amount
2,1003,Kiran,Chennai,2026-07-21 11:45:00,2026-07-22 15:30:00,3200
3,1004,Neha,Mumbai,2026-07-21 18:10:00,2026-07-24 09:15:00,1500
4,1005,Arjun,Hyderabad,2026-07-22 08:50:00,2026-07-23 11:20:00,4100
5,1006,Priya,Pune,2026-07-23 16:20:00,2026-07-25 13:45:00,2750

#### 10. **Set datetime as index**

In [17]:
df_ts = df.set_index('Order_Time') #Rule: Keep datetime64[ns] for pandas time-series operations; .dt.date converts it to object dtype.
df_ts.head()

,Order_ID,Customer,City,Delivery_Time,Amount,Ord_Year,Ord_Month,Ord_Day,Ord_Month_Name,Ord_Day_Name,Ord_Time,Ord_Hour,Ord_Min,Ord_Date,Expected_Delivery,Follow_Up_Date,Prep_Start,Delivery_Duration
Order_Time,,,,,,,,,,,,,,,,,,
2026-07-20 09:15:00,1001,Ravi,Hyderabad,2026-07-21 12:00:00,2500,2026,7,20,July,Monday,09:15:00,9,15,2026-07-20,2026-07-22 09:15:00,2026-07-27 09:15:00,2026-07-20 08:45:00,1 days 02:45:00
2026-07-20 14:30:00,1002,Asha,Bengaluru,2026-07-22 10:00:00,1800,2026,7,20,July,Monday,14:30:00,14,30,2026-07-20,2026-07-22 14:30:00,2026-07-27 14:30:00,2026-07-20 14:00:00,1 days 19:30:00
2026-07-21 11:45:00,1003,Kiran,Chennai,2026-07-22 15:30:00,3200,2026,7,21,July,Tuesday,11:45:00,11,45,2026-07-21,2026-07-23 11:45:00,2026-07-28 11:45:00,2026-07-21 11:15:00,1 days 03:45:00
2026-07-21 18:10:00,1004,Neha,Mumbai,2026-07-24 09:15:00,1500,2026,7,21,July,Tuesday,18:10:00,18,10,2026-07-21,2026-07-23 18:10:00,2026-07-28 18:10:00,2026-07-21 17:40:00,2 days 15:05:00
2026-07-22 08:50:00,1005,Arjun,Hyderabad,2026-07-23 11:20:00,4100,2026,7,22,July,Wednesday,08:50:00,8,50,2026-07-22,2026-07-24 08:50:00,2026-07-29 08:50:00,2026-07-22 08:20:00,1 days 02:30:00

#### 11. **Date range selection**

Orders from July 20 to July 21

In [18]:
df_ts.loc['2026-07-20':'2026-07-21', 'Order_ID':'Amount']

                     Order_ID Customer       City       Delivery_Time  Amount
Order_Time
2026-07-20 09:15:00      1001     Ravi  Hyderabad 2026-07-21 12:00:00    2500
2026-07-20 14:30:00      1002     Asha  Bengaluru 2026-07-22 10:00:00    1800
2026-07-21 11:45:00      1003    Kiran    Chennai 2026-07-22 15:30:00    3200
2026-07-21 18:10:00      1004     Neha     Mumbai 2026-07-24 09:15:00    1500

Only July 20

In [19]:
df_ts.loc['2026-07-20', 'Order_ID':'Amount']

                     Order_ID Customer       City       Delivery_Time  Amount
Order_Time
2026-07-20 09:15:00      1001     Ravi  Hyderabad 2026-07-21 12:00:00    2500
2026-07-20 14:30:00      1002     Asha  Bengaluru 2026-07-22 10:00:00    1800

#### 12. **strftime() — Format for reports**

Convert to Indian report format

In [20]:
df['Report_Date'] = df['Order_Time'].dt.strftime('%d-%m-%Y %I:%M %p')
print(df[['Order_Time', 'Report_Date']])

           Order_Time          Report_Date
0 2026-07-20 09:15:00  20-07-2026 09:15 AM
1 2026-07-20 14:30:00  20-07-2026 02:30 PM
2 2026-07-21 11:45:00  21-07-2026 11:45 AM
3 2026-07-21 18:10:00  21-07-2026 06:10 PM
4 2026-07-22 08:50:00  22-07-2026 08:50 AM
5 2026-07-23 16:20:00  23-07-2026 04:20 PM

##### **Best Practice**

Always use one of these:

```python
# If the input date is already in ISO format (YYYY-MM-DD)
pd.to_datetime("2026-07-24")

# If the input date is in another format, specify it explicitly
pd.to_datetime(df["Date"], format="%d-%m-%Y")
```

**Note:**

- `format=` does not change the date format.
- It tells pandas how to read (parse) the input date.
- The `format` must match the input date format.

**Memory Trick:**

- `pd.to_datetime(format=...)` → Read the date.
- `.dt.strftime(...)` → Display the date in a different format.