### **Resampling**

**Resampling means:**

Changing the frequency of time-series data (daily → monthly, monthly → yearly, hourly → daily, etc.) and then applying an aggregation function.

It only works with dates

#### **There are two common ways to use resample().**
----

1. **When the Date is the Index (Most Common)**

**Syntax:**
```python
df.resample(rule)[column].aggregation()
```
---
2. **When the Date is NOT the Index**

**Syntax:**
```python
df.resample(rule, on="date_column")[column].aggregation()
```
---

#### **Difference between GroupBy and Resample**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>GroupBy</th>
<th>Resample</th>
</tr>
<tr>
<td>Groups by column values</td>
<td>Groups by time intervals</td>
</tr>
<tr>
<td>Works on any column</td>
<td>Works only with datetime</td>
</tr>
<tr>
<td>Can group by Department, City, Product</td>
<td>Groups by Day, Week, Month, Year</td>
</tr>
<tr>
<td>No datetime required</td>
<td>Datetime required</td>
</tr>
<tr>
<td>Uses groupby()</td>
<td>Uses resample()</td>
</tr>
</table>

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Order_Date":[
        "2025-01-03",
        "2025-01-10",
        "2025-01-15",
        "2025-02-05",
        "2025-02-18",
        "2025-03-12",
        "2025-03-25",
        "2025-04-08",
        "2025-04-22",
        "2025-05-05",
        "2025-06-10",
        "2025-07-15",
        "2025-08-20",
        "2025-09-10",
        "2025-10-18",
        "2025-11-25",
        "2025-12-30",
        "2026-01-12",
        "2026-02-20",
        "2026-03-28"
    ],

    "Sales":[
        1200,1800,1400,
        2000,1700,
        2400,2600,
        1900,2200,
        2500,
        2700,
        2900,
        3100,
        2800,
        3300,
        3500,
        4000,
        4200,
        4500,
        4800
    ],

    "Profit":[
        200,350,250,
        420,360,
        500,550,
        410,450,
        520,
        600,
        650,
        700,
        620,
        760,
        800,
        950,
        1000,
        1050,
        1100
    ],

    "Orders":[
        15,18,16,
        21,19,
        24,26,
        20,22,
        25,
        28,
        30,
        33,
        29,
        35,
        37,
        40,
        42,
        45,
        48
    ]
})

**Convert the date column.**

In [2]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
print(df.dtypes)
df

Order_Date    datetime64[us]
Sales                  int64
Profit                 int64
Orders                 int64
dtype: object

   Order_Date  Sales  Profit  Orders
0  2025-01-03   1200     200      15
1  2025-01-10   1800     350      18
2  2025-01-15   1400     250      16
3  2025-02-05   2000     420      21
4  2025-02-18   1700     360      19
5  2025-03-12   2400     500      24
6  2025-03-25   2600     550      26
7  2025-04-08   1900     410      20
8  2025-04-22   2200     450      22
9  2025-05-05   2500     520      25
10 2025-06-10   2700     600      28
11 2025-07-15   2900     650      30
12 2025-08-20   3100     700      33
13 2025-09-10   2800     620      29
14 2025-10-18   3300     760      35
15 2025-11-25   3500     800      37
16 2025-12-30   4000     950      40
17 2026-01-12   4200    1000      42
18 2026-02-20   4500    1050      45
19 2026-03-28   4800    1100      48

#### **Method 1: Resampling using Date Index (Most Common)**

Set the date column as the index.

In [3]:
df_ts = df.set_index('Order_Date')
print(df_ts.index)

DatetimeIndex(['2025-01-03', '2025-01-10', '2025-01-15', '2025-02-05',
               '2025-02-18', '2025-03-12', '2025-03-25', '2025-04-08',
               '2025-04-22', '2025-05-05', '2025-06-10', '2025-07-15',
               '2025-08-20', '2025-09-10', '2025-10-18', '2025-11-25',
               '2025-12-30', '2026-01-12', '2026-02-20', '2026-03-28'],
              dtype='datetime64[us]', name='Order_Date', freq=None)

**Monthly Sales**

In [4]:
df_ts.resample('ME')['Sales'].sum()

Order_Date
2025-01-31    4400
2025-02-28    3700
2025-03-31    5000
2025-04-30    4100
2025-05-31    2500
2025-06-30    2700
2025-07-31    2900
2025-08-31    3100
2025-09-30    2800
2025-10-31    3300
2025-11-30    3500
2025-12-31    4000
2026-01-31    4200
2026-02-28    4500
2026-03-31    4800
Freq: ME, Name: Sales, dtype: int64

**Monthly Profit**

In [5]:
df_ts.resample('ME')['Profit'].sum()

Order_Date
2025-01-31     800
2025-02-28     780
2025-03-31    1050
2025-04-30     860
2025-05-31     520
2025-06-30     600
2025-07-31     650
2025-08-31     700
2025-09-30     620
2025-10-31     760
2025-11-30     800
2025-12-31     950
2026-01-31    1000
2026-02-28    1050
2026-03-31    1100
Freq: ME, Name: Profit, dtype: int64

**Monthly Average Sales**

In [6]:
df_ts.resample('ME')['Sales'].mean()

Order_Date
2025-01-31    1466.666667
2025-02-28    1850.000000
2025-03-31    2500.000000
2025-04-30    2050.000000
2025-05-31    2500.000000
2025-06-30    2700.000000
2025-07-31    2900.000000
2025-08-31    3100.000000
2025-09-30    2800.000000
2025-10-31    3300.000000
2025-11-30    3500.000000
2025-12-31    4000.000000
2026-01-31    4200.000000
2026-02-28    4500.000000
2026-03-31    4800.000000
Freq: ME, Name: Sales, dtype: float64

**Yearly Resampling**

In [7]:
df_ts.resample('YE').sum()

            Sales  Profit  Orders
Order_Date
2025-12-31  42000    9090     438
2026-12-31  13500    3150     135

**Multiple Aggregations**

In [8]:
df_ts.resample('YE').agg({
    'Sales':['sum', 'mean', 'max'],
    'Profit':['sum', 'mean'],
    'Orders':['sum']
})

            Sales                    Profit              Orders
              sum         mean   max    sum         mean    sum
Order_Date
2025-12-31  42000  2470.588235  4000   9090   534.705882    438
2026-12-31  13500  4500.000000  4800   3150  1050.000000    135

#### **Method 2: Resampling WITHOUT Setting the Index**

Sometimes you don't want to change the index.

Use the on parameter.

**Monthly Sales**

In [9]:
df.resample('ME', on='Order_Date')['Sales'].sum()

Order_Date
2025-01-31    4400
2025-02-28    3700
2025-03-31    5000
2025-04-30    4100
2025-05-31    2500
2025-06-30    2700
2025-07-31    2900
2025-08-31    3100
2025-09-30    2800
2025-10-31    3300
2025-11-30    3500
2025-12-31    4000
2026-01-31    4200
2026-02-28    4500
2026-03-31    4800
Freq: ME, Name: Sales, dtype: int64

**Monthly Profit**

In [10]:
df.resample('ME', on='Order_Date')['Profit'].sum()

Order_Date
2025-01-31     800
2025-02-28     780
2025-03-31    1050
2025-04-30     860
2025-05-31     520
2025-06-30     600
2025-07-31     650
2025-08-31     700
2025-09-30     620
2025-10-31     760
2025-11-30     800
2025-12-31     950
2026-01-31    1000
2026-02-28    1050
2026-03-31    1100
Freq: ME, Name: Profit, dtype: int64

**Yearly**

In [11]:
df.resample('YE', on='Order_Date').sum()

            Sales  Profit  Orders
Order_Date
2025-12-31  42000    9090     438
2026-12-31  13500    3150     135

####  **Common Resampling Frequency Codes**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Frequency</th>
<th>Pandas Code</th>
</tr>
<tr>
<td>Daily</td>
<td>'D'</td>
</tr>
<tr>
<td>Weekly</td>
<td>'W'</td>
</tr>
<tr>
<td>Month Start</td>
<td>'MS'</td>
</tr>
<tr>
<td>Month End</td>
<td>'ME'</td>
</tr>
<tr>
<td>Quarter Start</td>
<td>'QS'</td>
</tr>
<tr>
<td>Quarter End</td>
<td>'QE'</td>
</tr>
<tr>
<td>Year Start</td>
<td>'YS'</td>
</tr>
<tr>
<td>Year End</td>
<td>'YE'</td>
</tr>
<tr>
<td>Hour</td>
<td>'h'</td>
</tr>
<tr>
<td>Minute</td>
<td>'min'</td>
</tr>
</table>



##### **When to Use Which?**

**Use groupby() when your groups are based on categories:**

- Department
- Product
- City
- Customer
- Employee

**Use resample() when your groups are based on time:**

- Daily sales
- Weekly website visitors
- Monthly revenue
- Quarterly profit
- Yearly expenses