### **Window Functions in Pandas**

A window function performs calculations over a group of rows related to the current row without collapsing the DataFrame.

#### **Types of Window Functions in Pandas**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Window Function</th>
<th>Purpose</th>
<th>Industry Use</th>
</tr>
<tr>
<td><i>Rolling</i></td>
<td>Fixed-size moving window</td>
<td>Stock analysis, moving average</td>
</tr>
<tr>
<td><i>Expanding</i></td>
<td>From first row to current row</td>
<td>Running totals</td>
</tr>
<tr>
<td><i>Exponential Moving (EWM)</i></td>
<td>Gives more importance to recent data</td>
<td>Forecasting</td>
</tr>
<tr>
<td><i>Shift</i></td>
<td>Move data up/down</td>
<td>Previous day comparison</td>
</tr>
<tr>
<td><i>Diff</i></td>
<td>Difference between rows</td>
<td>Daily change</td>
</tr>
<tr>
<td><i>Rank</i></td>
<td>Ranking within dataset/group</td>
<td>Sales ranking</td>
</tr>
</table>

These are the six primary window-style operations most commonly used in pandas.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Date": pd.date_range("2025-01-01", periods=15),
    "Sales":[
        1200,1500,1700,1600,2000,
        1800,2200,2500,2400,2600,
        2800,3000,3100,3300,3500
    ],
    "Orders":[
        22,25,28,27,31,
        30,35,37,36,39,
        40,42,43,45,47
    ],
    "Visitors":[
        210,250,270,260,300,
        295,330,360,355,380,
        400,420,430,450,470
    ]
})

df

         Date  Sales  Orders  Visitors
0  2025-01-01   1200      22       210
1  2025-01-02   1500      25       250
2  2025-01-03   1700      28       270
3  2025-01-04   1600      27       260
4  2025-01-05   2000      31       300
5  2025-01-06   1800      30       295
6  2025-01-07   2200      35       330
7  2025-01-08   2500      37       360
8  2025-01-09   2400      36       355
9  2025-01-10   2600      39       380
10 2025-01-11   2800      40       400
11 2025-01-12   3000      42       420
12 2025-01-13   3100      43       430
13 2025-01-14   3300      45       450
14 2025-01-15   3500      47       470

#### 1. **Rolling Window**

**What it does**

Looks at a fixed number of consecutive rows.

**Example:**

**Window = 3**

Current row uses
```
Row1
Row2
Row3
```
Next row

```
Row2
Row3
Row4
```

**Syntax:**
```python
df["column"].rolling(
    window,
    min_periods=None,
    center=False,
    win_type=None,
    on=None,
    closed=None
)
```

**Important Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
<th>Example</th>
</tr>
<tr>
<td><i>window</i></td>
<td>Size of the moving window</td>
<td>window=3</td>
</tr>
<tr>
<td><i>min_periods</i></td>
<td>Minimum observations required to calculate a value</td>
<td>min_periods=1</td>
</tr>
<tr>
<td><i>center</i></td>
<td>Place result at center of window instead of right edge</td>
<td>center=True</td>
</tr>
<tr>
<td><i>win_type</i></td>
<td>Weighted window type (e.g., Gaussian, triangular)</td>
<td>win_type="gaussian"</td>
</tr>
<tr>
<td><i>on</i></td>
<td>Column to use for rolling when DataFrame index isn't datetime</td>
<td>on="Date"</td>
</tr>
<tr>
<td><i>closed</i></td>
<td>Which window endpoints are included (time-based windows)</td>
<td>closed="right"</td>
</tr>
</table>

 **USE CASES**
 
1. **Moving Average**

In [2]:
df['Sales_MA_3'] = df['Sales'].rolling(window=3).mean() #Today's average sales over the last 3 days.
df

         Date  Sales  Orders  Visitors   Sales_MA_3
0  2025-01-01   1200      22       210          NaN
1  2025-01-02   1500      25       250          NaN
2  2025-01-03   1700      28       270  1466.666667
3  2025-01-04   1600      27       260  1600.000000
4  2025-01-05   2000      31       300  1766.666667
5  2025-01-06   1800      30       295  1800.000000
6  2025-01-07   2200      35       330  2000.000000
7  2025-01-08   2500      37       360  2166.666667
8  2025-01-09   2400      36       355  2366.666667
9  2025-01-10   2600      39       380  2500.000000
10 2025-01-11   2800      40       400  2600.000000
11 2025-01-12   3000      42       420  2800.000000
12 2025-01-13   3100      43       430  2966.666667
13 2025-01-14   3300      45       450  3133.333333
14 2025-01-15   3500      47       470  3300.000000

2. **Rolling Sum**

In [3]:
df['Sales_Last3Days'] = df['Sales'].rolling(window=3).sum() #How much revenue came in during the last 3 days?
df

         Date  Sales  Orders  Visitors   Sales_MA_3  Sales_Last3Days
0  2025-01-01   1200      22       210          NaN              NaN
1  2025-01-02   1500      25       250          NaN              NaN
2  2025-01-03   1700      28       270  1466.666667           4400.0
3  2025-01-04   1600      27       260  1600.000000           4800.0
4  2025-01-05   2000      31       300  1766.666667           5300.0
5  2025-01-06   1800      30       295  1800.000000           5400.0
6  2025-01-07   2200      35       330  2000.000000           6000.0
7  2025-01-08   2500      37       360  2166.666667           6500.0
8  2025-01-09   2400      36       355  2366.666667           7100.0
9  2025-01-10   2600      39       380  2500.000000           7500.0
10 2025-01-11   2800      40       400  2600.000000           7800.0
11 2025-01-12   3000      42       420  2800.000000           8400.0
12 2025-01-13   3100      43       430  2966.666667           8900.0
13 2025-01-14   3300      45       450  3133.333333           9400.0
14 2025-01-15   3500      47       470  3300.000000           9900.0

3. **Rolling Maximum**

In [4]:
df['Highest_Sales'] = df['Sales'].rolling(window=7).max() #Highest sales achieved during the past week.
df

,Date,Sales,Orders,Visitors,Sales_MA_3,Sales_Last3Days,Highest_Sales
0,2025-01-01,1200,22,210,NaN,NaN,NaN
1,2025-01-02,1500,25,250,NaN,NaN,NaN
2,2025-01-03,1700,28,270,1466.666667,4400.0,NaN
3,2025-01-04,1600,27,260,1600.000000,4800.0,NaN
4,2025-01-05,2000,31,300,1766.666667,5300.0,NaN
5,2025-01-06,1800,30,295,1800.000000,5400.0,NaN
6,2025-01-07,2200,35,330,2000.000000,6000.0,2200.0
7,2025-01-08,2500,37,360,2166.666667,6500.0,2500.0
8,2025-01-09,2400,36,355,2366.666667,7100.0,2500.0
9,2025-01-10,2600,39,380,2500.000000,7500.0,2600.0
10,2025-01-11,2800,40,400,2600.000000,7800.0,2800.0
11,2025-01-12,3000,42,420,2800.000000,8400.0,3000.0
12,2025-01-13,3100,43,430,2966.666667,8900.0,3100.0
13,2025-01-14,3300,45,450,3133.333333,9400.0,3300.0
14,2025-01-15,3500,47,470,3300.000000,9900.0,3500.0

4. **Rolling Minimum**

In [5]:
df['Lowest_Sales'] = df['Sales'].rolling(window=7).min() #Worst sales day during the past week.
df

,Date,Sales,Orders,Visitors,Sales_MA_3,Sales_Last3Days,Highest_Sales,Lowest_Sales
0,2025-01-01,1200,22,210,NaN,NaN,NaN,NaN
1,2025-01-02,1500,25,250,NaN,NaN,NaN,NaN
2,2025-01-03,1700,28,270,1466.666667,4400.0,NaN,NaN
3,2025-01-04,1600,27,260,1600.000000,4800.0,NaN,NaN
4,2025-01-05,2000,31,300,1766.666667,5300.0,NaN,NaN
5,2025-01-06,1800,30,295,1800.000000,5400.0,NaN,NaN
6,2025-01-07,2200,35,330,2000.000000,6000.0,2200.0,1200.0
7,2025-01-08,2500,37,360,2166.666667,6500.0,2500.0,1500.0
8,2025-01-09,2400,36,355,2366.666667,7100.0,2500.0,1600.0
9,2025-01-10,2600,39,380,2500.000000,7500.0,2600.0,1600.0
10,2025-01-11,2800,40,400,2600.000000,7800.0,2800.0,1800.0
11,2025-01-12,3000,42,420,2800.000000,8400.0,3000.0,1800.0
12,2025-01-13,3100,43,430,2966.666667,8900.0,3100.0,2200.0
13,2025-01-14,3300,45,450,3133.333333,9400.0,3300.0,2400.0
14,2025-01-15,3500,47,470,3300.000000,9900.0,3500.0,2400.0

#### 2. **Expanding Window**

**What it does**

Starts from the first row and keeps growing.

```
Row1

↓

Row1 Row2

↓

Row1 Row2 Row3

↓

Row1 Row2 Row3 Row4
```

**Syntax:**
```python
df["column"].expanding(
    min_periods=1,
    axis=0
)
```


**Important Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
<th>Example</th>
</tr>
<tr>
<td><i>min_periods</i></td>
<td>Minimum rows before calculation begins</td>
<td>min_periods=2</td>
</tr>
<tr>
<td><i>axis</i></td>
<td>Compute across rows or columns (axis is deprecated for some APIs; rows is the common default)</td>
<td>axis=0</td>
</tr>
</table>


**USE CASES**

1. **Running Total**

In [6]:
df2 = pd.DataFrame({
    "Date": pd.date_range("2025-01-01", periods=15),
    "Sales":[
        1200,1500,1700,1600,2000,
        1800,2200,2500,2400,2600,
        2800,3000,3100,3300,3500
    ],
    "Orders":[
        22,25,28,27,31,
        30,35,37,36,39,
        40,42,43,45,47
    ],
    "Visitors":[
        210,250,270,260,300,
        295,330,360,355,380,
        400,420,430,450,470
    ]
})

In [7]:
df2['Running_Sales'] = df2['Sales'].expanding().sum() #Total sales since business started.
df2

         Date  Sales  Orders  Visitors  Running_Sales
0  2025-01-01   1200      22       210         1200.0
1  2025-01-02   1500      25       250         2700.0
2  2025-01-03   1700      28       270         4400.0
3  2025-01-04   1600      27       260         6000.0
4  2025-01-05   2000      31       300         8000.0
5  2025-01-06   1800      30       295         9800.0
6  2025-01-07   2200      35       330        12000.0
7  2025-01-08   2500      37       360        14500.0
8  2025-01-09   2400      36       355        16900.0
9  2025-01-10   2600      39       380        19500.0
10 2025-01-11   2800      40       400        22300.0
11 2025-01-12   3000      42       420        25300.0
12 2025-01-13   3100      43       430        28400.0
13 2025-01-14   3300      45       450        31700.0
14 2025-01-15   3500      47       470        35200.0

2. **Running Average**

In [8]:
df2['Average_Sales'] = df2['Sales'].expanding().mean() #Average sales until today.
df2

         Date  Sales  Orders  Visitors  Running_Sales  Average_Sales
0  2025-01-01   1200      22       210         1200.0    1200.000000
1  2025-01-02   1500      25       250         2700.0    1350.000000
2  2025-01-03   1700      28       270         4400.0    1466.666667
3  2025-01-04   1600      27       260         6000.0    1500.000000
4  2025-01-05   2000      31       300         8000.0    1600.000000
5  2025-01-06   1800      30       295         9800.0    1633.333333
6  2025-01-07   2200      35       330        12000.0    1714.285714
7  2025-01-08   2500      37       360        14500.0    1812.500000
8  2025-01-09   2400      36       355        16900.0    1877.777778
9  2025-01-10   2600      39       380        19500.0    1950.000000
10 2025-01-11   2800      40       400        22300.0    2027.272727
11 2025-01-12   3000      42       420        25300.0    2108.333333
12 2025-01-13   3100      43       430        28400.0    2184.615385
13 2025-01-14   3300      45       450        31700.0    2264.285714
14 2025-01-15   3500      47       470        35200.0    2346.666667

3. **Running Maximum**

In [9]:
df2['Best_Sales_Ever'] = df2['Sales'].expanding().max() #Highest sales ever achieved.
df2

,Date,Sales,Orders,Visitors,Running_Sales,Average_Sales,Best_Sales_Ever
0,2025-01-01,1200,22,210,1200.0,1200.000000,1200.0
1,2025-01-02,1500,25,250,2700.0,1350.000000,1500.0
2,2025-01-03,1700,28,270,4400.0,1466.666667,1700.0
3,2025-01-04,1600,27,260,6000.0,1500.000000,1700.0
4,2025-01-05,2000,31,300,8000.0,1600.000000,2000.0
5,2025-01-06,1800,30,295,9800.0,1633.333333,2000.0
6,2025-01-07,2200,35,330,12000.0,1714.285714,2200.0
7,2025-01-08,2500,37,360,14500.0,1812.500000,2500.0
8,2025-01-09,2400,36,355,16900.0,1877.777778,2500.0
9,2025-01-10,2600,39,380,19500.0,1950.000000,2600.0
10,2025-01-11,2800,40,400,22300.0,2027.272727,2800.0
11,2025-01-12,3000,42,420,25300.0,2108.333333,3000.0
12,2025-01-13,3100,43,430,28400.0,2184.615385,3100.0
13,2025-01-14,3300,45,450,31700.0,2264.285714,3300.0
14,2025-01-15,3500,47,470,35200.0,2346.666667,3500.0

4. **Running Minimum**

In [10]:
df2['Lowest_Sales_Ever'] = df2['Sales'].expanding().min()   #Lowest sales ever recorded.
df2

,Date,Sales,Orders,Visitors,Running_Sales,Average_Sales,Best_Sales_Ever,Lowest_Sales_Ever
0,2025-01-01,1200,22,210,1200.0,1200.000000,1200.0,1200.0
1,2025-01-02,1500,25,250,2700.0,1350.000000,1500.0,1200.0
2,2025-01-03,1700,28,270,4400.0,1466.666667,1700.0,1200.0
3,2025-01-04,1600,27,260,6000.0,1500.000000,1700.0,1200.0
4,2025-01-05,2000,31,300,8000.0,1600.000000,2000.0,1200.0
5,2025-01-06,1800,30,295,9800.0,1633.333333,2000.0,1200.0
6,2025-01-07,2200,35,330,12000.0,1714.285714,2200.0,1200.0
7,2025-01-08,2500,37,360,14500.0,1812.500000,2500.0,1200.0
8,2025-01-09,2400,36,355,16900.0,1877.777778,2500.0,1200.0
9,2025-01-10,2600,39,380,19500.0,1950.000000,2600.0,1200.0
10,2025-01-11,2800,40,400,22300.0,2027.272727,2800.0,1200.0
11,2025-01-12,3000,42,420,25300.0,2108.333333,3000.0,1200.0
12,2025-01-13,3100,43,430,28400.0,2184.615385,3100.0,1200.0
13,2025-01-14,3300,45,450,31700.0,2264.285714,3300.0,1200.0
14,2025-01-15,3500,47,470,35200.0,2346.666667,3500.0,1200.0

#### 3. **Exponentially Weighted Window (EWM)**

**What it does**

Recent observations get more weight than older ones.

Older data never completely disappears, but its influence fades over time.

**Syntax:**
```python
df["column"].ewm(span=3).mean()
```

**Important Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
<th>Example</th>
</tr>
<tr>
<td><i>span</i></td>
<td>Most commonly used smoothing parameter</td>
<td>span=5</td>
</tr>
<tr>
<td><i>alpha</i></td>
<td>Smoothing factor (0–1)</td>
<td>alpha=0.3</td>
</tr>
<tr>
<td><i>com</i></td>
<td>Center of mass (alternative to span)</td>
<td>com=2</td>
</tr>
<tr>
<td><i>halflife</i></td>
<td>Weight halves after this period</td>
<td>halflife=4</td>
</tr>
<tr>
<td><i>adjust</i></td>
<td>Whether to normalize weights (default True)</td>
<td>adjust=False</td>
</tr>
<tr>
<td><i>min_periods</i></td>
<td>Minimum observations before output</td>
<td>min_periods=2</td>
</tr>
<tr>
<td><i>ignore_na</i></td>
<td>Ignore missing values when weighting</td>
<td>ignore_na=True</td>
</tr>
</table>

>Important: Use only one of span, alpha, com, or halflife because they all define the smoothing in different ways.

In [11]:
df2["EMA"] = (df2["Sales"].ewm(span=5).mean()) #Forecast sales trends while reacting faster to recent changes.
df2

,Date,Sales,Orders,Visitors,Running_Sales,Average_Sales,Best_Sales_Ever,Lowest_Sales_Ever,EMA
0,2025-01-01,1200,22,210,1200.0,1200.000000,1200.0,1200.0,1200.000000
1,2025-01-02,1500,25,250,2700.0,1350.000000,1500.0,1200.0,1380.000000
2,2025-01-03,1700,28,270,4400.0,1466.666667,1700.0,1200.0,1531.578947
3,2025-01-04,1600,27,260,6000.0,1500.000000,1700.0,1200.0,1560.000000
4,2025-01-05,2000,31,300,8000.0,1600.000000,2000.0,1200.0,1728.909953
5,2025-01-06,1800,30,295,9800.0,1633.333333,2000.0,1200.0,1754.887218
6,2025-01-07,2200,35,330,12000.0,1714.285714,2200.0,1200.0,1912.481787
7,2025-01-08,2500,37,360,14500.0,1812.500000,2500.0,1200.0,2116.272799
8,2025-01-09,2400,36,355,16900.0,1877.777778,2500.0,1200.0,2213.374368
9,2025-01-10,2600,39,380,19500.0,1950.000000,2600.0,1200.0,2344.523912
10,2025-01-11,2800,40,400,22300.0,2027.272727,2800.0,1200.0,2498.125061
11,2025-01-12,3000,42,420,25300.0,2108.333333,3000.0,1200.0,2666.716097
12,2025-01-13,3100,43,430,28400.0,2184.615385,3100.0,1200.0,2811.890002
13,2025-01-14,3300,45,450,31700.0,2264.285714,3300.0,1200.0,2975.152588
14,2025-01-15,3500,47,470,35200.0,2346.666667,3500.0,1200.0,3150.502164

#### 4. **Shift**

**What it does**

Moves values up or down.

No calculations.

**Syntax:**
```python
df["column"].shift(
    periods=1,
    freq=None,
    fill_value=None
)
```

**Important Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
<th>Example</th>
</tr>
<tr>
<td><i>periods</i></td>
<td>Number of rows to shift</td>
<td>periods=1</td>
</tr>
<tr>
<td><i>freq</i></td>
<td>Shift by a calendar frequency (requires datetime index)</td>
<td>freq="D"</td>
</tr>
<tr>
<td><i>fill_value</i></td>
<td>Value used for new missing positions</td>
<td>fill_value=0</td>
</tr>
</table>



**Use Cases**

1. **Previous Day Sales**

In [12]:
df3 = pd.DataFrame({
    "Date": pd.date_range("2025-01-01", periods=15),
    "Sales":[
        1200,1500,1700,1600,2000,
        1800,2200,2500,2400,2600,
        2800,3000,3100,3300,3500
    ],
    "Orders":[
        22,25,28,27,31,
        30,35,37,36,39,
        40,42,43,45,47
    ],
    "Visitors":[
        210,250,270,260,300,
        295,330,360,355,380,
        400,420,430,450,470
    ]
})

In [13]:
df3['Yesterday_Sales'] = df3['Sales'].shift()
df3

         Date  Sales  Orders  Visitors  Yesterday_Sales
0  2025-01-01   1200      22       210              NaN
1  2025-01-02   1500      25       250           1200.0
2  2025-01-03   1700      28       270           1500.0
3  2025-01-04   1600      27       260           1700.0
4  2025-01-05   2000      31       300           1600.0
5  2025-01-06   1800      30       295           2000.0
6  2025-01-07   2200      35       330           1800.0
7  2025-01-08   2500      37       360           2200.0
8  2025-01-09   2400      36       355           2500.0
9  2025-01-10   2600      39       380           2400.0
10 2025-01-11   2800      40       400           2600.0
11 2025-01-12   3000      42       420           2800.0
12 2025-01-13   3100      43       430           3000.0
13 2025-01-14   3300      45       450           3100.0
14 2025-01-15   3500      47       470           3300.0

2. **Next Day Sales**

In [18]:
df3['Tomorrow_Sales'] = df3['Sales'].shift(-1)
df3

,Date,Sales,Orders,Visitors,Yesterday_Sales,Tommorow_Sales,Sales_Change,Tomorrow_Sales
0,2025-01-01,1200,22,210,NaN,1500.0,NaN,1500.0
1,2025-01-02,1500,25,250,1200.0,1700.0,300.0,1700.0
2,2025-01-03,1700,28,270,1500.0,1600.0,200.0,1600.0
3,2025-01-04,1600,27,260,1700.0,2000.0,-100.0,2000.0
4,2025-01-05,2000,31,300,1600.0,1800.0,400.0,1800.0
5,2025-01-06,1800,30,295,2000.0,2200.0,-200.0,2200.0
6,2025-01-07,2200,35,330,1800.0,2500.0,400.0,2500.0
7,2025-01-08,2500,37,360,2200.0,2400.0,300.0,2400.0
8,2025-01-09,2400,36,355,2500.0,2600.0,-100.0,2600.0
9,2025-01-10,2600,39,380,2400.0,2800.0,200.0,2800.0
10,2025-01-11,2800,40,400,2600.0,3000.0,200.0,3000.0
11,2025-01-12,3000,42,420,2800.0,3100.0,200.0,3100.0
12,2025-01-13,3100,43,430,3000.0,3300.0,100.0,3300.0
13,2025-01-14,3300,45,450,3100.0,3500.0,200.0,3500.0
14,2025-01-15,3500,47,470,3300.0,NaN,200.0,NaN

#### 5. **Diff**

**What it does**

Subtracts the previous value from the current value.

**Syntax:**
```python
df["column"].diff(
    periods=1
)
```
**Important Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
<th>Example</th>
</tr>
<tr>
<td><i>periods</i></td>
<td>Difference between current row and row <i>n</i> periods away</td>
<td>periods=1</td>
</tr>
</table>

**Use Cases**
**Daily Sales Increase**

In [15]:
df3['Sales_Change'] = (df3['Sales'].diff())
df3

,Date,Sales,Orders,Visitors,Yesterday_Sales,Tommorow_Sales,Sales_Change
0,2025-01-01,1200,22,210,NaN,1500.0,NaN
1,2025-01-02,1500,25,250,1200.0,1700.0,300.0
2,2025-01-03,1700,28,270,1500.0,1600.0,200.0
3,2025-01-04,1600,27,260,1700.0,2000.0,-100.0
4,2025-01-05,2000,31,300,1600.0,1800.0,400.0
5,2025-01-06,1800,30,295,2000.0,2200.0,-200.0
6,2025-01-07,2200,35,330,1800.0,2500.0,400.0
7,2025-01-08,2500,37,360,2200.0,2400.0,300.0
8,2025-01-09,2400,36,355,2500.0,2600.0,-100.0
9,2025-01-10,2600,39,380,2400.0,2800.0,200.0
10,2025-01-11,2800,40,400,2600.0,3000.0,200.0
11,2025-01-12,3000,42,420,2800.0,3100.0,200.0
12,2025-01-13,3100,43,430,3000.0,3300.0,100.0
13,2025-01-14,3300,45,450,3100.0,3500.0,200.0
14,2025-01-15,3500,47,470,3300.0,NaN,200.0

#### 6. **Rank**

**What it does**

Assigns rankings based on values.

**Syntax:**
```python
df["column"].rank(
    axis=0,
    method="average",
    numeric_only=False,
    na_option="keep",
    ascending=True,
    pct=False
)
```

**Important Parameters:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Description</th>
<th>Example</th>
</tr>
<tr>
<td><i>ascending</i></td>
<td>Rank from smallest (True) or largest (False)</td>
<td>ascending=False</td>
</tr>
<tr>
<td><i>method</i></td>
<td>How to rank ties</td>
<td>method="dense"</td>
</tr>
<tr>
<td><i>na_option</i></td>
<td>Handle missing values</td>
<td>na_option="bottom"</td>
</tr>
<tr>
<td><i>pct</i></td>
<td>Return percentile ranks</td>
<td>pct=True</td>
</tr>
<tr>
<td><i>numeric_only</i></td>
<td>Rank only numeric columns (for DataFrames)</td>
<td>numeric_only=True</td>
</tr>
</table>


**Use Cases**

**Top Selling Products**

In [16]:
df4 = pd.DataFrame({
    "Date": pd.date_range("2025-01-01", periods=15),
    "Sales":[
        1200,1500,1700,1600,2000,
        1800,2200,2500,2400,2600,
        2800,3000,3100,3300,3500
    ],
    "Orders":[
        22,25,28,27,31,
        30,35,37,36,39,
        40,42,43,45,47
    ],
    "Visitors":[
        210,250,270,260,300,
        295,330,360,355,380,
        400,420,430,450,470
    ]
})

In [17]:
df4['Sales_Rank'] = df4['Sales'].rank(ascending=False)
df4

         Date  Sales  Orders  Visitors  Sales_Rank
0  2025-01-01   1200      22       210        15.0
1  2025-01-02   1500      25       250        14.0
2  2025-01-03   1700      28       270        12.0
3  2025-01-04   1600      27       260        13.0
4  2025-01-05   2000      31       300        10.0
5  2025-01-06   1800      30       295        11.0
6  2025-01-07   2200      35       330         9.0
7  2025-01-08   2500      37       360         7.0
8  2025-01-09   2400      36       355         8.0
9  2025-01-10   2600      39       380         6.0
10 2025-01-11   2800      40       400         5.0
11 2025-01-12   3000      42       420         4.0
12 2025-01-13   3100      43       430         3.0
13 2025-01-14   3300      45       450         2.0
14 2025-01-15   3500      47       470         1.0

#### **⭐ Most Important Parameters to Remember**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Function</th>
<th>Parameters You Should Master</th>
</tr>
<tr>
<td><i>rolling()</i></td>
<td>window, min_periods, center, on</td>
</tr>
<tr>
<td><i>expanding()</i></td>
<td>min_periods</td>
</tr>
<tr>
<td><i>ewm()</i></td>
<td>span, alpha, adjust, min_periods</td>
</tr>
<tr>
<td><i>shift()</i></td>
<td>periods, fill_value, freq</td>
</tr>
<tr>
<td><i>diff()</i></td>
<td>periods</td>
</tr>
<tr>
<td><i>rank()</i></td>
<td>ascending, method, pct, na_option</td>
</tr>
</table>